version: '3.8'

services:
  # Production App (Frontend + Backend) - MongoDB Atlas 사용
  app:
    image: ddalgiwuu/n3rve-platform:latest
    container_name: n3rve-app
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3001
      MONGODB_URI: ${MONGODB_URI}
      DATABASE_URL: ${DATABASE_URL:-${MONGODB_URI}}
      JWT_SECRET: ${JWT_SECRET:-changeThisJWTSecret}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-${JWT_SECRET:-changeThisJWTSecret}}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL:-https://n3rve-onboarding.com/api/auth/google/callback}
      CORS_ORIGIN: ${CORS_ORIGIN:-https://n3rve-onboarding.com}
      DROPBOX_ACCESS_TOKEN: ${DROPBOX_ACCESS_TOKEN}
      VITE_DROPBOX_ACCESS_TOKEN: ${VITE_DROPBOX_ACCESS_TOKEN}
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
      - "3001:3001"
    networks:
      - n3rve-network

networks:
  n3rve-network:
    driver: bridge