version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: n3rve-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - n3rve-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    image: ddalgiwuu/n3rve-onboarding-platform:backend-latest
    container_name: n3rve-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - PORT=3001
    volumes:
      - backend_logs:/app/logs
      - uploads:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - n3rve-network

  frontend:
    image: ddalgiwuu/n3rve-onboarding-platform:frontend-latest
    container_name: n3rve-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_DROPBOX_APP_KEY=${VITE_DROPBOX_APP_KEY}
      - VITE_DROPBOX_REDIRECT_URI=${VITE_DROPBOX_REDIRECT_URI}
      - VITE_DROPBOX_ACCESS_TOKEN=${VITE_DROPBOX_ACCESS_TOKEN}
      - VITE_APP_URL=${VITE_APP_URL}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - n3rve-network

volumes:
  mongodb_data:
  backend_logs:
  uploads:

networks:
  n3rve-network:
    driver: bridge