version: '3.8'

services:
  # MongoDB Atlas 사용 (로컬 MongoDB 컨테이너 제거)
  backend:
    image: ddalgiwuu/n3rve-platform:backend-latest
    container_name: n3rve-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}  # MongoDB Atlas URL
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - PORT=3001
    volumes:
      - backend_logs:/app/logs
      - uploads:/app/uploads
    networks:
      - n3rve-network

  # Frontend Service
  frontend:
    image: ddalgiwuu/n3rve-platform:frontend-latest
    container_name: n3rve-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/letsencrypt:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
    networks:
      - n3rve-network

volumes:
  backend_logs:
  uploads:

networks:
  n3rve-network:
    driver: bridge