import { create } from 'zustand'
import { persist } from 'zustand/middleware'

type Language = 'ko' | 'en'

interface LanguageState {
  language: Language
  setLanguage: (language: Language) => void
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: 'ko',
      setLanguage: (language) => set({ language })
    }),
    {
      name: 'language-storage'
    }
  )
)

// 번역 데이터
export const translations = {
  ko: {
    // 공통
    'common.submit': '제출',
    'common.cancel': '취소',
    'common.save': '저장',
    'common.next': '다음',
    'common.previous': '이전',
    'common.upload': '업로드',
    'common.download': '다운로드',
    'common.delete': '삭제',
    'common.edit': '수정',
    'common.view': '보기',
    'common.search': '검색',
    'common.filter': '필터',
    'common.required': '필수',
    'common.select': '선택하세요',
    'common.selectLanguage': '언어를 선택하세요',
    'common.noItemsAdded': '추가된 항목이 없습니다',
    
    // 인증
    'auth.login': '로그인',
    'auth.logout': '로그아웃',
    'auth.email': '이메일',
    'auth.email.placeholder': 'email@example.com',
    'auth.password': '비밀번호',
    'auth.rememberMe': '로그인 상태 유지',
    'auth.forgotPassword': '비밀번호 찾기',
    'auth.noAccount': '아직 계정이 없으신가요?',
    'auth.register': '회원가입',
    'auth.welcomeTitle': 'N3RVE 음원 발매 시스템',
    'auth.welcomeSubtitle': '음원 발매의 모든 것',
    
    // 온보딩
    'onboarding.title': '음원 발매 신청',
    'onboarding.subtitle': 'N3RVE를 통해 전 세계에 당신의 음악을 들려주세요',
    'onboarding.submitSuccess': '음원 발매 신청이 완료되었습니다!',
    'onboarding.submitError': '제출 중 오류가 발생했습니다',
    'onboarding.step1': '앨범 정보',
    'onboarding.step1.description': '앨범의 기본 정보를 입력해주세요',
    'onboarding.step2': '앨범 정보',
    'onboarding.step3': '트랙 정보',
    'onboarding.step4': '파일 업로드',
    'onboarding.step5': '발매 정보',
    'onboarding.step6': '최종 확인',
    
    // 아티스트 정보
    'artist.nameKo': '아티스트명 (한글)',
    'artist.nameEn': '아티스트명 (영문)',
    'artist.labelName': '레이블/소속사명',
    'artist.genre': '장르',
    'artist.biography': '아티스트 소개',
    
    // 앨범 정보
    'album.info': '앨범 정보',
    'album.title': '앨범명',
    'album.title.placeholder': '앨범명을 입력하세요 (한글, 영어 등)',
    'album.title.help': '기본 앨범명을 입력하세요. 언어에 관계없이 자유롭게 입력 가능합니다.',
    'album.addTranslation': '다른 언어로 표기 추가',
    'album.addTranslation.help': '앨범명을 다른 언어로도 표기하고 싶은 경우 체크하세요.',
    'album.translationLanguage': '번역 언어',
    'album.translatedTitle': '번역된 앨범명',
    'album.selectLanguage': '언어를 선택하세요',
    'album.translatedTitle.placeholder': '선택한 언어로 앨범명을 입력하세요',
    'album.titleKo': '앨범명 (한글)',
    'album.titleEn': '앨범명 (영문)',
    'validation.required.albumTitle': '앨범명은 필수입니다',
    'validation.translationRequired': '번역을 활성화한 경우 언어와 번역된 제목을 입력해주세요',
    'album.type': '앨범 유형',
    'album.releaseFormat': '앨범 형식',
    'album.releaseDate': '발매일',
    'album.description': '앨범 소개',
    'album.type.single': '싱글',
    'album.type.ep': 'EP/미니앨범',
    'album.type.album': '정규앨범',
    'album.type.single.desc': '1-3곡',
    'album.type.ep.desc': '4-6곡',
    'album.type.album.desc': '7곡 이상',
    
    // 트랙 정보
    'track.title': '곡명',
    'track.titleKo': '곡명 (한글)',
    'track.titleEn': '곡명 (영문)',
    'track.composer': '작곡가',
    'track.lyricist': '작사가',
    'track.arranger': '편곡자',
    'track.featuring': '피처링',
    
    // 파일 업로드
    'upload.coverImage': '앨범 커버 이미지',
    'upload.audioFiles': '음원 파일',
    'upload.artistPhoto': '아티스트 사진',
    'upload.additionalFiles': '추가 자료',
    
    // 대시보드
    'dashboard.welcome': '환영합니다',
    'dashboard.subtitle': 'N3RVE와 함께 전 세계에 당신의 음악을 들려주세요',
    'dashboard.newSubmissionDesc': '새로운 음원을 등록하세요',
    'dashboard.submissions': '제출 내역',
    'dashboard.underReview': '검토 중',
    'dashboard.released': '발매 완료',
    'dashboard.noSubmissions': '아직 제출한 음원이 없습니다',
    'dashboard.registerFirstTrack': '지금 바로 첫 음원을 등록해보세요!',
    'dashboard.registerTrack': '음원 등록하기',
    'dashboard.quickGuide': '빠른 가이드',
    'dashboard.step1Title': '아티스트 정보 입력',
    'dashboard.step1Desc': '기본 정보와 장르 선택',
    'dashboard.step2Title': '앨범 & 트랙 정보',
    'dashboard.step2Desc': '발매일과 크레딧 정보',
    'dashboard.step3Title': '파일 업로드',
    'dashboard.step3Desc': '커버, 음원, 가사 등',
    'dashboard.step4Title': '발매 설정',
    'dashboard.step4Desc': '유통 플랫폼 선택',
    'dashboard.reviewNote': '모든 제출은 N3RVE 팀이 꼼꼼히 검토합니다',
    'dashboard.recentSubmissions': '최근 제출 내역',
    'dashboard.status': '상태',
    'dashboard.pending': '검토중',
    'dashboard.approved': '승인됨',
    'dashboard.rejected': '반려됨',
    
    // 메뉴
    'menu.dashboard': '대시보드',
    'menu.newSubmission': '새 음원 등록',
    'menu.submissions': '제출 내역',
    'menu.guide': '가이드',
    'menu.settings': '설정',
    'menu.adminDashboard': '관리자 대시보드',
    'menu.submissions.manage': '제출 관리',
    'menu.customerManagement': '고객 관리',
    'menu.artistProfile': '아티스트 프로필 가이드',
    
    // 아티스트 프로필 가이드
    'artistProfile.title': '아티스트 프로필 관리 가이드',
    'artistProfile.subtitle': 'Spotify for Artists와 Apple Music for Artists 설정 방법',
    'artistProfile.spotify.title': 'Spotify for Artists',
    'artistProfile.spotify.claim': '프로필 클레임하기',
    'artistProfile.spotify.claim.step1': '1. Spotify for Artists 웹사이트 방문',
    'artistProfile.spotify.claim.step2': '2. "Get Access" 버튼 클릭',
    'artistProfile.spotify.claim.step3': '3. Spotify 계정으로 로그인',
    'artistProfile.spotify.claim.step4': '4. 아티스트명 검색 및 선택',
    'artistProfile.spotify.claim.step5': '5. 본인 인증 (소셜미디어 또는 공식 웹사이트)',
    'artistProfile.spotify.claim.step6': '6. 승인 대기 (보통 1-3일 소요)',
    'artistProfile.spotify.verify': '프로필 인증받기',
    'artistProfile.spotify.verify.desc': '파란색 체크마크를 받으려면 월 리스너 250명 이상 필요',
    'artistProfile.spotify.manage': '프로필 관리하기',
    'artistProfile.spotify.manage.bio': '아티스트 소개 작성',
    'artistProfile.spotify.manage.photo': '프로필 및 헤더 이미지 업로드',
    'artistProfile.spotify.manage.social': '소셜미디어 계정 연결',
    'artistProfile.spotify.manage.playlist': '아티스트 플레이리스트 생성',
    'artistProfile.spotify.manage.concerts': '공연 정보 추가',
    'artistProfile.apple.title': 'Apple Music for Artists',
    'artistProfile.apple.claim': '프로필 클레임하기',
    'artistProfile.apple.claim.step1': '1. Apple Music for Artists 앱 다운로드',
    'artistProfile.apple.claim.step2': '2. Apple ID로 로그인',
    'artistProfile.apple.claim.step3': '3. 아티스트 검색 및 클레임 요청',
    'artistProfile.apple.claim.step4': '4. 역할 선택 (아티스트/매니저/레이블)',
    'artistProfile.apple.claim.step5': '5. 연락처 정보 입력',
    'artistProfile.apple.claim.step6': '6. 승인 대기 (최대 48시간)',
    'artistProfile.apple.manage': '프로필 관리하기',
    'artistProfile.apple.manage.bio': '아티스트 스토리 작성',
    'artistProfile.apple.manage.photo': '아티스트 이미지 업로드',
    'artistProfile.apple.manage.social': '소셜미디어 링크 추가',
    'artistProfile.apple.manage.milestones': '마일스톤 및 하이라이트 설정',
    'artistProfile.tips.title': '프로필 관리 팁',
    'artistProfile.tips.consistency': '모든 플랫폼에서 일관된 아티스트명과 이미지 사용',
    'artistProfile.tips.quality': '고품질 이미지 사용 (최소 2400x2400px)',
    'artistProfile.tips.update': '정기적으로 프로필 업데이트',
    'artistProfile.tips.engage': '팬들과 소통하기 위한 기능 활용',
    'artistProfile.tips.analytics': '분석 도구를 통해 리스너 이해하기',
    'artistProfile.social.title': '소셜미디어 연동',
    'artistProfile.social.instagram': 'Instagram 연동으로 스토리와 포스트 표시',
    'artistProfile.social.twitter': 'Twitter 연동으로 최신 트윗 표시',
    'artistProfile.social.facebook': 'Facebook 페이지 연동으로 이벤트 정보 공유',
    'artistProfile.social.tiktok': 'TikTok 연동으로 바이럴 콘텐츠 홍보',
    'artistProfile.benefits.title': '프로필 관리의 이점',
    'artistProfile.benefits.visibility': '검색 노출 증가',
    'artistProfile.benefits.credibility': '공식 인증으로 신뢰도 향상',
    'artistProfile.benefits.insights': '상세한 리스너 분석 데이터',
    'artistProfile.benefits.promotion': '신곡 홍보 기능 사용 가능',
    'artistProfile.benefits.playlist': '플레이리스트 피칭 기회',
    'artistProfile.cta': '지금 바로 아티스트 프로필을 관리해보세요!',
    'artistProfile.moreInfo': '자세한 정보',
    'artistProfile.spotifyLink': 'Spotify for Artists 바로가기',
    'artistProfile.appleLink': 'Apple Music for Artists 바로가기',
    
    // 장르
    'genre.alternative': '얼터너티브',
    'genre.blues': '블루스',
    'genre.childrensMusic': '어린이 음악',
    'genre.classical': '클래식',
    'genre.comedy': '코미디',
    'genre.country': '컨트리',
    'genre.dance': '댄스',
    'genre.electronic': '일렉트로닉',
    'genre.hipHopRap': '힙합/랩',
    'genre.holiday': '홀리데이',
    'genre.indiePop': '인디팝',
    'genre.jazz': '재즈',
    'genre.kPop': 'K-POP',
    'genre.latin': '라틴',
    'genre.newAge': '뉴에이지',
    'genre.opera': '오페라',
    'genre.pop': '팝',
    'genre.rbSoul': 'R&B/소울',
    'genre.reggae': '레게',
    'genre.rock': '록',
    'genre.singerSongwriter': '싱어송라이터',
    'genre.soundtrack': '사운드트랙',
    'genre.vocal': '보컬',
    'genre.world': '월드',
    
    // 공통 텍스트
    'text.maxSelection': '최대 {{count}}개 선택 가능',
    'text.optional': '선택사항',
    'text.autoSaved': '자동 저장됨',
    'text.previousStep': '이전 단계',
    'text.nextStep': '다음 단계',
    'text.help': '문의사항이 있으신가요?',
    'text.contactSupport': '고객센터에 연락주세요',
    'text.placeholder.artistNameKo': '예: 아이유',
    'text.placeholder.artistNameEn': '예: IU',
    'text.placeholder.labelName': '레이블 또는 소속사명',
    'text.placeholder.artistBio': '아티스트 소개를 입력해주세요',
    'text.info.bioDisplay': '이 정보는 음원 사이트에 표시될 수 있습니다',
    
    // 섹션 제목
    'section.artistInfo': '아티스트 정보',
    'section.labelInfo': '소속사 정보',
    'section.genreSelection': '장르 선택',
    'section.artistBio': '아티스트 소개',
    'section.albumTitle': '앨범 제목',
    'section.releaseInfo': '발매 정보',
    'section.albumDescription': '앨범 소개',
    
    // 추가 텍스트
    'text.placeholder.albumTitleKo': '예: 꽃갈피 둘',
    'text.placeholder.albumTitleEn': '예: Flower Bookmark 2',
    'text.placeholder.albumDescription': '앨범 소개를 입력해주세요',
    'text.releaseDateNotice': '발매일 안내',
    'text.releaseDateNotice1': '발매일은 최소 4주 후로 설정하시는 것을 권장합니다',
    'text.releaseDateNotice2': '음원 심사 및 유통사 등록에 시간이 소요됩니다',
    'text.releaseDateNotice3': '긴급 발매가 필요한 경우 별도 문의 바랍니다',
    'text.onboarding.step2.description': '앨범의 기본 정보를 입력해주세요',
    'text.onboarding.step3.description': '앨범에 포함될 트랙 정보를 입력해주세요',
    
    // 트랙 관련
    'track.number': '트랙 {{number}}',
    'track.titleTrack': '타이틀곡',
    'track.setAsTitleTrack': '타이틀곡',
    'track.trackTitle': '트랙 제목',
    'track.creditInfo': '크레딧 정보',
    'track.addTrack': '트랙 추가',
    'track.titleTrackNotice': '타이틀곡은 반드시 1개를 선택해주세요. 음원 사이트에서 대표곡으로 표시됩니다.',
    'track.trackList': '트랙 목록',
    'track.selectTrack': '트랙을 선택하세요',
    'track.trackDetails': '트랙 상세 정보',
    'track.basicInfo': '기본 정보',
    'track.credits': '크레딧',
    'track.additionalInfo': '추가 정보',
    'track.placeholder.titleKo': '예: 밤편지',
    'track.placeholder.titleEn': '예: Through the Night',
    'track.placeholder.composer': '작곡가명',
    'track.placeholder.lyricist': '작사가명',
    'track.placeholder.arranger': '편곡자명 (선택)',
    'track.placeholder.featuring': '피처링 아티스트 (선택)',
    'track.allFieldsRequired': '모든 필수 항목을 입력해주세요',
    'track.contributorNotice': '⚠️ Spotify 정책: 작곡가, 작사가, 편곡자는 반드시 법적 실명(Full Legal Name)을 사용해야 합니다.',
    'track.contributorNoticeDetail': '별칭이나 불완전한 이름 사용시 불이익이 있을 수 있습니다. Primary/Featuring 아티스트는 예명 사용 가능합니다.',
    'track.additionalCredits': '추가 크레딧',
    'track.producer': '프로듀서',
    'track.mixer': '믹싱 엔지니어',
    'track.masterer': '마스터링 엔지니어',
    'track.placeholder.producer': '프로듀서명 (선택)',
    'track.placeholder.mixer': '믹싱 엔지니어명 (선택)',
    'track.placeholder.masterer': '마스터링 엔지니어명 (선택)',
    'track.metadata': '트랙 메타데이터',
    'track.isrc': 'ISRC 코드',
    'track.placeholder.isrc': '예: USKRE2400001',
    'track.isrcDesc': '국제표준녹음코드 (입력하지 않으면 자동 생성)',
    'track.trackVersion': '트랙 버전',
    'track.version.original': '오리지널',
    'track.version.remix': '리믹스',
    'track.version.acoustic': '어쿠스틱',
    'track.version.live': '라이브',
    'track.version.instrumental': '인스트루멘탈',
    'track.version.demo': '데모',
    'track.version.radio': '라디오 에디트',
    'track.version.extended': '익스텐디드',
    'track.version.other': '기타',
    'track.lyricsLanguage': '가사 언어',
    'track.explicitContentOld': '성인 콘텐츠',
    'track.explicitContentDesc': '욕설, 폭력적 내용 포함',
    'track.previewSettings': '프리뷰 설정',
    'track.previewDesc': '틱톡 사운드, Apple Music 프리뷰 등에 사용되는 30초 미리듣기 구간 설정',
    'track.previewStart': '시작 지점 (초)',
    'track.metadataLanguage': '메타데이터 언어',
    'track.metadataLanguage.description': '트랙 정보가 표시될 기본 언어',
    'track.albumNotes': '앨범 소개',
    'track.albumNotes.description': '한국 DSP에서 표시될 앨범 소개글',
    'track.albumNotes.placeholder': '앨범에 대한 소개나 설명을 작성해주세요...',
    'track.territory': '지역 설정',
    'track.territory.description': '음원이 배포될 지역을 선택하세요',
    'track.territory.world': '전 세계',
    'track.territory.selected': '특정 지역 선택',
    'track.territory.africa': '아프리카',
    'track.territory.americas': '아메리카',
    'track.territory.asia': '아시아',
    'track.territory.europe': '유럽',
    'track.territory.oceania': '오세아니아',
    'track.dspTerritories': 'DSP별 지역 설정',
    'track.dspTerritories.description': '각 DSP별로 다른 지역 설정을 사용할 수 있습니다',
    'track.dspTerritories.useDefault': '기본 설정 사용',
    'track.dspTerritories.useCustom': '개별 설정',
    'track.dspTerritories.configure': '설정',
    'track.dspCustomSettings': '개 DSP 커스텀 설정',
    'track.dspDefaultSettings': '모든 DSP가 기본 지역 설정을 사용합니다',
    'track.dspManageSettings': 'DSP 설정 관리',
    'track.selectWorld': '전 세계 선택',
    'track.selectAll': '전체 선택',
    'track.deselectAll': '모두 해제',
    'track.selectedTerritories': '선택된 지역',
    'track.explicitContent': '명시적 콘텐츠',
    'track.explicitContent.notExplicit': '명시적 콘텐츠 아님',
    'track.explicitContent.explicit': '명시적 콘텐츠',
    'track.explicitContent.description': '욕설, 성적 내용 등 19세 미만 부적절한 내용 포함 여부',
    'track.audioLanguage': '오디오 언어',
    'track.audioLanguage.instrumental': 'Instrumental (가사 없음)',
    'track.audioLanguage.description': '노래 가사의 언어 또는 연주곡인 경우 Instrumental 선택',
    'track.translations': '번역',
    'track.addTranslation': '번역 추가',
    'track.translatedTitle': '번역된 제목',
    'track.translatedTitle.placeholder': '번역된 트랙 제목',
    'track.marketing': '마케팅',
    'track.metadataTab': '음원 메타데이터 탭',
    'track.productLevel': '프로덕트 레벨',
    'track.assetLevel': '에셋 레벨',
    'track.originalReleaseDate': 'Original Release Date',
    'track.recordingYear': 'Recording Year',
    'track.recordingLocation': 'Recording Location',
    'common.language': '언어',
    'track.productLevel.description': 'Product Level 정보는 앨범 전체에 적용됩니다',
    'track.releaseInfo': '발매 정보',
    'track.releaseTime': '발매 시간',
    'track.releaseTimezone': '발매 시간대',
    'track.albumDescription': '앨범 설명',
    'track.albumIntroduction': '앨범 소개',
    'track.albumIntroduction.placeholder': '앨범의 컨셉, 제작 배경 등을 소개해주세요',
    'track.detailedDescription': '상세 설명',
    'track.detailedDescription.placeholder': '각 트랙의 의미, 메시지 등 상세한 설명을 작성해주세요',
    'track.marketingStrategy': '마케팅 전략',
    'track.targetAudience': '타겟 오디언스',
    'track.targetAudience.placeholder': '예: 10-20대 K-Pop 팬층',
    'track.marketingKeywords': '마케팅 키워드',
    'track.marketingKeywords.placeholder': '키워드 입력 후 Enter',
    'track.promotionPlans': '프로모션 계획',
    'track.promotionPlans.placeholder': 'SNS 마케팅, 콘서트, 미디어 활동 등의 프로모션 계획을 작성해주세요',
    'common.add': '추가',
    'common.selectCountry': '국가를 선택하세요',
    'artist.addMainArtist': '메인 아티스트 추가',
    'artist.addFeaturingArtist': '피처링 아티스트 추가',
    'artist.name': '아티스트명',
    'artist.name.placeholder': '아티스트명을 입력하세요',
    'artist.addTranslation': '다른 언어로 표기 추가',
    'artist.translationLanguage': '번역 언어',
    'artist.translatedName': '번역된 아티스트명',
    'artist.translatedName.placeholder': '번역된 이름을 입력하세요',
    'artist.newArtist': '음원 플랫폼에 등록되지 않은 신규 아티스트입니다',
    'artist.platformIds': '플랫폼 아티스트 ID',
    'artist.platformIds.description': 'Spotify, Apple Music의 아티스트 ID가 있다면 추가해주세요.',
    'artist.countryOfOrigin': '출신 국가',
    'artist.youtubeChannelId': 'YouTube O&O Channel ID',
    'artist.youtubeChannelId.placeholder': 'YouTube Channel ID를 입력하세요',
    'artist.addPlatformId': '플랫폼 아티스트 ID 추가',
    'artist.selectPlatform': '플랫폼 선택',
    'artist.selectPlatform.placeholder': '플랫폼을 선택하세요',
    'artist.artistIdUrl': '아티스트 ID/URL',
    'artist.artistIdUrl.placeholder': '아티스트 ID 또는 프로필 URL을 입력하세요',
    'artist.mainArtists': '메인 아티스트',
    'artist.mainArtists.empty': '메인 아티스트를 추가해주세요.',
    'artist.featuringArtists': '피처링 아티스트',
    'artist.featuringArtists.empty': '피처링 아티스트가 있다면 추가해주세요.',
    'artist.required': '아티스트명은 필수입니다',
    'artist.minMainArtists': '최소 한 명의 메인 아티스트가 필요합니다',
    'artist.translationRequired': '번역을 활성화한 경우 언어와 번역된 이름을 입력해주세요',
    'artist.existingArtistInfo': '기존 아티스트의 경우, 플랫폼 ID를 추가해주시면 더 빠른 처리가 가능합니다.',
    'artist.findAppleMusicId': 'Apple Music ID 찾는 방법:',
    'artist.appleMusicStep1': '1. Apple Music에서 아티스트 프로필 페이지 접속',
    'artist.appleMusicStep2': '2. URL의 마지막 숫자 부분만 복사',
    'artist.appleMusicExample': '예: https://music.apple.com/artist/아티스트명/',
    'artist.findSpotifyUri': 'Spotify Artist URI 찾는 방법:',
    'artist.spotifyMac': 'Mac:',
    'artist.spotifyMacStep1': '1. Spotify 앱에서 아티스트 페이지 접속',
    'artist.spotifyMacStep2': '2. 아티스트명 옆 ••• 클릭',
    'artist.spotifyMacStep3': '3. Option(⌥) 키를 누른 상태에서 "Share" 클릭',
    'artist.spotifyMacStep4': '4. "Copy Spotify URI" 선택',
    'artist.spotifyWindows': 'Windows:',
    'artist.spotifyWindowsStep1': '1. Spotify 앱에서 아티스트 페이지 접속',
    'artist.spotifyWindowsStep2': '2. 아티스트명 옆 ••• 클릭',
    'artist.spotifyWindowsStep3': '3. Alt 키를 누른 상태에서 "Share" 클릭',
    'artist.spotifyWindowsStep4': '4. "Copy Spotify URI" 선택',
    'artist.spotifyExample': '예: spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX',
    'artist.youtubeInfo': 'YouTube Music에서 공식 아티스트 채널을 운영하고 있다면, Channel ID를 입력해주세요.',
    
    // Artist Modal specific translations
    'artist.modal.addMain': '메인 아티스트 추가',
    'artist.modal.addFeaturing': '피처링 아티스트 추가',
    'artist.modal.required': '아티스트명은 필수입니다',
    'artist.modal.translationLanguageRequired': '번역 언어를 선택해주세요',
    'artist.modal.translatedNameRequired': '번역된 아티스트명을 입력해주세요',
    'artist.modal.spotifyIdRequired': 'Spotify Artist ID는 필수입니다 (새 아티스트인 경우 New 버튼을 클릭하세요)',
    'artist.modal.appleIdRequired': 'Apple Music Artist ID는 필수입니다 (새 아티스트인 경우 New 버튼을 클릭하세요)',
    'artist.modal.name.placeholder': '아티스트명을 입력하세요',
    'artist.modal.addTranslation': '다른 언어로 표기 추가',
    'artist.modal.selectLanguage': '언어를 선택하세요',
    'artist.modal.translatedName.placeholder': '번역된 아티스트명',
    'artist.modal.nationality': '국적',
    'artist.modal.youtubeChannelId': 'YouTube 채널 ID',
    'artist.modal.youtubeChannelId.placeholder': '예: UC16niRr50-MSBwiO3YDb3RA',
    'artist.modal.youtubeChannelId.help': 'YouTube 채널 URL에서 /channel/ 다음 부분을 입력하세요',
    'artist.modal.platformIds': '소셜 미디어 / 스트리밍 플랫폼',
    'artist.modal.newArtist': 'New 아티스트',
    'artist.modal.newArtistInfo': '새로운 아티스트로 등록됩니다. 아티스트 페이지가 생성될 예정입니다.',
    'artist.modal.changeToExisting': '기존 아티스트로 변경',
    'artist.modal.spotifyId': 'Spotify Artist ID',
    'artist.modal.spotifyId.placeholder': '예: 6HQYnRM4OzToCYPpVBInPt',
    'artist.modal.appleId': 'Apple Music Artist ID',
    'artist.modal.appleId.placeholder': '예: 277905876',
    'artist.modal.helpModal.spotify.title': 'Spotify Artist ID 찾기',
    'artist.modal.helpModal.apple.title': 'Apple Music Artist ID 찾기',
    'artist.modal.helpModal.macWindows': 'Mac / Windows (웹 브라우저)',
    'artist.modal.helpModal.app': '앱',
    'artist.modal.helpModal.spotify.webSteps': '1. Spotify 웹 플레이어 (open.spotify.com) 접속\n2. 아티스트 페이지로 이동\n3. 브라우저 주소창에서 URL 확인\n4. URL 예시: https://open.spotify.com/artist/6HQYnRM4OzToCYPpVBInPt\n5. 굵게 표시된 부분이 Artist ID입니다',
    'artist.modal.helpModal.spotify.appSteps': '1. 아티스트 페이지에서 ⋯ (더보기) 메뉴 탭\n2. "공유" → "링크 복사" 선택\n3. 복사된 링크에서 artist/ 다음 부분이 ID입니다',
    'artist.modal.helpModal.spotify.idFormat': 'Artist ID는 22자의 영문자와 숫자 조합입니다',
    'artist.modal.helpModal.apple.webSteps': '1. Apple Music 웹 (music.apple.com) 접속\n2. 아티스트 페이지로 이동\n3. 브라우저 주소창에서 URL 확인\n4. URL 예시: https://music.apple.com/kr/artist/iu/277905876\n5. 굵게 표시된 숫자가 Artist ID입니다',
    'artist.modal.helpModal.apple.appSteps': '1. 아티스트 페이지에서 ⋯ (더보기) 버튼 탭\n2. "공유" → "링크 복사" 선택\n3. 복사된 링크의 마지막 숫자가 ID입니다',
    'artist.modal.helpModal.apple.idFormat': 'Artist ID는 9-10자리의 숫자입니다',
    'artist.modal.helpModal.confirm': '확인',
    'artist.modal.cancel': '취소',
    'artist.modal.save': '저장',
    'artist.modal.helpModal.spotifyApp': 'Spotify 앱',
    'artist.modal.helpModal.appleApp': 'Apple Music 앱',
    'artist.modal.helpModal.spotifyWebStep1': '1. Spotify 웹 플레이어 (open.spotify.com) 접속',
    'artist.modal.helpModal.spotifyWebStep2': '2. 아티스트 페이지로 이동',
    'artist.modal.helpModal.spotifyWebStep3': '3. 브라우저 주소창에서 URL 확인',
    'artist.modal.helpModal.spotifyWebStep4': '4. URL 예시: https://open.spotify.com/artist/',
    'artist.modal.helpModal.spotifyWebStep5': '5. 굵게 표시된 부분이 Artist ID입니다',
    'artist.modal.helpModal.spotifyAppStep1': '1. 아티스트 페이지에서 ⋯ (더보기) 메뉴 탭',
    'artist.modal.helpModal.spotifyAppStep2': '2. "공유" → "링크 복사" 선택',
    'artist.modal.helpModal.spotifyAppStep3': '3. 복사된 링크에서 artist/ 다음 부분이 ID입니다',
    'artist.modal.helpModal.appleWebStep1': '1. Apple Music 웹 (music.apple.com) 접속',
    'artist.modal.helpModal.appleWebStep2': '2. 아티스트 페이지로 이동',
    'artist.modal.helpModal.appleWebStep3': '3. 브라우저 주소창에서 URL 확인',
    'artist.modal.helpModal.appleWebStep4': '4. URL 예시: https://music.apple.com/kr/artist/iu/',
    'artist.modal.helpModal.appleWebStep5': '5. 굵게 표시된 숫자가 Artist ID입니다',
    'artist.modal.helpModal.appleAppStep1': '1. 아티스트 페이지에서 ⋯ (더보기) 버튼 탭',
    'artist.modal.helpModal.appleAppStep2': '2. "공유" → "링크 복사" 선택',
    'artist.modal.helpModal.appleAppStep3': '3. 복사된 링크의 마지막 숫자가 ID입니다',
    
    // UI texts for ReleaseSubmission
    'ui.confirmDelete': '저장된 내용을 삭제하시겠습니까?',
    'ui.dataDeleted': '저장된 내용이 삭제되었습니다',
    'ui.delete': '삭제',
    'ui.autoSaveEnabled': '자동 저장 활성화됨',
    'ui.previousContent': '이전에 작성하던 내용이 있습니다',
    'ui.lastSaved': '마지막 저장',
    
    // Submission Success page
    'submission.success.reviewNotice': '담당자가 검토 후 24시간 이내에 연락드리겠습니다.',
    'submission.success.reviewNoticeEn': 'Our team will review and contact you within 24 hours.',
    'submission.success.completedItems': '제출 완료 항목',
    'submission.success.goToDashboard': '대시보드로 이동',
    'submission.success.newRelease': '새 음원 등록',
    'genre.mainGenre': '메인 장르',
    'genre.selectMainGenre': '메인 장르를 선택하세요',
    'genre.mainGenreRequired': '메인 장르를 선택해주세요',
    'genre.subGenre': '서브 장르',
    'genre.selectSubGenre': '서브 장르를 선택하세요',
    'genre.subGenreRequired': '서브 장르를 선택하거나 직접 입력해주세요',
    'genre.enterCustom': '직접 입력',
    'genre.subGenre.placeholder': '서브 장르를 직접 입력하세요',
    'genre.selectFromList': '목록에서 선택하기',
    'autosave.saving': '저장 중...',
    'autosave.justSaved': '방금 저장됨',
    'autosave.savedMinutesAgo': '{{minutes}}분 전 저장됨',
    'country.kr': '한국',
    'country.us': '미국',
    'country.jp': '일본',
    'country.cn': '중국',
    'country.gb': '영국',
    'country.fr': '프랑스',
    'country.de': '독일',
    'country.other': '기타',
    'contributor.add': '기여자 추가',
    'contributor.name.placeholder': '기여자 이름을 입력하세요',
    'track.contributorInfo': '기여자 정보',
    'track.contributorInfo.empty': '작곡가, 작사가, 편곡자 등 기여자를 추가해주세요.',
    'track.previewEnd': '종료 지점 (초)',
    
    // 파일 업로드
    'text.onboarding.step4.description': '음원 발매에 필요한 파일을 업로드해주세요',
    'upload.clickToUpload': '클릭하여 업로드',
    'upload.dragOrClick': '또는 파일을 드래그해주세요',
    'upload.recommendedSize': '권장 크기: 3000x3000px',
    'upload.format': '형식: {{format}}',
    'upload.changeFile': '파일 변경',
    'upload.clickToUploadAudio': '클릭하여 음원 파일 업로드',
    'upload.multipleFiles': '여러 파일 선택 가능',
    'upload.trackOrder': '트랙 순서대로 파일을 선택해주세요',
    'upload.recommendedAudioFormat': '형식: WAV, FLAC (최소 44.1kHz 24bit)',
    'upload.supportedAudioFormats': '지원 형식: 44.1kHz~192kHz, 16~32bit',
    'upload.maxFileSize': '최대 파일 크기: 2GB',
    'upload.additionalMaterials': '추가 자료 업로드',
    'upload.additionalMaterialsDesc': '가사, 악보, 기타 문서 등',
    'upload.optionalFormats': '선택사항: PDF, DOC, TXT 등',
    'upload.filesCount': '{{count}}개 파일',
    'upload.coverImageRequired': '앨범 커버 이미지는 필수입니다',
    'upload.audioFilesRequired': '음원 파일을 업로드해주세요',
    'upload.viewTechnicalGuide': '기술 사양 가이드 보기',
    'upload.motionArt': '모션 아트',
    'upload.uploadMotionArt': '모션 아트 업로드',
    'upload.motionArtDesc': '1:1 비율, 15-30초 MP4 파일',
    'upload.musicVideo': '뮤직 비디오',
    'upload.uploadMusicVideo': '뮤직 비디오 업로드',
    'upload.musicVideoDesc': '16:9 비율, HD 이상 MP4/MOV 파일',
    
    // 발매 정보
    'text.onboarding.step5.description': '발매 정보 및 저작권 정보를 입력해주세요',
    'release.distributors': '유통사 선택',
    'release.priceType': '가격 유형',
    'release.paid': '유료',
    'release.free': '무료',
    'release.price': '판매 가격 (원)',
    'release.copyrightInfo': '저작권 정보',
    'release.copyrightHolder': '저작권자',
    'release.copyrightYear': '저작권 연도',
    'release.cRights': 'Ⓒ Rights (음원 제작권)',
    'release.pRights': 'Ⓟ Rights (아트워크 제작권)',
    'release.recordingCountry': '녹음 국가',
    'release.recordingLanguage': '녹음 언어',
    'release.upc': 'UPC 코드',
    'release.catalogNumber': '카탈로그 번호',
    'release.originalReleaseDate': 'Original Release Date',
    'release.consumerReleaseDate': 'Consumer Release Date',
    'release.originalReleaseDateDesc': '음원사이트 표기용 발매일',
    'release.consumerReleaseDateDesc': '실제 음원이 라이브되는 날짜',
    'release.preview': '프리뷰 설정',
    'release.previewStart': '프리뷰 시작점 (초)',
    'release.previewStartDesc': '틱톡 사운드 클립 시작점 (기본: 0초)',
    'release.territory': '배포 지역',
    'release.worldwide': '전세계',
    'release.selectCountries': '특정 국가 선택',
    'release.excludeCountries': '제외 국가',
    'release.albumNotes': '앨범 노트',
    'release.albumNotesDesc': '앨범 소개나 크레딧 정보',
    'release.koreanDSP': '한국 DSP 전용 정보',
    'release.lyricsAttached': '가사 첨부',
    'release.artistPageLink': '아티스트 페이지 링크',
    'release.releaseTime': '발매 시간',
    'release.timezone': '시간대',
    'release.selectTimezone': '시간대를 선택하세요',
    'release.timezoneHelp': '음원이 발매될 기준 시간대를 선택하세요',
    'release.enterTime': '시간을 입력하세요',
    'release.timezoneConversion': '타임존 변환',
    'release.timeInTimezone': '{{timezone}} 시간',
    'release.nextDay': '(다음날)',
    'release.previousDay': '(전날)',
    'release.timezoneNote': '시간대별 발매 시간이 표시됩니다',
    'release.translation': '번역 정보',
    'release.koreanTitle': '한국어 제목',
    'release.englishTitle': '영어 제목',
    'release.notes': '추가 요청사항',
    
    // Advanced Formats
    'release.advancedFormats': '고급 포맷 옵션',
    'release.dolbyAtmos': 'Dolby Atmos',
    'release.dolbyAtmosDesc': '이 릴리즈는 Dolby Atmos 마스터를 포함합니다',
    'release.dolbyAtmosRequirements': 'Dolby Atmos 요구사항',
    'release.motionArt': '모션 아트',
    'release.motionArtDesc': '앨범 아트에 애니메이션 효과를 추가합니다 (Apple Music 등 지원)',
    'release.motionArtSettings': '모션 아트 설정',
    'release.motionArt.autoPlay': '자동 재생',
    'release.motionArt.loop': '반복 재생',
    'release.motionArt.showControls': '컨트롤 표시',
    
    // DSP Profile Update
    'release.dspProfileUpdate': 'DSP 프로필 업데이트',
    'release.dspProfileUpdate.checkbox': '모든 DSP에 프로필 사진 업데이트',
    'release.dspProfileUpdate.internationalForm': '국제 DSP 프로필 업데이트 (JotForm)',
    'release.dspProfileUpdate.internationalFormDesc': 'Spotify, Apple Music 등 국제 DSP의 프로필 사진을 업데이트하려면 아래 링크를 이용하세요.',
    'release.dspProfileUpdate.koreanDSPInfo': '한국 DSP 프로필 업데이트 안내',
    'release.dspProfileUpdate.koreanDSPDesc': '한국 DSP (멜론, 지니, 벅스, 바이브)의 경우 아래 정보를 작성해 주세요.',
    'release.dspProfileUpdate.formLink': '프로필 업데이트 양식 작성하기',
    
    // Album Introduction
    'release.albumIntroduction': '앨범 소개',
    'release.albumIntroductionDesc': 'Apple Music 및 한국 DSP에 표시될 앨범 소개글',
    'release.albumIntroductionPlaceholder': '이 앨범에 대한 소개, 제작 배경, 특별한 의미 등을 자유롭게 작성해주세요.',
    
    // Korean DSP Enhanced
    'release.koreanDSP.artistPageLinks': '아티스트 페이지 링크',
    'release.koreanDSP.melonLink': '멜론 아티스트 페이지',
    'release.koreanDSP.genieLink': '지니 아티스트 페이지',
    'release.koreanDSP.bugsLink': '벅스 아티스트 페이지',
    'release.koreanDSP.vibeLink': '바이브 아티스트 페이지',
    'release.koreanDSP.linkPlaceholder': '예: https://www.melon.com/artist/...',
    'release.koreanDSP.translationNotice': '번역 안내',
    'release.koreanDSP.translationNoticeDesc': '아티스트명과 레이블명에 한글과 영문이 모두 포함된 경우, 한국 DSP용 번역이 필요합니다.',
    'release.koreanDSP.artistNameTranslation': '아티스트명 번역',
    'release.koreanDSP.labelNameTranslation': '레이블명 번역',
    'release.koreanDSP.newArtist': '신규 아티스트',
    'release.koreanDSP.newArtistDesc': '한국 DSP에 처음 등록되는 아티스트입니다',
    'release.koreanDSP.creditInfo': '크레딧 정보',
    'release.koreanDSP.albumCredits': '앨범 크레딧',
    'release.koreanDSP.albumCreditsPlaceholder': '프로듀서, 엔지니어, 세션 연주자 등 앨범 제작에 참여한 모든 크레딧 정보를 입력해주세요.',
    
    // Admin Email Preview
    'admin.emailPreview.title': '관리자 이메일 미리보기',
    'admin.emailPreview.subtitle': '한국 DSP 등록을 위해 관리자에게 전송될 이메일 내용입니다',
    'admin.emailPreview.subject': '한국 DSP 정보',
    'admin.emailPreview.newArtistNotice': '* 신규 아티스트 등록 필요',
    'admin.emailPreview.lyricsAttachedNotice': '* 가사 첨부됨',
    
    'release.timedReleaseTitle': '시간대별 발매 안내',
    'release.timedReleaseNotice': '⚠️ 중요: Apple Music 등 일부 DSP는 시간대별 발매를 지원하지 않습니다.',
    'release.timedReleaseWorkaround': '시간대별 발매 방법:',
    'release.timedReleaseStep1': '1. Consumer Release Date를 가장 이른 지역(뉴질랜드)의 발매일로 설정',
    'release.timedReleaseStep2': '2. Territory를 "특정 국가 선택"으로 설정 후 뉴질랜드만 선택',
    'release.timedReleaseStep3': '3. 나머지 지역은 각 시간대에 맞춰 별도 릴리즈로 제출',
    'release.timedReleaseExample': '예시: 한국 시간 2024년 1월 1일 0시 발매를 원할 경우, 뉴질랜드는 2023년 12월 31일 20시에 발매됩니다.',
    
    // Timezone translations
    'timezone.newZealand': '뉴질랜드',
    'timezone.seoul': '서울',
    'timezone.tokyo': '도쿄',
    'timezone.beijing': '베이징',
    'timezone.singapore': '싱가포르',
    'timezone.london': '런던',
    'timezone.paris': '파리',
    'timezone.berlin': '베를린',
    'timezone.newYork': '뉴욕',
    'timezone.chicago': '시카고',
    'timezone.denver': '덴버',
    'timezone.losAngeles': '로스앤젤레스',
    'release.metadata': '릴리즈 메타데이터',
    'release.parentalAdvisory': '성인 콘텐츠 경고',
    'release.parentalAdvisory.none': '해당 없음',
    'release.parentalAdvisory.explicit': '성인 콘텐츠 포함',
    'release.parentalAdvisory.clean': '클린 버전',
    'release.parentalAdvisoryDesc': '앨범 또는 트랙에 성인 콘텐츠가 포함된 경우',
    'release.releaseFormat': '릴리즈 형식',
    'release.format.standard': '표준',
    'release.format.deluxe': '디럭스',
    'release.format.special': '스페셜',
    'release.format.remastered': '리마스터드',
    'release.format.anniversary': '기념판',
    'release.compilationAlbum': '컴필레이션 앨범',
    'release.compilationAlbumDesc': '여러 아티스트의 곡을 모은 앨범',
    'release.preOrder': '예약 판매 설정',
    'release.preOrderDesc': '발매일 이전에 미리 주문 가능',
    'release.preOrderDate': '예약 판매 시작일',
    'release.previouslyReleased': '재발매',
    'release.previouslyReleasedDesc': '이전에 발매된 적이 있는 음원',
    'release.previousReleaseDate': '최초 발매일',
    'release.previousReleaseInfo': '이전 발매 정보',
    'release.previousReleaseInfoPlaceholder': '예: 2020년 ABC 레코드에서 발매, 이번에 리마스터링 및 재유통',
    
    // Territory Selection
    'release.territorySelection': '배포 지역 선택',
    'release.selectSpecificCountries': '특정 국가 선택',
    'release.selectedCountries': '선택된 국가',
    'release.selectAll': '모두 선택',
    'release.deselectAll': '모두 해제',
    'release.countriesSelected': '{{count}}개 국가 선택됨',
    'release.dspExclusions': 'DSP별 제외 국가',
    'release.dspExclusionNotice': '선택한 유통사에서 자동 제외되는 국가들입니다',
    
    // Continents
    'continent.africa': '아프리카',
    'continent.americas': '아메리카',
    'continent.asia': '아시아',
    'continent.europe': '유럽',
    'continent.oceania': '오세아니아',
    
    // Major Countries
    'country.US': '미국',
    'country.GB': '영국',
    'country.JP': '일본',
    'country.CN': '중국',
    'country.KR': '대한민국',
    'country.CA': '캐나다',
    'country.AU': '호주',
    'country.DE': '독일',
    'country.FR': '프랑스',
    'country.IT': '이탈리아',
    'country.ES': '스페인',
    'country.NL': '네덜란드',
    'country.SE': '스웨덴',
    'country.NO': '노르웨이',
    'country.DK': '덴마크',
    'country.FI': '핀란드',
    'country.CH': '스위스',
    'country.AT': '오스트리아',
    'country.BE': '벨기에',
    'country.PL': '폴란드',
    'country.RU': '러시아',
    'country.BR': '브라질',
    'country.MX': '멕시코',
    'country.AR': '아르헨티나',
    'country.IN': '인도',
    'country.ID': '인도네시아',
    'country.TH': '태국',
    'country.MY': '말레이시아',
    'country.SG': '싱가포르',
    'country.PH': '필리핀',
    'country.VN': '베트남',
    'country.TW': '대만',
    'country.HK': '홍콩',
    'country.NZ': '뉴질랜드',
    'country.ZA': '남아프리카',
    'country.EG': '이집트',
    'country.NG': '나이지리아',
    'country.KE': '케냐',
    'country.IL': '이스라엘',
    'country.AE': '아랍에미리트',
    'country.SA': '사우디아라비아',
    'country.TR': '터키',
    'country.GR': '그리스',
    'country.PT': '포르투갈',
    'country.CZ': '체코',
    'country.HU': '헝가리',
    'country.RO': '루마니아',
    'country.UA': '우크라이나',
    'country.CL': '칠레',
    'country.CO': '콜롬비아',
    'country.PE': '페루',
    'country.VE': '베네수엘라',
    
    // DSP Exclusion Countries
    'country.SY': '시리아',
    'country.IR': '이란',
    'country.CU': '쿠바',
    'country.KP': '북한',
    'country.SD': '수단',
    
    // 언어
    'language.korean': '한국어',
    'language.english': '영어',
    'language.japanese': '일본어',
    'language.chinese': '중국어',
    'language.spanish': '스페인어',
    'language.french': '프랑스어',
    'language.german': '독일어',
    'language.instrumental': '인스트루멘탈',
    'language.other': '기타',
    
    // Admin - Submission Management
    'admin.submissionManagement': '제출 관리',
    'admin.submissions.title': '음원 제출 관리',
    'admin.submissions.filter.all': '전체',
    'admin.submissions.filter.pending': '검토중',
    'admin.submissions.filter.approved': '승인됨',
    'admin.submissions.filter.rejected': '반려됨',
    'admin.submissions.search.placeholder': '아티스트명, 앨범명, ID로 검색',
    'admin.submissions.table.id': 'ID',
    'admin.submissions.table.artistName': '아티스트명',
    'admin.submissions.table.releaseTitle': '발매 제목',
    'admin.submissions.table.label': '레이블',
    'admin.submissions.table.submissionDate': '제출일',
    'admin.submissions.table.status': '상태',
    'admin.submissions.table.actions': '작업',
    'admin.submissions.actions.view': '상세보기',
    'admin.submissions.actions.approve': '승인',
    'admin.submissions.actions.reject': '반려',
    'admin.submissions.modal.title': '제출 상세 정보',
    'admin.submissions.modal.artistInfo': '아티스트 정보',
    'admin.submissions.modal.albumInfo': '앨범 정보',
    'admin.submissions.modal.trackInfo': '트랙 정보',
    'admin.submissions.modal.releaseInfo': '발매 정보',
    'admin.submissions.modal.comment': '검토 의견',
    'admin.submissions.modal.comment.placeholder': '승인/반려 사유를 입력하세요',
    'admin.submissions.modal.close': '닫기',
    'admin.submissions.export': 'CSV 내보내기',
    'admin.submissions.exportExcel': 'Excel 내보내기',
    'admin.submissions.pagination.showing': '{{total}}개 중 {{from}}-{{to}}개 표시',
    'admin.submissions.pagination.previous': '이전',
    'admin.submissions.pagination.next': '다음',
    'admin.submissions.noData': '제출된 음원이 없습니다',
    'admin.submissions.loading': '불러오는 중...',
    'admin.submissions.success.approve': '성공적으로 승인되었습니다',
    'admin.submissions.success.reject': '성공적으로 반려되었습니다',
    'admin.submissions.error.approve': '승인 중 오류가 발생했습니다',
    'admin.submissions.error.reject': '반려 중 오류가 발생했습니다',
    'admin.submissions.stats.total': '전체 제출',
    'admin.submissions.stats.pending': '검토 대기',
    'admin.submissions.stats.approved': '승인됨',
    'admin.submissions.stats.rejected': '반려됨',
    'admin.submissions.bulk.selected': '{{count}}개 선택됨',
    'admin.submissions.bulk.approve': '일괄 승인',
    'admin.submissions.bulk.reject': '일괄 반려',
    'admin.submissions.bulk.clear': '선택 해제',
    'admin.submissions.bulk.confirm.approve': '선택한 {{count}}개 항목을 승인하시겠습니까?',
    'admin.submissions.bulk.confirm.reject': '선택한 {{count}}개 항목을 반려하시겠습니까?',
    'admin.submissions.bulk.success.approve': '{{count}}개 항목이 승인되었습니다',
    'admin.submissions.bulk.success.reject': '{{count}}개 항목이 반려되었습니다',
    'admin.submissions.bulk.error.approve': '일괄 승인 중 오류가 발생했습니다',
    'admin.submissions.bulk.error.reject': '일괄 반려 중 오류가 발생했습니다',
    'admin.submissions.modal.tabs.overview': '개요',
    'admin.submissions.modal.tabs.tracks': '트랙',
    'admin.submissions.modal.tabs.files': '파일',
    'admin.submissions.modal.tabs.release': '발매 정보',
    'admin.submissions.modal.tabs.history': '히스토리',
    'admin.submissions.modal.export': '내보내기',
    'admin.submissions.modal.print': '인쇄',
    'admin.submissions.modal.trackList': '트랙 목록',
    'admin.submissions.modal.uploadedFiles': '업로드된 파일',
    'admin.submissions.modal.noFiles': '업로드된 파일이 없습니다',
    'admin.submissions.modal.distribution': '유통 플랫폼',
    'admin.submissions.modal.copyrightInfo': '저작권 정보',
    'admin.submissions.modal.identifiers': '식별자',
    'admin.submissions.modal.marketingPlan': '마케팅 계획',
    'admin.submissions.modal.submissionHistory': '제출 이력',
    'admin.submissions.history.submitted': '제출됨',
    'admin.submissions.history.approved': '승인됨',
    'admin.submissions.history.rejected': '반려됨',
    
    // Confirmation page
    'text.onboarding.step6.description': '입력하신 정보를 확인하고 최종 제출해주세요',
    'confirmation.fileInfo': '파일 정보',
    'confirmation.uploaded': '업로드 완료',
    'confirmation.notUploaded': '업로드 필요',
    'confirmation.filesUploaded': '개 파일',
    'confirmation.termsAcceptance': '이용약관 동의',
    'confirmation.termsDescription': '아래 내용을 확인하고 동의합니다:',
    'confirmation.term1': '입력한 모든 정보가 정확하며 허위 정보가 포함되지 않았습니다',
    'confirmation.term2': '제출한 콘텐츠에 대한 모든 권리를 보유하고 있습니다',
    'confirmation.term3': 'N3RVE의 음원 발매 정책 및 지침에 동의합니다',
    'confirmation.term4': '허위 정보 제출 시 발매가 취소될 수 있음을 인지하고 있습니다',
    'confirmation.submitting': '제출 중...',
    'confirmation.submitRelease': '음원 발매 신청',
    
    // Validation messages
    'validation.noTitleTrack': '타이틀곡을 선택해주세요',
    'validation.multipleTitleTracks': '타이틀곡이 여러 개 선택되었습니다',
    'validation.duplicateIsrc': '중복된 ISRC 코드가 있습니다',
    'validation.explicitContentWarning': '성인 콘텐츠가 포함되어 있으나 Parental Advisory가 설정되지 않았습니다',
    'validation.shortReleaseNotice': '발매일이 2주 이내입니다. 검토 시간이 부족할 수 있습니다',
    'validation.invalidPreOrderDate': '예약 판매 시작일은 발매일보다 빨라야 합니다',
    'validation.noCoverImage': '앨범 커버 이미지를 업로드해주세요',
    'validation.audioFilesMismatch': '음원 파일 수와 트랙 수가 일치하지 않습니다',
    'validation.errorsFound': '오류가 발견되었습니다',
    'validation.warningsFound': '경고 사항',
    
    // QC Validation messages
    'qc.error.doubleSpaces': '연속된 공백이 발견되었습니다',
    'qc.error.leadingTrailingSpaces': '앞뒤 공백을 제거해주세요',
    'qc.error.invalidCharacters': '사용할 수 없는 특수문자가 포함되어 있습니다',
    'qc.error.promotionalText': '홍보성 문구는 사용할 수 없습니다 (NEW, HOT, EXCLUSIVE 등)',
    'qc.error.unmatchedBrackets': '괄호가 올바르게 닫히지 않았습니다',
    'qc.error.invalidISRC': 'ISRC 형식이 올바르지 않습니다',
    'qc.error.invalidCopyrightYear': '저작권 연도 형식이 올바르지 않습니다',
    'qc.error.futureCopyrightYear': '미래의 저작권 연도는 사용할 수 없습니다',
    'qc.error.pastReleaseDate': '과거 날짜로는 발매할 수 없습니다',
    'qc.error.noGenre': '장르를 선택해주세요',
    'qc.error.genericArtistName': 'Various Artists, Unknown 등의 일반적인 아티스트명은 사용할 수 없습니다',
    'qc.error.misleadingArtistName': '아티스트명에 feat., vs, presents 등의 용어를 포함할 수 없습니다',
    'qc.error.abbreviationInArtistName': '아티스트명에는 약어가 아닌 전체 단어를 사용해주세요',
    'qc.error.emojisInTitle': '제목에 이모지를 사용할 수 없습니다',
    'qc.error.forbiddenVersionTerm': 'Original, Original Mix 등은 사용할 수 없습니다. 표준 버전은 버전 표기를 하지 않습니다',
    'qc.error.incorrectFormat': '트랙 수에 따른 올바른 포맷이 아닙니다',
    'qc.error.singleTitleMismatch': '싱글 포맷에서는 모든 트랙이 앨범과 동일한 제목을 가져야 합니다',
    'qc.error.parentalAdvisoryMissing': '성인 콘텐츠가 포함되어 있으나 Parental Advisory가 설정되지 않았습니다',
    
    'qc.warning.akaInArtistName': '아티스트명에 aka/AKA는 공식적인 경우가 아니면 사용하지 않는 것이 좋습니다',
    'qc.warning.versionCapitalization': '버전명의 대소문자를 확인해주세요',
    'qc.warning.sentenceCaseRequired': '이 언어에서는 문장 대소문자 규칙을 사용해야 합니다',
    'qc.warning.germanOrthography': '독일어 움라우트(ä,ö,ü)와 에스체트(ß)를 올바르게 사용해주세요',
    'qc.warning.parentalAdvisoryUnnecessary': '성인 콘텐츠가 없는데 Parental Advisory가 설정되어 있습니다',
    'qc.warning.cleanVersionWithoutExplicit': 'Clean 버전이 있지만 Explicit 버전이 없습니다',
    'qc.warning.titleCase': '영문 제목의 대소문자를 확인해주세요',
    'qc.warning.versionDuplicate': '버전 정보가 제목에 이미 포함되어 있습니다',
    'qc.warning.featuringFormat': '피처링 형식을 확인해주세요 (feat. 권장)',
    'qc.warning.featuringInconsistent': '피처링 표기가 일관되지 않습니다',
    'qc.warning.copyrightSymbolIncluded': '저작권 기호는 자동으로 추가되므로 입력하지 마세요',
    'qc.warning.mixedLanguages': '트랙별 언어가 혼재되어 있습니다',
    'qc.warning.shortReleaseNotice': '발매일까지 2주 미만입니다. 심사가 지연될 수 있습니다',
    'qc.warning.tooManyGenres': '너무 많은 장르가 선택되었습니다 (최대 3개 권장)',
    
    'qc.info.versionFormat': '버전 정보는 제목 끝에 괄호로 표기하는 것이 좋습니다',
    
    'qc.suggestion': '제안',
    'qc.field': '필드',
    'qc.status.passed': 'QC 통과',
    'qc.status.failed': 'QC 실패',
    'qc.status.warnings': '경고',
    'qc.report.title': 'QC 검사 결과',
    'qc.report.subtitle': '발매 전 반드시 수정이 필요한 항목들입니다',
    'qc.report.errors': '필수 수정 사항',
    'qc.report.warnings': '권장 수정 사항',
    'qc.report.info': '참고 사항',
    'qc.report.noIssues': '모든 QC 검사를 통과했습니다',
    'qc.report.fixRequired': '제출 전 오류를 수정해주세요',
    
    // Technical Guide
    'technicalGuide.title': '기술 사양 가이드',
    'technicalGuide.description': 'QC 요구사항을 충족하기 위한 상세 기술 사양입니다',
    'technicalGuide.downloadSpecs': '기술 사양 다운로드',
    'technicalGuide.downloadDescription': 'PDF 형식으로 전체 사양을 다운로드하세요',
    'technicalGuide.downloadPDF': 'PDF 다운로드',
    'technicalGuide.specifications': '사양',
    'technicalGuide.requirements': '요구사항',
    'technicalGuide.correctExamples': '올바른 예시',
    'technicalGuide.incorrectExamples': '잘못된 예시',
    'technicalGuide.proTips': '프로 팁',
    'technicalGuide.audio.title': '오디오 사양',
    'technicalGuide.artwork.title': '아트워크 사양',
    'technicalGuide.motionArt.title': '모션 아트 사양',
    'technicalGuide.dolbyAtmos.title': 'Dolby Atmos 사양',
    'technicalGuide.video.title': '비디오 사양',
    'technicalGuide.needHelp': '도움이 필요하신가요?',
    'technicalGuide.contactSupport': '기술 지원팀이 도와드리겠습니다',
    'technicalGuide.contactButton': '지원팀 문의',
    'technicalGuide.tips.audio1': '최상의 음질을 위해 96kHz/24bit 이상을 권장합니다',
    'technicalGuide.tips.audio2': '마스터링 시 -14 LUFS (스트리밍 기준) 타겟을 고려하세요',
    'technicalGuide.tips.audio3': 'True Peak는 -1dB 이하로 유지하세요',
    'technicalGuide.tips.artwork1': 'RGB 색상 모드를 사용하고 CMYK는 피하세요',
    'technicalGuide.tips.artwork2': '텍스트가 포함된 경우 300DPI 이상 권장',
    'technicalGuide.tips.artwork3': '투명 배경은 지원되지 않습니다',
    'technicalGuide.tips.motionArt1': '루프 재생을 위해 첫 프레임과 마지막 프레임을 일치시키세요',
    'technicalGuide.tips.motionArt2': '파일 크기 최적화를 위해 적절한 비트레이트 사용',
    'technicalGuide.tips.motionArt3': '과도한 움직임이나 깜빡임은 피하세요',
    'technicalGuide.tips.dolbyAtmos1': 'Dolby Atmos Production Suite에서 마스터링 필수',
    'technicalGuide.tips.dolbyAtmos2': '바이노럴 렌더는 반드시 포함되어야 합니다',
    'technicalGuide.tips.dolbyAtmos3': 'Dolby 렌더러에서 최종 테스트 필수',
    'technicalGuide.tips.video1': '고품질 인코딩을 위해 높은 비트레이트 사용',
    'technicalGuide.tips.video2': '색상 공간은 Rec. 709 권장',
    'technicalGuide.tips.video3': '오디오 트랙은 비디오와 완벽히 동기화되어야 합니다'
  },
  en: {
    // Common
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.required': 'Required',
    'common.select': 'Select',
    'common.selectLanguage': 'Select Language',
    'common.noItemsAdded': 'No items added',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.email.placeholder': 'email@example.com',
    'auth.password': 'Password',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': "Don't have an account?",
    'auth.register': 'Sign up',
    'auth.welcomeTitle': 'N3RVE Music Distribution',
    'auth.welcomeSubtitle': 'Everything for music release',
    
    // Onboarding
    'onboarding.title': 'Music Release Application',
    'onboarding.subtitle': 'Share your music with the world through N3RVE',
    'onboarding.submitSuccess': 'Music release application completed!',
    'onboarding.submitError': 'An error occurred during submission',
    'onboarding.step1': 'Artist Information',
    'onboarding.step1.description': 'Enter basic information about the artist',
    'onboarding.step2': 'Album Information',
    'onboarding.step3': 'Track Information',
    'onboarding.step4': 'File Upload',
    'onboarding.step5': 'Release Information',
    'onboarding.step6': 'Final Confirmation',
    
    // Artist Info
    'artist.nameKo': 'Artist Name (Korean)',
    'artist.nameEn': 'Artist Name (English)',
    'artist.labelName': 'Label/Agency Name',
    'artist.genre': 'Genre',
    'artist.biography': 'Artist Biography',
    
    // Album Info
    'album.info': 'Album Information',
    'album.title': 'Album Title',
    'album.title.placeholder': 'Enter album title (Korean, English, etc.)',
    'album.title.help': 'Enter the primary album title. You can enter in any language.',
    'album.addTranslation': 'Add translation in another language',
    'album.addTranslation.help': 'Check if you want to add the album title in another language.',
    'album.translationLanguage': 'Translation Language',
    'album.translatedTitle': 'Translated Album Title',
    'album.selectLanguage': 'Select Language',
    'album.translatedTitle.placeholder': 'Enter album title in selected language',
    'album.titleKo': 'Album Title (Korean)',
    'album.titleEn': 'Album Title (English)',
    'validation.required.albumTitle': 'Album title is required',
    'validation.translationRequired': 'Please enter language and translated title when translation is enabled',
    'album.type': 'Album Type',
    'album.releaseFormat': 'Album Format',
    'album.releaseDate': 'Release Date',
    'album.description': 'Album Description',
    'album.type.single': 'Single',
    'album.type.ep': 'EP/Mini Album',
    'album.type.album': 'Full Album',
    'album.type.single.desc': '1-3 tracks',
    'album.type.ep.desc': '4-6 tracks',
    'album.type.album.desc': '7+ tracks',
    
    // Track Info
    'track.title': 'Track Title',
    'track.titleKo': 'Track Title (Korean)',
    'track.titleEn': 'Track Title (English)',
    'track.composer': 'Composer',
    'track.lyricist': 'Lyricist',
    'track.arranger': 'Arranger',
    'track.featuring': 'Featuring',
    
    // File Upload
    'upload.coverImage': 'Album Cover Image',
    'upload.audioFiles': 'Audio Files',
    'upload.artistPhoto': 'Artist Photo',
    'upload.additionalFiles': 'Additional Files',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.subtitle': 'Share your music with the world together with N3RVE',
    'dashboard.newSubmissionDesc': 'Register a new track',
    'dashboard.submissions': 'Submissions',
    'dashboard.underReview': 'Under Review',
    'dashboard.released': 'Released',
    'dashboard.noSubmissions': 'No submissions yet',
    'dashboard.registerFirstTrack': 'Register your first track now!',
    'dashboard.registerTrack': 'Register Track',
    'dashboard.quickGuide': 'Quick Guide',
    'dashboard.step1Title': 'Artist Information',
    'dashboard.step1Desc': 'Basic info and genre selection',
    'dashboard.step2Title': 'Album & Track Info',
    'dashboard.step2Desc': 'Release date and credits',
    'dashboard.step3Title': 'File Upload',
    'dashboard.step3Desc': 'Cover, audio, lyrics, etc.',
    'dashboard.step4Title': 'Release Settings',
    'dashboard.step4Desc': 'Distribution platform selection',
    'dashboard.reviewNote': 'All submissions are carefully reviewed by the N3RVE team',
    'dashboard.recentSubmissions': 'Recent Submissions',
    'dashboard.status': 'Status',
    'dashboard.pending': 'Pending',
    'dashboard.approved': 'Approved',
    'dashboard.rejected': 'Rejected',
    
    // Menu
    'menu.dashboard': 'Dashboard',
    'menu.newSubmission': 'New Release',
    'menu.submissions': 'Submissions',
    'menu.guide': 'Guide',
    'menu.settings': 'Settings',
    'menu.adminDashboard': 'Admin Dashboard',
    'menu.submissions.manage': 'Manage Submissions',
    'menu.customerManagement': 'Customer Management',
    'menu.artistProfile': 'Artist Profile Guide',
    
    // Artist Profile Guide
    'artistProfile.title': 'Artist Profile Management Guide',
    'artistProfile.subtitle': 'How to set up Spotify for Artists and Apple Music for Artists',
    'artistProfile.spotify.title': 'Spotify for Artists',
    'artistProfile.spotify.claim': 'Claim Your Profile',
    'artistProfile.spotify.claim.step1': '1. Visit Spotify for Artists website',
    'artistProfile.spotify.claim.step2': '2. Click "Get Access" button',
    'artistProfile.spotify.claim.step3': '3. Log in with your Spotify account',
    'artistProfile.spotify.claim.step4': '4. Search and select your artist name',
    'artistProfile.spotify.claim.step5': '5. Verify your identity (social media or official website)',
    'artistProfile.spotify.claim.step6': '6. Wait for approval (usually 1-3 days)',
    'artistProfile.spotify.verify': 'Get Verified',
    'artistProfile.spotify.verify.desc': 'Blue checkmark requires 250+ monthly listeners',
    'artistProfile.spotify.manage': 'Manage Your Profile',
    'artistProfile.spotify.manage.bio': 'Write artist bio',
    'artistProfile.spotify.manage.photo': 'Upload profile and header images',
    'artistProfile.spotify.manage.social': 'Connect social media accounts',
    'artistProfile.spotify.manage.playlist': 'Create artist playlists',
    'artistProfile.spotify.manage.concerts': 'Add concert information',
    'artistProfile.apple.title': 'Apple Music for Artists',
    'artistProfile.apple.claim': 'Claim Your Profile',
    'artistProfile.apple.claim.step1': '1. Download Apple Music for Artists app',
    'artistProfile.apple.claim.step2': '2. Sign in with Apple ID',
    'artistProfile.apple.claim.step3': '3. Search for your artist and request claim',
    'artistProfile.apple.claim.step4': '4. Select role (Artist/Manager/Label)',
    'artistProfile.apple.claim.step5': '5. Enter contact information',
    'artistProfile.apple.claim.step6': '6. Wait for approval (up to 48 hours)',
    'artistProfile.apple.manage': 'Manage Your Profile',
    'artistProfile.apple.manage.bio': 'Write artist story',
    'artistProfile.apple.manage.photo': 'Upload artist images',
    'artistProfile.apple.manage.social': 'Add social media links',
    'artistProfile.apple.manage.milestones': 'Set milestones and highlights',
    'artistProfile.tips.title': 'Profile Management Tips',
    'artistProfile.tips.consistency': 'Use consistent artist name and images across all platforms',
    'artistProfile.tips.quality': 'Use high-quality images (minimum 2400x2400px)',
    'artistProfile.tips.update': 'Update your profile regularly',
    'artistProfile.tips.engage': 'Use features to engage with fans',
    'artistProfile.tips.analytics': 'Understand your listeners through analytics',
    'artistProfile.social.title': 'Social Media Integration',
    'artistProfile.social.instagram': 'Connect Instagram to show stories and posts',
    'artistProfile.social.twitter': 'Connect Twitter to display latest tweets',
    'artistProfile.social.facebook': 'Connect Facebook page to share events',
    'artistProfile.social.tiktok': 'Connect TikTok to promote viral content',
    'artistProfile.benefits.title': 'Benefits of Profile Management',
    'artistProfile.benefits.visibility': 'Increased search visibility',
    'artistProfile.benefits.credibility': 'Enhanced credibility with official verification',
    'artistProfile.benefits.insights': 'Detailed listener analytics',
    'artistProfile.benefits.promotion': 'Access to promotional features',
    'artistProfile.benefits.playlist': 'Playlist pitching opportunities',
    'artistProfile.cta': 'Start managing your artist profile today!',
    'artistProfile.moreInfo': 'Learn More',
    'artistProfile.spotifyLink': 'Go to Spotify for Artists',
    'artistProfile.appleLink': 'Go to Apple Music for Artists',
    
    // Genres
    'genre.alternative': 'Alternative',
    'genre.blues': 'Blues',
    'genre.childrensMusic': "Children's Music",
    'genre.classical': 'Classical',
    'genre.comedy': 'Comedy',
    'genre.country': 'Country',
    'genre.dance': 'Dance',
    'genre.electronic': 'Electronic',
    'genre.hipHopRap': 'Hip-Hop/Rap',
    'genre.holiday': 'Holiday',
    'genre.indiePop': 'Indie Pop',
    'genre.jazz': 'Jazz',
    'genre.kPop': 'K-Pop',
    'genre.latin': 'Latin',
    'genre.newAge': 'New Age',
    'genre.opera': 'Opera',
    'genre.pop': 'Pop',
    'genre.rbSoul': 'R&B/Soul',
    'genre.reggae': 'Reggae',
    'genre.rock': 'Rock',
    'genre.singerSongwriter': 'Singer/Songwriter',
    'genre.soundtrack': 'Soundtrack',
    'genre.vocal': 'Vocal',
    'genre.world': 'World',
    
    // Common Text
    'text.maxSelection': 'Max {{count}} selections',
    'text.optional': 'Optional',
    'text.autoSaved': 'Auto-saved',
    'text.previousStep': 'Previous',
    'text.nextStep': 'Next',
    'text.help': 'Need help?',
    'text.contactSupport': 'Contact support',
    'text.placeholder.artistNameKo': 'e.g. 아이유',
    'text.placeholder.artistNameEn': 'e.g. IU',
    'text.placeholder.labelName': 'Label or Agency name',
    'text.placeholder.artistBio': 'Enter artist biography',
    'text.info.bioDisplay': 'This information may be displayed on music platforms',
    
    // Section Titles
    'section.artistInfo': 'Artist Information',
    'section.labelInfo': 'Label Information',
    'section.genreSelection': 'Genre Selection',
    'section.artistBio': 'Artist Biography',
    'section.albumTitle': 'Album Title',
    'section.releaseInfo': 'Release Information',
    'section.albumDescription': 'Album Description',
    
    // Additional Text
    'text.placeholder.albumTitleKo': 'e.g. 꽃갈피 둘',
    'text.placeholder.albumTitleEn': 'e.g. Flower Bookmark 2',
    'text.placeholder.albumDescription': 'Enter album description',
    'text.releaseDateNotice': 'Release Date Notice',
    'text.releaseDateNotice1': 'We recommend setting the release date at least 2 weeks from now',
    'text.releaseDateNotice2': 'Time is needed for content review and distributor registration',
    'text.releaseDateNotice3': 'Please contact us separately for urgent releases',
    'text.onboarding.step2.description': 'Enter basic information about the album',
    'text.onboarding.step3.description': 'Enter information about tracks in the album',
    
    // Track Related
    'track.number': 'Track {{number}}',
    'track.titleTrack': 'Title Track',
    'track.setAsTitleTrack': 'Title Track',
    'track.trackTitle': 'Track Title',
    'track.creditInfo': 'Credit Information',
    'track.addTrack': 'Add Track',
    'track.titleTrackNotice': 'Please select exactly 1 title track. It will be displayed as the representative song on music platforms.',
    'track.trackList': 'Track List',
    'track.selectTrack': 'Select a track',
    'track.trackDetails': 'Track Details',
    'track.basicInfo': 'Basic Information',
    'track.credits': 'Credits',
    'track.additionalInfo': 'Additional Information',
    'track.placeholder.titleKo': 'e.g. 밤편지',
    'track.placeholder.titleEn': 'e.g. Through the Night',
    'track.placeholder.composer': 'Composer name',
    'track.placeholder.lyricist': 'Lyricist name',
    'track.placeholder.arranger': 'Arranger name (optional)',
    'track.placeholder.featuring': 'Featuring artist (optional)',
    'track.allFieldsRequired': 'Please fill in all required fields',
    'track.contributorNotice': '⚠️ Spotify Policy: Composers, lyricists, and arrangers must use their full legal names.',
    'track.contributorNoticeDetail': 'Penalties may apply for using aliases or incomplete names. Primary/Featuring artists can use stage names.',
    'track.additionalCredits': 'Additional Credits',
    'track.producer': 'Producer',
    'track.mixer': 'Mixing Engineer',
    'track.masterer': 'Mastering Engineer',
    'track.placeholder.producer': 'Producer name (optional)',
    'track.placeholder.mixer': 'Mixing engineer name (optional)',
    'track.placeholder.masterer': 'Mastering engineer name (optional)',
    'track.metadata': 'Track Metadata',
    'track.isrc': 'ISRC Code',
    'track.placeholder.isrc': 'e.g. USKRE2400001',
    'track.isrcDesc': 'International Standard Recording Code (auto-generated if not provided)',
    'track.trackVersion': 'Track Version',
    'track.version.original': 'Original',
    'track.version.remix': 'Remix',
    'track.version.acoustic': 'Acoustic',
    'track.version.live': 'Live',
    'track.version.instrumental': 'Instrumental',
    'track.version.demo': 'Demo',
    'track.version.radio': 'Radio Edit',
    'track.version.extended': 'Extended',
    'track.version.other': 'Other',
    'track.lyricsLanguage': 'Lyrics Language',
    'track.explicitContentOld': 'Explicit Content',
    'track.explicitContentDesc': 'Contains profanity or violent content',
    'track.previewSettings': 'Preview Settings',
    'track.previewDesc': '30-second preview for TikTok Sounds, Apple Music preview, etc.',
    'track.previewStart': 'Start Point (seconds)',
    'track.previewEnd': 'End Point (seconds)',
    'track.metadataLanguage': 'Metadata Language',
    'track.metadataLanguage.description': 'Default language for track information display',
    'track.albumNotes': 'Album Notes',
    'track.albumNotes.description': 'Album introduction for Korean DSPs',
    'track.albumNotes.placeholder': 'Write an introduction or description for the album...',
    'track.territory': 'Territory Settings',
    'track.territory.description': 'Select regions where the music will be distributed',
    'track.territory.world': 'Worldwide',
    'track.territory.selected': 'Select Specific Regions',
    'track.territory.africa': 'Africa',
    'track.territory.americas': 'Americas',
    'track.territory.asia': 'Asia',
    'track.territory.europe': 'Europe',
    'track.territory.oceania': 'Oceania',
    'track.dspTerritories': 'DSP Territory Settings',
    'track.dspTerritories.description': 'Configure different territory settings for each DSP',
    'track.dspTerritories.useDefault': 'Use Default',
    'track.dspTerritories.useCustom': 'Custom Settings',
    'track.dspTerritories.configure': 'Configure',
    'track.dspCustomSettings': ' DSPs with custom settings',
    'track.dspDefaultSettings': 'All DSPs use default territory settings',
    'track.dspManageSettings': 'Manage DSP Settings',
    'track.selectWorld': 'Select World',
    'track.selectAll': 'Select All',
    'track.deselectAll': 'Deselect All',
    'track.selectedTerritories': 'Selected Territories',
    'track.explicitContent': 'Explicit Content',
    'track.explicitContent.notExplicit': 'Not Explicit',
    'track.explicitContent.explicit': 'Explicit',
    'track.explicitContent.description': 'Contains profanity, sexual content, or other inappropriate content for minors',
    'track.audioLanguage': 'Audio Language',
    'track.audioLanguage.instrumental': 'Instrumental (No Lyrics)',
    'track.audioLanguage.description': 'Language of the song lyrics or select Instrumental for instrumental tracks',
    'track.translations': 'Translations',
    'track.addTranslation': 'Add Translation',
    'track.translatedTitle': 'Translated Title',
    'track.translatedTitle.placeholder': 'Translated track title',
    'track.marketing': 'Marketing',
    'track.metadataTab': 'Music Metadata Tab',
    'track.productLevel': 'Product Level',
    'track.assetLevel': 'Asset Level',
    'track.originalReleaseDate': 'Original Release Date',
    'track.recordingYear': 'Recording Year',
    'track.recordingLocation': 'Recording Location',
    'common.language': 'Language',
    'track.productLevel.description': 'Product Level information applies to the entire album',
    'track.releaseInfo': 'Release Information',
    'track.releaseTime': 'Release Time',
    'track.releaseTimezone': 'Release Timezone',
    'track.albumDescription': 'Album Description',
    'track.albumIntroduction': 'Album Introduction',
    'track.albumIntroduction.placeholder': 'Introduce the album concept, production background, etc.',
    'track.detailedDescription': 'Detailed Description',
    'track.detailedDescription.placeholder': 'Write detailed descriptions of each track\'s meaning, message, etc.',
    'track.marketingStrategy': 'Marketing Strategy',
    'track.targetAudience': 'Target Audience',
    'track.targetAudience.placeholder': 'e.g. K-Pop fans aged 10-20',
    'track.marketingKeywords': 'Marketing Keywords',
    'track.marketingKeywords.placeholder': 'Enter keyword and press Enter',
    'track.promotionPlans': 'Promotion Plans',
    'track.promotionPlans.placeholder': 'Write promotion plans including SNS marketing, concerts, media activities, etc.',
    'common.add': 'Add',
    'common.selectCountry': 'Select Country',
    'artist.addMainArtist': 'Add Main Artist',
    'artist.addFeaturingArtist': 'Add Featuring Artist',
    'artist.name': 'Artist Name',
    'artist.name.placeholder': 'Enter artist name',
    'artist.addTranslation': 'Add translation in another language',
    'artist.translationLanguage': 'Translation Language',
    'artist.translatedName': 'Translated Artist Name',
    'artist.translatedName.placeholder': 'Enter translated name',
    'artist.newArtist': 'This is a new artist not registered on music platforms',
    'artist.platformIds': 'Platform Artist IDs',
    'artist.platformIds.description': 'Add artist IDs from Spotify, Apple Music if available.',
    'artist.countryOfOrigin': 'Country of Origin',
    'artist.youtubeChannelId': 'YouTube O&O Channel ID',
    'artist.youtubeChannelId.placeholder': 'Enter YouTube Channel ID',
    'artist.addPlatformId': 'Add Platform Artist ID',
    'artist.selectPlatform': 'Select Platform',
    'artist.selectPlatform.placeholder': 'Select a platform',
    'artist.artistIdUrl': 'Artist ID/URL',
    'artist.artistIdUrl.placeholder': 'Enter artist ID or profile URL',
    'artist.mainArtists': 'Main Artists',
    'artist.mainArtists.empty': 'Please add main artists.',
    'artist.featuringArtists': 'Featuring Artists',
    'artist.featuringArtists.empty': 'Add featuring artists if any.',
    'artist.required': 'Artist name is required',
    'artist.minMainArtists': 'At least one main artist is required',
    'artist.translationRequired': 'Please enter language and translated name when translation is enabled',
    'artist.existingArtistInfo': 'For existing artists, adding platform IDs will speed up processing.',
    'artist.findAppleMusicId': 'How to find Apple Music ID:',
    'artist.appleMusicStep1': '1. Go to artist profile page on Apple Music',
    'artist.appleMusicStep2': '2. Copy only the number part at the end of the URL',
    'artist.appleMusicExample': 'e.g. https://music.apple.com/artist/artist-name/',
    'artist.findSpotifyUri': 'How to find Spotify Artist URI:',
    'artist.spotifyMac': 'Mac:',
    'artist.spotifyMacStep1': '1. Go to artist page in Spotify app',
    'artist.spotifyMacStep2': '2. Click ••• next to artist name',
    'artist.spotifyMacStep3': '3. Hold Option(⌥) key and click "Share"',
    'artist.spotifyMacStep4': '4. Select "Copy Spotify URI"',
    'artist.spotifyWindows': 'Windows:',
    'artist.spotifyWindowsStep1': '1. Go to artist page in Spotify app',
    'artist.spotifyWindowsStep2': '2. Click ••• next to artist name',
    'artist.spotifyWindowsStep3': '3. Hold Alt key and click "Share"',
    'artist.spotifyWindowsStep4': '4. Select "Copy Spotify URI"',
    'artist.spotifyExample': 'e.g. spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX',
    'artist.youtubeInfo': 'If you have an official artist channel on YouTube Music, please enter the Channel ID.',
    'genre.mainGenre': 'Main Genre',
    'genre.selectMainGenre': 'Select main genre',
    'genre.mainGenreRequired': 'Please select main genre',
    'genre.subGenre': 'Sub Genre',
    'genre.selectSubGenre': 'Select sub genre',
    'genre.subGenreRequired': 'Please select or enter sub genre',
    'genre.enterCustom': 'Enter custom',
    'genre.subGenre.placeholder': 'Enter custom sub genre',
    'genre.selectFromList': 'Select from list',
    'autosave.saving': 'Saving...',
    'autosave.justSaved': 'Just saved',
    'autosave.savedMinutesAgo': 'Saved {{minutes}} minutes ago',
    'country.kr': 'Korea',
    'country.us': 'United States',
    'country.jp': 'Japan',
    'country.cn': 'China',
    'country.gb': 'United Kingdom',
    'country.fr': 'France',
    'country.de': 'Germany',
    'country.other': 'Other',
    'contributor.add': 'Add Contributor',
    'contributor.name.placeholder': 'Enter contributor name',
    'track.contributorInfo': 'Contributor Information',
    'track.contributorInfo.empty': 'Add contributors such as composers, lyricists, arrangers, etc.',
    
    // File Upload
    'text.onboarding.step4.description': 'Upload files required for music release',
    'upload.clickToUpload': 'Click to upload',
    'upload.dragOrClick': 'or drag files here',
    'upload.recommendedSize': 'Recommended size: 3000x3000px',
    'upload.format': 'Format: {{format}}',
    'upload.changeFile': 'Change files',
    'upload.clickToUploadAudio': 'Click to upload audio files',
    'upload.multipleFiles': 'Multiple files can be selected',
    'upload.trackOrder': 'Please select files in track order',
    'upload.recommendedAudioFormat': 'Format: WAV, FLAC (minimum 44.1kHz 24bit)',
    'upload.supportedAudioFormats': 'Supported: 44.1kHz-192kHz, 16-32bit',
    'upload.maxFileSize': 'Max file size: 2GB',
    'upload.additionalMaterials': 'Upload additional materials',
    'upload.additionalMaterialsDesc': 'Lyrics, sheet music, other documents',
    'upload.optionalFormats': 'Optional: PDF, DOC, TXT, etc',
    'upload.filesCount': '{{count}} files',
    'upload.coverImageRequired': 'Album cover image is required',
    'upload.audioFilesRequired': 'Please upload audio files',
    'upload.viewTechnicalGuide': 'View Technical Specifications Guide',
    'upload.motionArt': 'Motion Art',
    'upload.uploadMotionArt': 'Upload Motion Art',
    'upload.motionArtDesc': '1:1 aspect ratio, 15-30 second MP4 file',
    'upload.musicVideo': 'Music Video',
    'upload.uploadMusicVideo': 'Upload Music Video',
    'upload.musicVideoDesc': '16:9 aspect ratio, HD or higher MP4/MOV file',
    
    // Release Information
    'text.onboarding.step5.description': 'Enter release and copyright information',
    'release.distributors': 'Select Distributors',
    'release.priceType': 'Price Type',
    'release.paid': 'Paid',
    'release.free': 'Free',
    'release.price': 'Sale Price (KRW)',
    'release.copyrightInfo': 'Copyright Information',
    'release.copyrightHolder': 'Copyright Holder',
    'release.copyrightYear': 'Copyright Year',
    'release.cRights': 'Ⓒ Rights (Sound Recording)',
    'release.pRights': 'Ⓟ Rights (Artwork)',
    'release.recordingCountry': 'Recording Country',
    'release.recordingLanguage': 'Recording Language',
    'release.upc': 'UPC Code',
    'release.catalogNumber': 'Catalog Number',
    'release.originalReleaseDate': 'Original Release Date',
    'release.consumerReleaseDate': 'Consumer Release Date',
    'release.originalReleaseDateDesc': 'Display date on music platforms',
    'release.consumerReleaseDateDesc': 'Actual go-live date',
    'release.preview': 'Preview Settings',
    'release.previewStart': 'Preview Start (seconds)',
    'release.previewStartDesc': 'TikTok sound clip start point (default: 0s)',
    'release.territory': 'Distribution Territory',
    'release.worldwide': 'Worldwide',
    'release.selectCountries': 'Select Countries',
    'release.excludeCountries': 'Exclude Countries',
    'release.albumNotes': 'Album Notes',
    'release.albumNotesDesc': 'Album introduction or credit information',
    'release.koreanDSP': 'Korean DSP Information',
    'release.lyricsAttached': 'Lyrics Attached',
    'release.artistPageLink': 'Artist Page Link',
    'release.releaseTime': 'Release Time',
    'release.timezone': 'Time Zone',
    'release.selectTimezone': 'Select time zone',
    'release.timezoneHelp': 'Select the time zone for your release',
    'release.enterTime': 'Please enter time',
    'release.timezoneConversion': 'Timezone Conversion',
    'release.timeInTimezone': '{{timezone}} Time',
    'release.nextDay': '(next day)',
    'release.previousDay': '(previous day)',
    'release.timezoneNote': 'Release time displayed by timezone',
    'release.translation': 'Translation Information',
    'release.koreanTitle': 'Korean Title',
    'release.englishTitle': 'English Title',
    'release.notes': 'Additional Requests',
    
    // Advanced Formats
    'release.advancedFormats': 'Advanced Format Options',
    'release.dolbyAtmos': 'Dolby Atmos',
    'release.dolbyAtmosDesc': 'This release includes Dolby Atmos master',
    'release.dolbyAtmosRequirements': 'Dolby Atmos Requirements',
    'release.motionArt': 'Motion Art',
    'release.motionArtDesc': 'Add animated effects to album art (supported on Apple Music, etc.)',
    'release.motionArtSettings': 'Motion Art Settings',
    'release.motionArt.autoPlay': 'Auto Play',
    'release.motionArt.loop': 'Loop',
    'release.motionArt.showControls': 'Show Controls',
    
    // DSP Profile Update
    'release.dspProfileUpdate': 'DSP Profile Update',
    'release.dspProfileUpdate.checkbox': 'Update profile picture on all DSPs',
    'release.dspProfileUpdate.internationalForm': 'International DSP Profile Update (JotForm)',
    'release.dspProfileUpdate.internationalFormDesc': 'Use the link below to update profile pictures on international DSPs like Spotify and Apple Music.',
    'release.dspProfileUpdate.koreanDSPInfo': 'Korean DSP Profile Update Information',
    'release.dspProfileUpdate.koreanDSPDesc': 'For Korean DSPs (Melon, Genie, Bugs, Vibe), please fill out the information below.',
    'release.dspProfileUpdate.formLink': 'Fill out profile update form',
    
    // Album Introduction
    'release.albumIntroduction': 'Album Introduction',
    'release.albumIntroductionDesc': 'Album introduction to be displayed on Apple Music and Korean DSPs',
    'release.albumIntroductionPlaceholder': 'Feel free to write about this album, its production background, special meaning, etc.',
    
    // Korean DSP Enhanced
    'release.koreanDSP.artistPageLinks': 'Artist Page Links',
    'release.koreanDSP.melonLink': 'Melon Artist Page',
    'release.koreanDSP.genieLink': 'Genie Artist Page',
    'release.koreanDSP.bugsLink': 'Bugs Artist Page',
    'release.koreanDSP.vibeLink': 'Vibe Artist Page',
    'release.koreanDSP.linkPlaceholder': 'e.g. https://www.melon.com/artist/...',
    'release.koreanDSP.translationNotice': 'Translation Notice',
    'release.koreanDSP.translationNoticeDesc': 'If artist name and label name contain both Korean and English, translation for Korean DSPs is required.',
    'release.koreanDSP.artistNameTranslation': 'Artist Name Translation',
    'release.koreanDSP.labelNameTranslation': 'Label Name Translation',
    'release.koreanDSP.newArtist': 'New Artist',
    'release.koreanDSP.newArtistDesc': 'This is an artist being registered for the first time on Korean DSPs',
    'release.koreanDSP.creditInfo': 'Credit Information',
    'release.koreanDSP.albumCredits': 'Album Credits',
    'release.koreanDSP.albumCreditsPlaceholder': 'Enter all credit information including producers, engineers, session musicians, etc.',
    
    // Admin Email Preview
    'admin.emailPreview.title': 'Admin Email Preview',
    'admin.emailPreview.subtitle': 'Email content to be sent to administrators for Korean DSP registration',
    'admin.emailPreview.subject': 'Korean DSP Information',
    'admin.emailPreview.newArtistNotice': '* New artist registration required',
    'admin.emailPreview.lyricsAttachedNotice': '* Lyrics attached',
    
    'release.timedReleaseTitle': 'Timed Release Guide',
    'release.timedReleaseNotice': '⚠️ Important: Some DSPs like Apple Music do not support timed releases.',
    'release.timedReleaseWorkaround': 'How to achieve timed releases:',
    'release.timedReleaseStep1': '1. Set Consumer Release Date to the earliest timezone (New Zealand)',
    'release.timedReleaseStep2': '2. Set Territory to "Select Countries" and choose only New Zealand',
    'release.timedReleaseStep3': '3. Submit separate releases for other regions according to their timezones',
    'release.timedReleaseExample': 'Example: For a January 1, 2024 00:00 KST release, New Zealand would be December 31, 2023 20:00.',
    
    // Timezone translations
    'timezone.newZealand': 'New Zealand',
    'timezone.seoul': 'Seoul',
    'timezone.tokyo': 'Tokyo',
    'timezone.beijing': 'Beijing',
    'timezone.singapore': 'Singapore',
    'timezone.london': 'London',
    'timezone.paris': 'Paris',
    'timezone.berlin': 'Berlin',
    'timezone.newYork': 'New York',
    'timezone.chicago': 'Chicago',
    'timezone.denver': 'Denver',
    'timezone.losAngeles': 'Los Angeles',
    'release.metadata': 'Release Metadata',
    'release.parentalAdvisory': 'Parental Advisory',
    'release.parentalAdvisory.none': 'None',
    'release.parentalAdvisory.explicit': 'Explicit Content',
    'release.parentalAdvisory.clean': 'Clean Version',
    'release.parentalAdvisoryDesc': 'If album or tracks contain explicit content',
    'release.releaseFormat': 'Release Format',
    'release.format.standard': 'Standard',
    'release.format.deluxe': 'Deluxe',
    'release.format.special': 'Special',
    'release.format.remastered': 'Remastered',
    'release.format.anniversary': 'Anniversary',
    'release.compilationAlbum': 'Compilation Album',
    'release.compilationAlbumDesc': 'Album featuring tracks from various artists',
    'release.preOrder': 'Pre-order Settings',
    'release.preOrderDesc': 'Allow pre-orders before release date',
    'release.preOrderDate': 'Pre-order Start Date',
    'release.previouslyReleased': 'Previously Released',
    'release.previouslyReleasedDesc': 'This content has been released before',
    'release.previousReleaseDate': 'Original Release Date',
    'release.previousReleaseInfo': 'Previous Release Information',
    'release.previousReleaseInfoPlaceholder': 'e.g. Released in 2020 by ABC Records, now remastered and redistributed',
    
    // Territory Selection
    'release.territorySelection': 'Territory Selection',
    'release.selectSpecificCountries': 'Select specific countries',
    'release.selectedCountries': 'Selected Countries',
    'release.selectAll': 'Select All',
    'release.deselectAll': 'Deselect All',
    'release.countriesSelected': '{{count}} countries selected',
    'release.dspExclusions': 'DSP-specific Exclusions',
    'release.dspExclusionNotice': 'These countries are automatically excluded by selected distributors',
    
    // Continents
    'continent.africa': 'Africa',
    'continent.americas': 'Americas',
    'continent.asia': 'Asia',
    'continent.europe': 'Europe',
    'continent.oceania': 'Oceania',
    
    // Major Countries
    'country.US': 'United States',
    'country.GB': 'United Kingdom',
    'country.JP': 'Japan',
    'country.CN': 'China',
    'country.KR': 'South Korea',
    'country.CA': 'Canada',
    'country.AU': 'Australia',
    'country.DE': 'Germany',
    'country.FR': 'France',
    'country.IT': 'Italy',
    'country.ES': 'Spain',
    'country.NL': 'Netherlands',
    'country.SE': 'Sweden',
    'country.NO': 'Norway',
    'country.DK': 'Denmark',
    'country.FI': 'Finland',
    'country.CH': 'Switzerland',
    'country.AT': 'Austria',
    'country.BE': 'Belgium',
    'country.PL': 'Poland',
    'country.RU': 'Russia',
    'country.BR': 'Brazil',
    'country.MX': 'Mexico',
    'country.AR': 'Argentina',
    'country.IN': 'India',
    'country.ID': 'Indonesia',
    'country.TH': 'Thailand',
    'country.MY': 'Malaysia',
    'country.SG': 'Singapore',
    'country.PH': 'Philippines',
    'country.VN': 'Vietnam',
    'country.TW': 'Taiwan',
    'country.HK': 'Hong Kong',
    'country.NZ': 'New Zealand',
    'country.ZA': 'South Africa',
    'country.EG': 'Egypt',
    'country.NG': 'Nigeria',
    'country.KE': 'Kenya',
    'country.IL': 'Israel',
    'country.AE': 'United Arab Emirates',
    'country.SA': 'Saudi Arabia',
    'country.TR': 'Turkey',
    'country.GR': 'Greece',
    'country.PT': 'Portugal',
    'country.CZ': 'Czech Republic',
    'country.HU': 'Hungary',
    'country.RO': 'Romania',
    'country.UA': 'Ukraine',
    'country.CL': 'Chile',
    'country.CO': 'Colombia',
    'country.PE': 'Peru',
    'country.VE': 'Venezuela',
    
    // DSP Exclusion Countries
    'country.SY': 'Syria',
    'country.IR': 'Iran',
    'country.CU': 'Cuba',
    'country.KP': 'North Korea',
    'country.SD': 'Sudan',
    
    // Languages
    'language.korean': 'Korean',
    'language.english': 'English',
    'language.japanese': 'Japanese',
    'language.chinese': 'Chinese',
    'language.spanish': 'Spanish',
    'language.french': 'French',
    'language.german': 'German',
    'language.instrumental': 'Instrumental',
    'language.other': 'Other',
    
    // Admin - Submission Management
    'admin.submissionManagement': 'Submission Management',
    'admin.submissions.title': 'Music Submission Management',
    'admin.submissions.filter.all': 'All',
    'admin.submissions.filter.pending': 'Pending',
    'admin.submissions.filter.approved': 'Approved',
    'admin.submissions.filter.rejected': 'Rejected',
    'admin.submissions.search.placeholder': 'Search by artist, release title, or ID',
    'admin.submissions.table.id': 'ID',
    'admin.submissions.table.artistName': 'Artist Name',
    'admin.submissions.table.releaseTitle': 'Release Title',
    'admin.submissions.table.label': 'Label',
    'admin.submissions.table.submissionDate': 'Submission Date',
    'admin.submissions.table.status': 'Status',
    'admin.submissions.table.actions': 'Actions',
    'admin.submissions.actions.view': 'View Details',
    'admin.submissions.actions.approve': 'Approve',
    'admin.submissions.actions.reject': 'Reject',
    'admin.submissions.modal.title': 'Submission Details',
    'admin.submissions.modal.artistInfo': 'Artist Information',
    'admin.submissions.modal.albumInfo': 'Album Information',
    'admin.submissions.modal.trackInfo': 'Track Information',
    'admin.submissions.modal.releaseInfo': 'Release Information',
    'admin.submissions.modal.comment': 'Review Comment',
    'admin.submissions.modal.comment.placeholder': 'Enter reason for approval/rejection',
    'admin.submissions.modal.close': 'Close',
    'admin.submissions.export': 'Export CSV',
    'admin.submissions.exportExcel': 'Export Excel',
    'admin.submissions.pagination.showing': 'Showing {{from}}-{{to}} of {{total}}',
    'admin.submissions.pagination.previous': 'Previous',
    'admin.submissions.pagination.next': 'Next',
    'admin.submissions.noData': 'No submissions found',
    'admin.submissions.loading': 'Loading...',
    'admin.submissions.success.approve': 'Successfully approved',
    'admin.submissions.success.reject': 'Successfully rejected',
    'admin.submissions.error.approve': 'Error approving submission',
    'admin.submissions.error.reject': 'Error rejecting submission',
    'admin.submissions.stats.total': 'Total Submissions',
    'admin.submissions.stats.pending': 'Pending Review',
    'admin.submissions.stats.approved': 'Approved',
    'admin.submissions.stats.rejected': 'Rejected',
    'admin.submissions.bulk.selected': '{{count}} selected',
    'admin.submissions.bulk.approve': 'Bulk Approve',
    'admin.submissions.bulk.reject': 'Bulk Reject',
    'admin.submissions.bulk.clear': 'Clear Selection',
    'admin.submissions.bulk.confirm.approve': 'Are you sure you want to approve {{count}} items?',
    'admin.submissions.bulk.confirm.reject': 'Are you sure you want to reject {{count}} items?',
    'admin.submissions.bulk.success.approve': '{{count}} items approved successfully',
    'admin.submissions.bulk.success.reject': '{{count}} items rejected successfully',
    'admin.submissions.bulk.error.approve': 'Error during bulk approval',
    'admin.submissions.bulk.error.reject': 'Error during bulk rejection',
    'admin.submissions.modal.tabs.overview': 'Overview',
    'admin.submissions.modal.tabs.tracks': 'Tracks',
    'admin.submissions.modal.tabs.files': 'Files',
    'admin.submissions.modal.tabs.release': 'Release Info',
    'admin.submissions.modal.tabs.history': 'History',
    'admin.submissions.modal.export': 'Export',
    'admin.submissions.modal.print': 'Print',
    'admin.submissions.modal.trackList': 'Track List',
    'admin.submissions.modal.uploadedFiles': 'Uploaded Files',
    'admin.submissions.modal.noFiles': 'No files uploaded',
    'admin.submissions.modal.distribution': 'Distribution Platforms',
    'admin.submissions.modal.copyrightInfo': 'Copyright Information',
    'admin.submissions.modal.identifiers': 'Identifiers',
    'admin.submissions.modal.marketingPlan': 'Marketing Plan',
    'admin.submissions.modal.submissionHistory': 'Submission History',
    'admin.submissions.history.submitted': 'Submitted',
    'admin.submissions.history.approved': 'Approved',
    'admin.submissions.history.rejected': 'Rejected',
    
    // Confirmation page
    'text.onboarding.step6.description': 'Review your information and submit your release',
    'confirmation.fileInfo': 'File Information',
    'confirmation.uploaded': 'Uploaded',
    'confirmation.notUploaded': 'Not uploaded',
    'confirmation.filesUploaded': 'files',
    'confirmation.termsAcceptance': 'Terms & Conditions',
    'confirmation.termsDescription': 'I confirm and agree to the following:',
    'confirmation.term1': 'All information provided is accurate and contains no false information',
    'confirmation.term2': 'I own all rights to the submitted content',
    'confirmation.term3': 'I agree to N3RVE\'s music distribution policies and guidelines',
    'confirmation.term4': 'I understand that releases may be cancelled if false information is submitted',
    'confirmation.submitting': 'Submitting...',
    'confirmation.submitRelease': 'Submit Release',
    
    // Validation messages
    'validation.noTitleTrack': 'Please select a title track',
    'validation.multipleTitleTracks': 'Multiple title tracks selected',
    'validation.duplicateIsrc': 'Duplicate ISRC codes found',
    'validation.explicitContentWarning': 'Explicit content found but Parental Advisory not set',
    'validation.shortReleaseNotice': 'Release date is less than 2 weeks away. Review time may be insufficient',
    'validation.invalidPreOrderDate': 'Pre-order date must be before release date',
    'validation.noCoverImage': 'Please upload album cover image',
    'validation.audioFilesMismatch': 'Number of audio files does not match number of tracks',
    'validation.errorsFound': 'Errors Found',
    'validation.warningsFound': 'Warnings',
    
    // QC Validation messages
    'qc.error.doubleSpaces': 'Double spaces found',
    'qc.error.leadingTrailingSpaces': 'Please remove leading/trailing spaces',
    'qc.error.invalidCharacters': 'Invalid special characters detected',
    'qc.error.promotionalText': 'Promotional text not allowed (NEW, HOT, EXCLUSIVE, etc.)',
    'qc.error.unmatchedBrackets': 'Unmatched brackets detected',
    'qc.error.invalidISRC': 'Invalid ISRC format',
    'qc.error.invalidCopyrightYear': 'Invalid copyright year format',
    'qc.error.futureCopyrightYear': 'Future copyright year not allowed',
    'qc.error.pastReleaseDate': 'Release date cannot be in the past',
    'qc.error.noGenre': 'Please select a genre',
    'qc.error.genericArtistName': 'Generic artist names like Various Artists, Unknown are not allowed',
    'qc.error.misleadingArtistName': 'Artist names cannot contain terms like feat., vs, presents',
    'qc.error.abbreviationInArtistName': 'Please use full words instead of abbreviations in artist names',
    'qc.error.emojisInTitle': 'Emojis are not allowed in titles',
    'qc.error.forbiddenVersionTerm': 'Terms like Original, Original Mix are not allowed. Standard versions should not have version designation',
    'qc.error.incorrectFormat': 'Format does not match track count',
    'qc.error.singleTitleMismatch': 'Single format requires all tracks to have the same title as the album',
    'qc.error.parentalAdvisoryMissing': 'Explicit content found but Parental Advisory not set',
    
    'qc.warning.akaInArtistName': 'aka/AKA in artist names should only be used if officially part of the name',
    'qc.warning.versionCapitalization': 'Please check version name capitalization',
    'qc.warning.sentenceCaseRequired': 'This language requires sentence case formatting',
    'qc.warning.germanOrthography': 'Please use proper German umlauts (ä,ö,ü) and eszett (ß)',
    'qc.warning.parentalAdvisoryUnnecessary': 'Parental Advisory set but no explicit content found',
    'qc.warning.cleanVersionWithoutExplicit': 'Clean version exists without corresponding explicit version',
    'qc.warning.titleCase': 'Please check title capitalization',
    'qc.warning.versionDuplicate': 'Version information already included in title',
    'qc.warning.featuringFormat': 'Please check featuring format (feat. recommended)',
    'qc.warning.featuringInconsistent': 'Inconsistent featuring notation',
    'qc.warning.copyrightSymbolIncluded': 'Copyright symbols are added automatically, do not include',
    'qc.warning.mixedLanguages': 'Mixed languages across tracks',
    'qc.warning.shortReleaseNotice': 'Less than 2 weeks until release. Review may be delayed',
    'qc.warning.tooManyGenres': 'Too many genres selected (max 3 recommended)',
    
    'qc.info.versionFormat': 'Version info should be in parentheses at end of title',
    
    'qc.suggestion': 'Suggestion',
    'qc.field': 'Field',
    'qc.status.passed': 'QC Passed',
    'qc.status.failed': 'QC Failed',
    'qc.status.warnings': 'Warnings',
    'qc.report.title': 'FUGA QC Check Results',
    'qc.report.subtitle': 'Items that must be fixed before release',
    'qc.report.errors': 'Required Fixes',
    'qc.report.warnings': 'Recommended Fixes',
    'qc.report.info': 'Information',
    'qc.report.noIssues': 'All QC checks passed',
    'qc.report.fixRequired': 'Please fix errors before submission',
    
    // Technical Guide
    'technicalGuide.title': 'Technical Specifications Guide',
    'technicalGuide.description': 'Detailed technical specifications to meet QC requirements',
    'technicalGuide.downloadSpecs': 'Download Technical Specs',
    'technicalGuide.downloadDescription': 'Download complete specifications in PDF format',
    'technicalGuide.downloadPDF': 'Download PDF',
    'technicalGuide.specifications': 'Specifications',
    'technicalGuide.requirements': 'Requirements',
    'technicalGuide.correctExamples': 'Correct Examples',
    'technicalGuide.incorrectExamples': 'Incorrect Examples',
    'technicalGuide.proTips': 'Pro Tips',
    'technicalGuide.audio.title': 'Audio Specifications',
    'technicalGuide.artwork.title': 'Artwork Specifications',
    'technicalGuide.motionArt.title': 'Motion Art Specifications',
    'technicalGuide.dolbyAtmos.title': 'Dolby Atmos Specifications',
    'technicalGuide.video.title': 'Video Specifications',
    'technicalGuide.needHelp': 'Need Help?',
    'technicalGuide.contactSupport': 'Our technical support team is here to help',
    'technicalGuide.contactButton': 'Contact Support',
    'technicalGuide.tips.audio1': 'We recommend 96kHz/24bit or higher for best quality',
    'technicalGuide.tips.audio2': 'Consider targeting -14 LUFS for streaming platforms',
    'technicalGuide.tips.audio3': 'Keep True Peak below -1dB',
    'technicalGuide.tips.artwork1': 'Use RGB color mode and avoid CMYK',
    'technicalGuide.tips.artwork2': 'For artwork with text, use 300DPI or higher',
    'technicalGuide.tips.artwork3': 'Transparent backgrounds are not supported',
    'technicalGuide.tips.motionArt1': 'Match first and last frames for seamless looping',
    'technicalGuide.tips.motionArt2': 'Use appropriate bitrate for file size optimization',
    'technicalGuide.tips.motionArt3': 'Avoid excessive motion or flashing',
    'technicalGuide.tips.dolbyAtmos1': 'Must be mastered in Dolby Atmos Production Suite',
    'technicalGuide.tips.dolbyAtmos2': 'Binaural render must be included',
    'technicalGuide.tips.dolbyAtmos3': 'Final testing on Dolby renderer is required',
    'technicalGuide.tips.video1': 'Use high bitrate for quality encoding',
    'technicalGuide.tips.video2': 'Rec. 709 color space recommended',
    'technicalGuide.tips.video3': 'Audio track must be perfectly synced with video',
    
    // Artist Modal specific translations
    'artist.modal.addMain': 'Add Main Artist',
    'artist.modal.addFeaturing': 'Add Featuring Artist',
    'artist.modal.required': 'Artist name is required',
    'artist.modal.translationLanguageRequired': 'Please select translation language',
    'artist.modal.translatedNameRequired': 'Please enter translated artist name',
    'artist.modal.spotifyIdRequired': 'Spotify Artist ID is required (click New button for new artists)',
    'artist.modal.appleIdRequired': 'Apple Music Artist ID is required (click New button for new artists)',
    'artist.modal.name.placeholder': 'Enter artist name',
    'artist.modal.addTranslation': 'Add translation in another language',
    'artist.modal.selectLanguage': 'Select language',
    'artist.modal.translatedName.placeholder': 'Translated artist name',
    'artist.modal.nationality': 'Nationality',
    'artist.modal.youtubeChannelId': 'YouTube Channel ID',
    'artist.modal.youtubeChannelId.placeholder': 'e.g., UC16niRr50-MSBwiO3YDb3RA',
    'artist.modal.youtubeChannelId.help': 'Enter the part after /channel/ from YouTube channel URL',
    'artist.modal.platformIds': 'Social Media / Streaming Platforms',
    'artist.modal.newArtist': 'New Artist',
    'artist.modal.newArtistInfo': 'Will be registered as a new artist. Artist page will be created.',
    'artist.modal.changeToExisting': 'Change to existing artist',
    'artist.modal.spotifyId': 'Spotify Artist ID',
    'artist.modal.spotifyId.placeholder': 'e.g., 6HQYnRM4OzToCYPpVBInPt',
    'artist.modal.appleId': 'Apple Music Artist ID',
    'artist.modal.appleId.placeholder': 'e.g., 277905876',
    'artist.modal.helpModal.spotify.title': 'How to Find Spotify Artist ID',
    'artist.modal.helpModal.apple.title': 'How to Find Apple Music Artist ID',
    'artist.modal.helpModal.macWindows': 'Mac / Windows (Web Browser)',
    'artist.modal.helpModal.app': 'App',
    'artist.modal.helpModal.spotify.webSteps': '1. Go to Spotify web player (open.spotify.com)\n2. Navigate to artist page\n3. Check URL in browser address bar\n4. URL example: https://open.spotify.com/artist/6HQYnRM4OzToCYPpVBInPt\n5. The highlighted part is the Artist ID',
    'artist.modal.helpModal.spotify.appSteps': '1. Tap ⋯ (more) menu on artist page\n2. Select "Share" → "Copy Link"\n3. The part after artist/ in the copied link is the ID',
    'artist.modal.helpModal.spotify.idFormat': 'Artist ID is a 22-character combination of letters and numbers',
    'artist.modal.helpModal.apple.webSteps': '1. Go to Apple Music web (music.apple.com)\n2. Navigate to artist page\n3. Check URL in browser address bar\n4. URL example: https://music.apple.com/kr/artist/iu/277905876\n5. The highlighted number is the Artist ID',
    'artist.modal.helpModal.apple.appSteps': '1. Tap ⋯ (more) button on artist page\n2. Select "Share" → "Copy Link"\n3. The last number in the copied link is the ID',
    'artist.modal.helpModal.apple.idFormat': 'Artist ID is a 9-10 digit number',
    'artist.modal.helpModal.confirm': 'Confirm',
    'artist.modal.cancel': 'Cancel',
    'artist.modal.save': 'Save',
    'artist.modal.helpModal.spotifyApp': 'Spotify App',
    'artist.modal.helpModal.appleApp': 'Apple Music App',
    'artist.modal.helpModal.spotifyWebStep1': '1. Go to Spotify web player (open.spotify.com)',
    'artist.modal.helpModal.spotifyWebStep2': '2. Navigate to artist page',
    'artist.modal.helpModal.spotifyWebStep3': '3. Check URL in browser address bar',
    'artist.modal.helpModal.spotifyWebStep4': '4. URL example: https://open.spotify.com/artist/',
    'artist.modal.helpModal.spotifyWebStep5': '5. The highlighted part is the Artist ID',
    'artist.modal.helpModal.spotifyAppStep1': '1. Tap ⋯ (more) menu on artist page',
    'artist.modal.helpModal.spotifyAppStep2': '2. Select "Share" → "Copy Link"',
    'artist.modal.helpModal.spotifyAppStep3': '3. The part after artist/ in the copied link is the ID',
    'artist.modal.helpModal.appleWebStep1': '1. Go to Apple Music web (music.apple.com)',
    'artist.modal.helpModal.appleWebStep2': '2. Navigate to artist page',
    'artist.modal.helpModal.appleWebStep3': '3. Check URL in browser address bar',
    'artist.modal.helpModal.appleWebStep4': '4. URL example: https://music.apple.com/kr/artist/iu/',
    'artist.modal.helpModal.appleWebStep5': '5. The highlighted number is the Artist ID',
    'artist.modal.helpModal.appleAppStep1': '1. Tap ⋯ (more) button on artist page',
    'artist.modal.helpModal.appleAppStep2': '2. Select "Share" → "Copy Link"',
    'artist.modal.helpModal.appleAppStep3': '3. The last number in the copied link is the ID',
    
    // UI texts for ReleaseSubmission
    'ui.confirmDelete': 'Are you sure you want to delete the saved content?',
    'ui.dataDeleted': 'Saved content has been deleted',
    'ui.delete': 'Delete',
    'ui.autoSaveEnabled': 'Auto-save enabled',
    'ui.previousContent': 'You have previously saved content',
    'ui.lastSaved': 'Last saved',
    
    // Submission Success page
    'submission.success.reviewNotice': 'Our team will review and contact you within 24 hours.',
    'submission.success.reviewNoticeEn': 'Our team will review and contact you within 24 hours.',
    'submission.success.completedItems': 'Completed Items',
    'submission.success.goToDashboard': 'Go to Dashboard',
    'submission.success.newRelease': 'Register New Release'
  }
}

// 번역 함수
export function t(key: string, replacements?: Record<string, string | number>): string {
  const language = useLanguageStore.getState().language
  let value = translations[language][key as keyof typeof translations['ko']] || key
  
  // Handle template replacements
  if (replacements) {
    Object.entries(replacements).forEach(([placeholder, replacement]) => {
      value = value.replace(new RegExp(`{{${placeholder}}}`, 'g'), String(replacement))
    })
  }
  
  return value
}

// Hook for translations (for compatibility)
export function useTranslation() {
  const language = useLanguageStore(state => state.language)
  
  return {
    t: (key: string, replacements?: Record<string, string | number>) => {
      let value = translations[language][key as keyof typeof translations['ko']] || key
      
      if (replacements) {
        Object.entries(replacements).forEach(([placeholder, replacement]) => {
          value = value.replace(new RegExp(`{{${placeholder}}}`, 'g'), String(replacement))
        })
      }
      
      return value
    },
    language
  }
}