// Genre list for FUGA platform
export const genreList = [
  'Pop',
  'Rock',
  'Hip Hop',
  'R&B/Soul',
  'Electronic',
  'Dance',
  'Country',
  'Latin',
  'Alternative',
  'Jazz',
  'Classical',
  'Blues',
  'Reggae',
  'Metal',
  'Folk',
  'World',
  'Gospel',
  'Vocal',
  'Easy Listening',
  'J-Pop',
  'K-Pop',
  'Anime',
  'Soundtrack',
  'Children\'s Music',
  'Holiday',
  'Comedy',
  'Spoken Word',
  'Audiobook',
  'Podcast'
]

// Subgenre list
export const subgenreList = [
  // Pop Subgenres
  'Adult Contemporary',
  'Britpop',
  'Bubblegum Pop',
  'Chamber Pop',
  'Dance Pop',
  'Dream Pop',
  'Electro Pop',
  'Indie Pop',
  'K-Pop',
  'New Wave',
  'Pop Punk',
  'Pop Rock',
  'Power Pop',
  'Soft Rock',
  'Synthpop',
  'Teen Pop',
  
  // Rock Subgenres
  'Alternative Rock',
  'Blues Rock',
  'Classic Rock',
  'Garage Rock',
  'Glam Rock',
  'Hard Rock',
  'Indie Rock',
  'Progressive Rock',
  'Psychedelic Rock',
  'Punk Rock',
  'Southern Rock',
  'Surf Rock',
  
  // Hip Hop Subgenres
  'Boom Bap',
  'Conscious Hip Hop',
  'Gangsta Rap',
  'Hardcore Hip Hop',
  'Hip Hop Soul',
  'Instrumental Hip Hop',
  'Jazz Rap',
  'Trap',
  'Underground Hip Hop',
  
  // Electronic Subgenres
  'Ambient',
  'Big Beat',
  'Breakbeat',
  'Chillout',
  'Downtempo',
  'Drum & Bass',
  'Dubstep',
  'EDM',
  'Electronica',
  'Garage',
  'Hardcore',
  'House',
  'IDM',
  'Jungle',
  'Techno',
  'Trance',
  'Trip Hop',
  
  // R&B/Soul Subgenres
  'Contemporary R&B',
  'Deep Soul',
  'Funk',
  'Motown',
  'Neo Soul',
  'Northern Soul',
  'Quiet Storm',
  'Soul',
  'Southern Soul',
  
  // Jazz Subgenres
  'Acid Jazz',
  'Avant-Garde Jazz',
  'Bebop',
  'Big Band',
  'Cool Jazz',
  'Free Jazz',
  'Fusion',
  'Hard Bop',
  'Latin Jazz',
  'Smooth Jazz',
  'Swing',
  'Vocal Jazz',
  
  // Classical Subgenres
  'Baroque',
  'Chamber Music',
  'Choral',
  'Classical Crossover',
  'Contemporary Classical',
  'Impressionist',
  'Medieval',
  'Minimalism',
  'Modern Classical',
  'Opera',
  'Orchestral',
  'Renaissance',
  'Romantic',
  
  // World Music Subgenres
  'Afrobeat',
  'Celtic',
  'Flamenco',
  'Indian Classical',
  'Middle Eastern',
  'Polka',
  'Samba',
  'Tango',
  'Traditional',
  'Worldbeat',
  
  // Other Subgenres
  'Acid House',
  'Bluegrass',
  'Cajun',
  'Disco',
  'Doo Wop',
  'Gospel',
  'Grunge',
  'Lo-Fi',
  'New Age',
  'Reggaeton',
  'Ska',
  'Zydeco'
]

// Genre categories for better organization
export const genreCategories = {
  'Popular': ['Pop', 'Rock', 'Hip Hop', 'R&B/Soul', 'Electronic', 'Dance', 'K-Pop'],
  'Traditional': ['Jazz', 'Classical', 'Blues', 'Folk', 'Gospel', 'World'],
  'Regional': ['Latin', 'Country', 'Reggae', 'J-Pop', 'K-Pop'],
  'Specialty': ['Soundtrack', 'Children\'s Music', 'Holiday', 'Comedy', 'Spoken Word', 'Audiobook', 'Podcast'],
  'Heavy': ['Metal', 'Alternative']
}