// Genre list for FUGA platform with labels
export const genreList = [
  { value: 'Pop', label: 'Pop' },
  { value: 'Rock', label: 'Rock' },
  { value: 'Hip Hop', label: 'Hip Hop' },
  { value: 'R&B/Soul', label: 'R&B/Soul' },
  { value: 'Electronic', label: 'Electronic' },
  { value: 'Dance', label: 'Dance' },
  { value: 'Country', label: 'Country' },
  { value: 'Latin', label: 'Latin' },
  { value: 'Alternative', label: 'Alternative' },
  { value: 'Jazz', label: 'Jazz' },
  { value: 'Classical', label: 'Classical' },
  { value: 'Blues', label: 'Blues' },
  { value: 'Reggae', label: 'Reggae' },
  { value: 'Metal', label: 'Metal' },
  { value: 'Folk', label: 'Folk' },
  { value: 'World', label: 'World' },
  { value: 'Gospel', label: 'Gospel' },
  { value: 'Vocal', label: 'Vocal' },
  { value: 'Easy Listening', label: 'Easy Listening' },
  { value: 'J-Pop', label: 'J-Pop' },
  { value: 'K-Pop', label: 'K-Pop' },
  { value: 'Anime', label: 'Anime' },
  { value: 'Soundtrack', label: 'Soundtrack' },
  { value: 'Children\'s Music', label: 'Children\'s Music' },
  { value: 'Holiday', label: 'Holiday' },
  { value: 'Comedy', label: 'Comedy' },
  { value: 'Spoken Word', label: 'Spoken Word' },
  { value: 'Audiobook', label: 'Audiobook' },
  { value: 'Podcast', label: 'Podcast' }
]

// Subgenre list by genre
export const subgenreList: Record<string, { value: string; label: string }[]> = {
  'Pop': [
    { value: 'Adult Contemporary', label: 'Adult Contemporary' },
    { value: 'Britpop', label: 'Britpop' },
    { value: 'Bubblegum Pop', label: 'Bubblegum Pop' },
    { value: 'Chamber Pop', label: 'Chamber Pop' },
    { value: 'Dance Pop', label: 'Dance Pop' },
    { value: 'Dream Pop', label: 'Dream Pop' },
    { value: 'Electro Pop', label: 'Electro Pop' },
    { value: 'Indie Pop', label: 'Indie Pop' },
    { value: 'New Wave', label: 'New Wave' },
    { value: 'Pop Punk', label: 'Pop Punk' },
    { value: 'Pop Rock', label: 'Pop Rock' },
    { value: 'Power Pop', label: 'Power Pop' },
    { value: 'Soft Rock', label: 'Soft Rock' },
    { value: 'Synth Pop', label: 'Synth Pop' },
    { value: 'Teen Pop', label: 'Teen Pop' }
  ],
  'Rock': [
    { value: 'Alternative Rock', label: 'Alternative Rock' },
    { value: 'Arena Rock', label: 'Arena Rock' },
    { value: 'Blues Rock', label: 'Blues Rock' },
    { value: 'Classic Rock', label: 'Classic Rock' },
    { value: 'Folk Rock', label: 'Folk Rock' },
    { value: 'Garage Rock', label: 'Garage Rock' },
    { value: 'Glam Rock', label: 'Glam Rock' },
    { value: 'Grunge', label: 'Grunge' },
    { value: 'Hard Rock', label: 'Hard Rock' },
    { value: 'Indie Rock', label: 'Indie Rock' },
    { value: 'Progressive Rock', label: 'Progressive Rock' },
    { value: 'Psychedelic Rock', label: 'Psychedelic Rock' },
    { value: 'Punk Rock', label: 'Punk Rock' },
    { value: 'Southern Rock', label: 'Southern Rock' },
    { value: 'Surf Rock', label: 'Surf Rock' }
  ],
  'Hip Hop': [
    { value: 'Alternative Hip Hop', label: 'Alternative Hip Hop' },
    { value: 'Boom Bap', label: 'Boom Bap' },
    { value: 'Bounce', label: 'Bounce' },
    { value: 'Conscious Hip Hop', label: 'Conscious Hip Hop' },
    { value: 'Crunk', label: 'Crunk' },
    { value: 'Dirty South', label: 'Dirty South' },
    { value: 'East Coast Hip Hop', label: 'East Coast Hip Hop' },
    { value: 'Gangsta Rap', label: 'Gangsta Rap' },
    { value: 'Hardcore Hip Hop', label: 'Hardcore Hip Hop' },
    { value: 'Hip Hop Soul', label: 'Hip Hop Soul' },
    { value: 'Mumble Rap', label: 'Mumble Rap' },
    { value: 'Trap', label: 'Trap' },
    { value: 'Underground Hip Hop', label: 'Underground Hip Hop' },
    { value: 'West Coast Hip Hop', label: 'West Coast Hip Hop' }
  ],
  'R&B/Soul': [
    { value: 'Contemporary R&B', label: 'Contemporary R&B' },
    { value: 'Deep Soul', label: 'Deep Soul' },
    { value: 'Funk', label: 'Funk' },
    { value: 'Motown', label: 'Motown' },
    { value: 'Neo Soul', label: 'Neo Soul' },
    { value: 'Northern Soul', label: 'Northern Soul' },
    { value: 'Quiet Storm', label: 'Quiet Storm' },
    { value: 'Soul', label: 'Soul' },
    { value: 'Southern Soul', label: 'Southern Soul' },
    { value: 'Urban Contemporary', label: 'Urban Contemporary' }
  ],
  'Electronic': [
    { value: 'Ambient', label: 'Ambient' },
    { value: 'Breakbeat', label: 'Breakbeat' },
    { value: 'Chillout', label: 'Chillout' },
    { value: 'Downtempo', label: 'Downtempo' },
    { value: 'Drum and Bass', label: 'Drum and Bass' },
    { value: 'Dubstep', label: 'Dubstep' },
    { value: 'EDM', label: 'EDM' },
    { value: 'Electro', label: 'Electro' },
    { value: 'Future Bass', label: 'Future Bass' },
    { value: 'Garage', label: 'Garage' },
    { value: 'Hardstyle', label: 'Hardstyle' },
    { value: 'House', label: 'House' },
    { value: 'IDM', label: 'IDM' },
    { value: 'Techno', label: 'Techno' },
    { value: 'Trance', label: 'Trance' }
  ],
  'Dance': [
    { value: 'Club', label: 'Club' },
    { value: 'Deep House', label: 'Deep House' },
    { value: 'Disco', label: 'Disco' },
    { value: 'Eurodance', label: 'Eurodance' },
    { value: 'Freestyle', label: 'Freestyle' },
    { value: 'Future House', label: 'Future House' },
    { value: 'Garage House', label: 'Garage House' },
    { value: 'Hi-NRG', label: 'Hi-NRG' },
    { value: 'House', label: 'House' },
    { value: 'Progressive House', label: 'Progressive House' },
    { value: 'Tech House', label: 'Tech House' },
    { value: 'Tribal House', label: 'Tribal House' },
    { value: 'UK Garage', label: 'UK Garage' }
  ],
  'Country': [
    { value: 'Alt-Country', label: 'Alt-Country' },
    { value: 'Americana', label: 'Americana' },
    { value: 'Bluegrass', label: 'Bluegrass' },
    { value: 'Country Blues', label: 'Country Blues' },
    { value: 'Country Folk', label: 'Country Folk' },
    { value: 'Country Pop', label: 'Country Pop' },
    { value: 'Country Rock', label: 'Country Rock' },
    { value: 'Honky Tonk', label: 'Honky Tonk' },
    { value: 'Nashville Sound', label: 'Nashville Sound' },
    { value: 'Outlaw Country', label: 'Outlaw Country' },
    { value: 'Traditional Country', label: 'Traditional Country' },
    { value: 'Western Swing', label: 'Western Swing' }
  ],
  'Latin': [
    { value: 'Bachata', label: 'Bachata' },
    { value: 'Banda', label: 'Banda' },
    { value: 'Bossa Nova', label: 'Bossa Nova' },
    { value: 'Cumbia', label: 'Cumbia' },
    { value: 'Flamenco', label: 'Flamenco' },
    { value: 'Latin Jazz', label: 'Latin Jazz' },
    { value: 'Latin Pop', label: 'Latin Pop' },
    { value: 'Mariachi', label: 'Mariachi' },
    { value: 'Merengue', label: 'Merengue' },
    { value: 'Ranchera', label: 'Ranchera' },
    { value: 'Reggaeton', label: 'Reggaeton' },
    { value: 'Salsa', label: 'Salsa' },
    { value: 'Samba', label: 'Samba' },
    { value: 'Tango', label: 'Tango' },
    { value: 'Tejano', label: 'Tejano' }
  ],
  'K-Pop': [
    { value: 'K-Pop Ballad', label: 'K-Pop Ballad' },
    { value: 'K-Pop Dance', label: 'K-Pop Dance' },
    { value: 'K-Pop Hip Hop', label: 'K-Pop Hip Hop' },
    { value: 'K-Pop R&B', label: 'K-Pop R&B' },
    { value: 'K-Pop Rock', label: 'K-Pop Rock' },
    { value: 'K-Indie', label: 'K-Indie' },
    { value: 'Trot', label: 'Trot' }
  ],
  'J-Pop': [
    { value: 'J-Rock', label: 'J-Rock' },
    { value: 'Visual Kei', label: 'Visual Kei' },
    { value: 'Shibuya-kei', label: 'Shibuya-kei' },
    { value: 'City Pop', label: 'City Pop' },
    { value: 'Idol Pop', label: 'Idol Pop' },
    { value: 'Denpa', label: 'Denpa' },
    { value: 'Enka', label: 'Enka' }
  ]
}