export interface Instrument {
  value: string
  label: string
  labelEn: string
  category: string
}

export const instrumentList: Instrument[] = [
  // String Instruments
  { value: 'string-bass-guitar', label: '스트링 베이스 기타', labelEn: 'String Bass Guitar', category: '현악기' },
  { value: 'string-guitar', label: '스트링 기타', labelEn: 'String Guitar', category: '현악기' },
  { value: 'string-acoustic-guitar', label: '스트링 어쿠스틱 기타', labelEn: 'String Acoustic Guitar', category: '현악기' },
  { value: 'string-electric-guitar', label: '스트링 일렉트릭 기타', labelEn: 'String Electric Guitar', category: '현악기' },
  { value: 'string-fiddle', label: '스트링 피들', labelEn: 'String Fiddle', category: '현악기' },
  { value: 'string-banjo', label: '스트링 밴조', labelEn: 'String Banjo', category: '현악기' },
  { value: 'acoustic-baritone-guitar', label: '어쿠스틱 바리톤 기타', labelEn: 'Acoustic Baritone Guitar', category: '현악기' },
  { value: 'acoustic-bass-guitar', label: '어쿠스틱 베이스 기타', labelEn: 'Acoustic Bass Guitar', category: '현악기' },
  { value: 'acoustic-fretless-guitar', label: '어쿠스틱 프렛리스 기타', labelEn: 'Acoustic Fretless Guitar', category: '현악기' },
  { value: 'acoustic-guitar', label: '어쿠스틱 기타', labelEn: 'Acoustic Guitar', category: '현악기' },
  { value: 'appalachian-dulcimer', label: '애팔래치안 덜시머', labelEn: 'Appalachian Dulcimer', category: '현악기' },
  { value: 'archlute', label: '아치류트', labelEn: 'Archlute', category: '현악기' },
  { value: 'autoharp', label: '오토하프', labelEn: 'Autoharp', category: '현악기' },
  { value: 'balalaika', label: '발랄라이카', labelEn: 'Balalaika', category: '현악기' },
  { value: 'bandurria', label: '반두리아', labelEn: 'Bandurria', category: '현악기' },
  { value: 'banjo', label: '밴조', labelEn: 'Banjo', category: '현악기' },
  { value: 'barbat', label: '바르밧', labelEn: 'Barbat', category: '현악기' },
  { value: 'baritone-guitar', label: '바리톤 기타', labelEn: 'Baritone Guitar', category: '현악기' },
  { value: 'baroque-guitar', label: '바로크 기타', labelEn: 'Baroque Guitar', category: '현악기' },
  { value: 'baroque-violin', label: '바로크 바이올린', labelEn: 'Baroque Violin', category: '현악기' },
  { value: 'bass', label: '베이스', labelEn: 'Bass', category: '현악기' },
  { value: 'bass-guitar', label: '베이스 기타', labelEn: 'Bass Guitar', category: '현악기' },
  { value: 'biwa', label: '비와', labelEn: 'Biwa', category: '현악기' },
  { value: 'bouzouki', label: '부주키', labelEn: 'Bouzouki', category: '현악기' },
  { value: 'cavaquinho', label: '카바킨요', labelEn: 'Cavaquinho', category: '현악기' },
  { value: 'cello', label: '첼로', labelEn: 'Cello', category: '현악기' },
  { value: 'chapman-stick', label: '채프먼 스틱', labelEn: 'Chapman Stick', category: '현악기' },
  { value: 'charango', label: '차랑고', labelEn: 'Charango', category: '현악기' },
  { value: 'cimbalom', label: '침발롬', labelEn: 'Cimbalom', category: '현악기' },
  { value: 'cittern', label: '시턴', labelEn: 'Cittern', category: '현악기' },
  { value: 'classical-guitar', label: '클래식 기타', labelEn: 'Classical Guitar', category: '현악기' },
  { value: 'contrabass', label: '콘트라베이스', labelEn: 'Contrabass', category: '현악기' },
  { value: 'cuatro', label: '쿠아트로', labelEn: 'Cuatro', category: '현악기' },
  { value: 'diddley-bow', label: '디들리 보우', labelEn: 'Diddley Bow', category: '현악기' },
  { value: 'dobro-guitar', label: '도브로 기타', labelEn: 'Dobro Guitar', category: '현악기' },
  { value: 'double-bass', label: '더블 베이스', labelEn: 'Double Bass', category: '현악기' },
  { value: 'dulcimer', label: '덜시머', labelEn: 'Dulcimer', category: '현악기' },
  { value: 'e-bow', label: '이보우', labelEn: 'E-Bow', category: '현악기' },
  { value: 'electric-bass-guitar', label: '일렉트릭 베이스 기타', labelEn: 'Electric Bass Guitar', category: '현악기' },
  { value: 'electric-cello', label: '일렉트릭 첼로', labelEn: 'Electric Cello', category: '현악기' },
  { value: 'electric-fretless-guitar', label: '일렉트릭 프렛리스 기타', labelEn: 'Electric Fretless Guitar', category: '현악기' },
  { value: 'electric-guitar', label: '일렉트릭 기타', labelEn: 'Electric Guitar', category: '현악기' },
  { value: 'electric-sitar', label: '일렉트릭 시타르', labelEn: 'Electric Sitar', category: '현악기' },
  { value: 'electric-upright-bass', label: '일렉트릭 업라이트 베이스', labelEn: 'Electric Upright Bass', category: '현악기' },
  { value: 'electric-viola', label: '일렉트릭 비올라', labelEn: 'Electric Viola', category: '현악기' },
  { value: 'electric-violin', label: '일렉트릭 바이올린', labelEn: 'Electric Violin', category: '현악기' },
  { value: 'fiddle', label: '피들', labelEn: 'Fiddle', category: '현악기' },
  { value: 'flamenco-guitar', label: '플라멩코 기타', labelEn: 'Flamenco Guitar', category: '현악기' },
  { value: 'gitern', label: '기턴', labelEn: 'Gitern', category: '현악기' },
  { value: 'gut-string-guitar', label: '거트 스트링 기타', labelEn: 'Gut-String-Guitar', category: '현악기' },
  { value: 'hardingfele', label: '하르딩펠레', labelEn: 'Hardingfele', category: '현악기' },
  { value: 'harp', label: '하프', labelEn: 'Harp', category: '현악기' },
  { value: 'kora', label: '코라', labelEn: 'Kora', category: '현악기' },
  { value: 'koto', label: '고토', labelEn: 'Koto', category: '현악기' },
  { value: 'lap-steel-guitar', label: '랩 스틸 기타', labelEn: 'Lap Steel Guitar', category: '현악기' },
  { value: 'lute', label: '류트', labelEn: 'Lute', category: '현악기' },
  { value: 'mandocello', label: '만도첼로', labelEn: 'Mandocello', category: '현악기' },
  { value: 'mandola', label: '만돌라', labelEn: 'Mandola', category: '현악기' },
  { value: 'mandolin', label: '만돌린', labelEn: 'Mandolin', category: '현악기' },
  { value: 'nylon-string-guitar', label: '나일론 스트링 기타', labelEn: 'Nylon-String-Guitar', category: '현악기' },
  { value: 'oud', label: '우드', labelEn: 'Oud', category: '현악기' },
  { value: 'parlour-guitar', label: '팔러 기타', labelEn: 'Parlour Guitar', category: '현악기' },
  { value: 'pedal-steel-guitar', label: '페달 스틸 기타', labelEn: 'Pedal Steel Guitar', category: '현악기' },
  { value: 'pikasa-guitar', label: '피카사 기타', labelEn: 'Pikasa Guitar', category: '현악기' },
  { value: 'portuguese-guitar', label: '포르투갈 기타', labelEn: 'Portuguese Guitar', category: '현악기' },
  { value: 'psaltery', label: '솔터리', labelEn: 'Psaltery', category: '현악기' },
  { value: 'rebab', label: '레밥', labelEn: 'Rebab', category: '현악기' },
  { value: 'rebec', label: '레벡', labelEn: 'Rebec', category: '현악기' },
  { value: 'requinto-guitar', label: '레킨토 기타', labelEn: 'Requinto Guitar', category: '현악기' },
  { value: 'rhythm-guitar', label: '리듬 기타', labelEn: 'Rhythm Guitar', category: '현악기' },
  { value: 'santoor', label: '산투르', labelEn: 'Santoor', category: '현악기' },
  { value: 'santur', label: '산투르', labelEn: 'Santur', category: '현악기' },
  { value: 'sarangi', label: '사랑기', labelEn: 'Sarangi', category: '현악기' },
  { value: 'sarod', label: '사로드', labelEn: 'Sarod', category: '현악기' },
  { value: 'saz', label: '사즈', labelEn: 'Saz', category: '현악기' },
  { value: 'shamisen', label: '샤미센', labelEn: 'Shamisen', category: '현악기' },
  { value: 'sitar', label: '시타르', labelEn: 'Sitar', category: '현악기' },
  { value: 'slide-guitar', label: '슬라이드 기타', labelEn: 'Slide Guitar', category: '현악기' },
  { value: 'spanish-guitar', label: '스패니시 기타', labelEn: 'Spanish Guitar', category: '현악기' },
  { value: 'strings', label: '스트링스', labelEn: 'Strings', category: '현악기' },
  { value: 'tamboura', label: '탐부라', labelEn: 'Tamboura', category: '현악기' },
  { value: 'tanpura', label: '탄푸라', labelEn: 'Tanpura', category: '현악기' },
  { value: 'tenor-banjo', label: '테너 밴조', labelEn: 'Tenor Banjo', category: '현악기' },
  { value: 'tenor-guitar', label: '테너 기타', labelEn: 'Tenor Guitar', category: '현악기' },
  { value: 'theorbo', label: '테오르보', labelEn: 'Theorbo', category: '현악기' },
  { value: 'tres', label: '트레스', labelEn: 'Tres', category: '현악기' },
  { value: 'ukulele', label: '우쿨렐레', labelEn: 'Ukulele', category: '현악기' },
  { value: 'vielle', label: '비엘', labelEn: 'Vielle', category: '현악기' },
  { value: 'viol', label: '비올', labelEn: 'Viol', category: '현악기' },
  { value: 'viola', label: '비올라', labelEn: 'Viola', category: '현악기' },
  { value: 'viola-damore', label: '비올라 다모레', labelEn: "Viola D'Amore", category: '현악기' },
  { value: 'viola-da-gamba', label: '비올라 다 감바', labelEn: 'Viola Da Gamba', category: '현악기' },
  { value: 'violin', label: '바이올린', labelEn: 'Violin', category: '현악기' },
  { value: 'violoncello', label: '비올론첼로', labelEn: 'Violoncello', category: '현악기' },
  { value: 'violone', label: '비올로네', labelEn: 'Violone', category: '현악기' },
  { value: 'zither', label: '치터', labelEn: 'Zither', category: '현악기' },
  { value: 'alto-violin', label: '알토 바이올린', labelEn: 'Alto Violin', category: '현악기' },
  { value: 'soprano-violin', label: '소프라노 바이올린', labelEn: 'Soprano Violin', category: '현악기' },
  { value: 'tenor-violin', label: '테너 바이올린', labelEn: 'Tenor Violin', category: '현악기' },
  { value: 'concert-harp', label: '콘서트 하프', labelEn: 'Concert Harp', category: '현악기' },
  { value: 'hammered-dulcimer', label: '해머드 덜시머', labelEn: 'Hammered Dulcimer', category: '현악기' },

  // Keyboard Instruments
  { value: 'accordion', label: '아코디언', labelEn: 'Accordion', category: '건반악기' },
  { value: 'barrel-organ', label: '배럴 오르간', labelEn: 'Barrel Organ', category: '건반악기' },
  { value: 'button-accordion', label: '버튼 아코디언', labelEn: 'Button Accordion', category: '건반악기' },
  { value: 'celeste', label: '첼레스타', labelEn: 'Celeste', category: '건반악기' },
  { value: 'chamber-organ', label: '챔버 오르간', labelEn: 'Chamber Organ', category: '건반악기' },
  { value: 'chamberlin', label: '챔벌린', labelEn: 'Chamberlin', category: '건반악기' },
  { value: 'chest-organ', label: '체스트 오르간', labelEn: 'Chest Organ', category: '건반악기' },
  { value: 'clavichord', label: '클라비코드', labelEn: 'Clavichord', category: '건반악기' },
  { value: 'clavinet', label: '클라비넷', labelEn: 'Clavinet', category: '건반악기' },
  { value: 'concertina', label: '콘서티나', labelEn: 'Concertina', category: '건반악기' },
  { value: 'electric-piano', label: '일렉트릭 피아노', labelEn: 'Electric Piano', category: '건반악기' },
  { value: 'farfisa', label: '파르피사', labelEn: 'Farfisa', category: '건반악기' },
  { value: 'fender-rhodes', label: '펜더 로즈', labelEn: 'Fender Rhodes', category: '건반악기' },
  { value: 'fortepiano', label: '포르테피아노', labelEn: 'Fortepiano', category: '건반악기' },
  { value: 'hammond-organ', label: '해먼드 오르간', labelEn: 'Hammond Organ', category: '건반악기' },
  { value: 'harmonium', label: '하모늄', labelEn: 'Harmonium', category: '건반악기' },
  { value: 'harpsichord', label: '하프시코드', labelEn: 'Harpsichord', category: '건반악기' },
  { value: 'keyboard-bass', label: '키보드 베이스', labelEn: 'Keyboard Bass', category: '건반악기' },
  { value: 'keyboards', label: '키보드', labelEn: 'Keyboards', category: '건반악기' },
  { value: 'keytar', label: '키타', labelEn: 'Keytar', category: '건반악기' },
  { value: 'mellophone', label: '멜로폰', labelEn: 'Mellophone', category: '건반악기' },
  { value: 'omnichord', label: '옴니코드', labelEn: 'Omnichord', category: '건반악기' },
  { value: 'ondes-martenot', label: '옹드 마르트노', labelEn: 'Ondes Martenot', category: '건반악기' },
  { value: 'organ', label: '오르간', labelEn: 'Organ', category: '건반악기' },
  { value: 'piano', label: '피아노', labelEn: 'Piano', category: '건반악기' },
  { value: 'pipe-organ', label: '파이프 오르간', labelEn: 'Pipe Organ', category: '건반악기' },
  { value: 'prepared-piano', label: '프리페어드 피아노', labelEn: 'Prepared Piano', category: '건반악기' },
  { value: 'reed-organ', label: '리드 오르간', labelEn: 'Reed Organ', category: '건반악기' },
  { value: 'rhodes-piano', label: '로즈 피아노', labelEn: 'Rhodes Piano', category: '건반악기' },
  { value: 'spinet', label: '스피넷', labelEn: 'Spinet', category: '건반악기' },
  { value: 'synclavier', label: '신클라비어', labelEn: 'Synclavier', category: '건반악기' },
  { value: 'synthesizer', label: '신시사이저', labelEn: 'Synthesizer', category: '건반악기' },
  { value: 'tack-piano', label: '택 피아노', labelEn: 'Tack Piano', category: '건반악기' },
  { value: 'toy-piano', label: '토이 피아노', labelEn: 'Toy Piano', category: '건반악기' },
  { value: 'upright-piano', label: '업라이트 피아노', labelEn: 'Upright Piano', category: '건반악기' },
  { value: 'wurlitzer', label: '월리처', labelEn: 'Wurlitzer', category: '건반악기' },

  // Wind Instruments
  { value: 'alto-clarinet', label: '알토 클라리넷', labelEn: 'Alto Clarinet', category: '관악기' },
  { value: 'alto-flute', label: '알토 플루트', labelEn: 'Alto Flute', category: '관악기' },
  { value: 'alto-horn', label: '알토 호른', labelEn: 'Alto Horn', category: '관악기' },
  { value: 'alto-recorder', label: '알토 리코더', labelEn: 'Alto Recorder', category: '관악기' },
  { value: 'alto-saxophone', label: '알토 색소폰', labelEn: 'Alto Saxophone', category: '관악기' },
  { value: 'alto-trombone', label: '알토 트롬본', labelEn: 'Alto Trombone', category: '관악기' },
  { value: 'bagpipes', label: '백파이프', labelEn: 'Bagpipes', category: '관악기' },
  { value: 'bansuri', label: '반수리', labelEn: 'Bansuri', category: '관악기' },
  { value: 'baritone-horn', label: '바리톤 호른', labelEn: 'Baritone Horn', category: '관악기' },
  { value: 'bass-clarinet', label: '베이스 클라리넷', labelEn: 'Bass Clarinet', category: '관악기' },
  { value: 'bass-flute', label: '베이스 플루트', labelEn: 'Bass Flute', category: '관악기' },
  { value: 'bass-harmonica', label: '베이스 하모니카', labelEn: 'Bass Harmonica', category: '관악기' },
  { value: 'bass-oboe', label: '베이스 오보에', labelEn: 'Bass Oboe', category: '관악기' },
  { value: 'bass-recorder', label: '베이스 리코더', labelEn: 'Bass Recorder', category: '관악기' },
  { value: 'bass-saxophone', label: '베이스 색소폰', labelEn: 'Bass Saxophone', category: '관악기' },
  { value: 'bass-trombone', label: '베이스 트롬본', labelEn: 'Bass Trombone', category: '관악기' },
  { value: 'bass-trumpet', label: '베이스 트럼펫', labelEn: 'Bass Trumpet', category: '관악기' },
  { value: 'basset-clarinet', label: '바셋 클라리넷', labelEn: 'Basset Clarinet', category: '관악기' },
  { value: 'basset-horn', label: '바셋 호른', labelEn: 'Basset Horn', category: '관악기' },
  { value: 'bassoon', label: '바순', labelEn: 'Bassoon', category: '관악기' },
  { value: 'bugle', label: '뷰글', labelEn: 'Bugle', category: '관악기' },
  { value: 'c-melody-sax', label: 'C 멜로디 색소폰', labelEn: 'C-Melody Sax', category: '관악기' },
  { value: 'calliope', label: '칼리오페', labelEn: 'Calliope', category: '관악기' },
  { value: 'chromatic-harmonica', label: '크로매틱 하모니카', labelEn: 'Chromatic Harmonica', category: '관악기' },
  { value: 'clarinet', label: '클라리넷', labelEn: 'Clarinet', category: '관악기' },
  { value: 'contrabass-clarinet', label: '콘트라베이스 클라리넷', labelEn: 'Contrabass Clarinet', category: '관악기' },
  { value: 'contrabass-flute', label: '콘트라베이스 플루트', labelEn: 'Contrabass Flute', category: '관악기' },
  { value: 'contrabass-recorder', label: '콘트라베이스 리코더', labelEn: 'Contrabass Recorder', category: '관악기' },
  { value: 'contrabass-sarrusophone', label: '콘트라베이스 사루소폰', labelEn: 'Contrabass Sarrusophone', category: '관악기' },
  { value: 'contrabass-saxophone', label: '콘트라베이스 색소폰', labelEn: 'Contrabass Saxophone', category: '관악기' },
  { value: 'contrabass-trombone', label: '콘트라베이스 트롬본', labelEn: 'Contrabass Trombone', category: '관악기' },
  { value: 'contrabassoon', label: '콘트라바순', labelEn: 'Contrabassoon', category: '관악기' },
  { value: 'contralto-clarinet', label: '콘트랄토 클라리넷', labelEn: 'Contralto Clarinet', category: '관악기' },
  { value: 'cornet', label: '코넷', labelEn: 'Cornet', category: '관악기' },
  { value: 'cornett', label: '코르넷', labelEn: 'Cornett', category: '관악기' },
  { value: 'crumhorn', label: '크럼호른', labelEn: 'Crumhorn', category: '관악기' },
  { value: 'curtal', label: '커탈', labelEn: 'Curtal', category: '관악기' },
  { value: 'didgeridoo', label: '디저리두', labelEn: 'Didgeridoo', category: '관악기' },
  { value: 'duduk', label: '두둑', labelEn: 'Duduk', category: '관악기' },
  { value: 'dulcian', label: '둘시안', labelEn: 'Dulcian', category: '관악기' },
  { value: 'english-horn', label: '잉글리시 호른', labelEn: 'English Horn', category: '관악기' },
  { value: 'euphonium', label: '유포늄', labelEn: 'Euphonium', category: '관악기' },
  { value: 'fife', label: '파이프', labelEn: 'Fife', category: '관악기' },
  { value: 'flugelhorn', label: '플뤼겔호른', labelEn: 'Flugelhorn', category: '관악기' },
  { value: 'flute', label: '플루트', labelEn: 'Flute', category: '관악기' },
  { value: 'french-horn', label: '프렌치 호른', labelEn: 'French Horn', category: '관악기' },
  { value: 'harmonica', label: '하모니카', labelEn: 'Harmonica', category: '관악기' },
  { value: 'horn', label: '호른', labelEn: 'Horn', category: '관악기' },
  { value: 'horn-section', label: '호른 섹션', labelEn: 'Horn Section', category: '관악기' },
  { value: 'horns', label: '호른즈', labelEn: 'Horns', category: '관악기' },
  { value: 'kazoo', label: '카주', labelEn: 'Kazoo', category: '관악기' },
  { value: 'low-whistle', label: '로우 휘슬', labelEn: 'Low Whistle', category: '관악기' },
  { value: 'lyricon', label: '리리콘', labelEn: 'Lyricon', category: '관악기' },
  { value: 'manzello', label: '만젤로', labelEn: 'Manzello', category: '관악기' },
  { value: 'mouth-organ', label: '마우스 오르간', labelEn: 'Mouth Organ', category: '관악기' },
  { value: 'musette', label: '뮤제트', labelEn: 'Musette', category: '관악기' },
  { value: 'ney', label: '네이', labelEn: 'Ney', category: '관악기' },
  { value: 'oboe-damore', label: '오보에 다모레', labelEn: "Oboe D'Amore", category: '관악기' },
  { value: 'ocarina', label: '오카리나', labelEn: 'Ocarina', category: '관악기' },
  { value: 'pan-flute', label: '팬플루트', labelEn: 'Pan Flute', category: '관악기' },
  { value: 'panpipes', label: '팬파이프', labelEn: 'Panpipes', category: '관악기' },
  { value: 'penny-whistle', label: '페니 휘슬', labelEn: 'Penny Whistle', category: '관악기' },
  { value: 'piccolo', label: '피콜로', labelEn: 'Piccolo', category: '관악기' },
  { value: 'piccolo-bass', label: '피콜로 베이스', labelEn: 'Piccolo Bass', category: '관악기' },
  { value: 'piccolo-oboe', label: '피콜로 오보에', labelEn: 'Piccolo Oboe', category: '관악기' },
  { value: 'piccolo-trumpet', label: '피콜로 트럼펫', labelEn: 'Piccolo Trumpet', category: '관악기' },
  { value: 'recorder', label: '리코더', labelEn: 'Recorder', category: '관악기' },
  { value: 'sackbut', label: '색버트', labelEn: 'Sackbut', category: '관악기' },
  { value: 'sarrusophone', label: '사루소폰', labelEn: 'Sarrusophone', category: '관악기' },
  { value: 'saxello', label: '색셀로', labelEn: 'Saxello', category: '관악기' },
  { value: 'saxophone', label: '색소폰', labelEn: 'Saxophone', category: '관악기' },
  { value: 'serpent', label: '서펜트', labelEn: 'Serpent', category: '관악기' },
  { value: 'shakuhachi', label: '샤쿠하치', labelEn: 'Shakuhachi', category: '관악기' },
  { value: 'shawm', label: '숌', labelEn: 'Shawm', category: '관악기' },
  { value: 'shenai', label: '셰나이', labelEn: 'Shenai', category: '관악기' },
  { value: 'sheng', label: '생', labelEn: 'Sheng', category: '관악기' },
  { value: 'slide-saxophone', label: '슬라이드 색소폰', labelEn: 'Slide Saxophone', category: '관악기' },
  { value: 'slide-trumpet', label: '슬라이드 트럼펫', labelEn: 'Slide Trumpet', category: '관악기' },
  { value: 'slide-whistle', label: '슬라이드 휘슬', labelEn: 'Slide Whistle', category: '관악기' },
  { value: 'sopranino-clarinet', label: '소프라니노 클라리넷', labelEn: 'Sopranino Clarinet', category: '관악기' },
  { value: 'sopranino-saxophone', label: '소프라니노 색소폰', labelEn: 'Sopranino Saxophone', category: '관악기' },
  { value: 'soprano', label: '소프라노', labelEn: 'Soprano', category: '관악기' },
  { value: 'soprano-clarinet', label: '소프라노 클라리넷', labelEn: 'Soprano Clarinet', category: '관악기' },
  { value: 'soprano-flute', label: '소프라노 플루트', labelEn: 'Soprano Flute', category: '관악기' },
  { value: 'soprano-recorder', label: '소프라노 리코더', labelEn: 'Soprano Recorder', category: '관악기' },
  { value: 'soprano-saxophone', label: '소프라노 색소폰', labelEn: 'Soprano Saxophone', category: '관악기' },
  { value: 'sousaphone', label: '수자폰', labelEn: 'Sousaphone', category: '관악기' },
  { value: 'stritch', label: '스트리치', labelEn: 'Stritch', category: '관악기' },
  { value: 'tabor-pipe', label: '테이버 파이프', labelEn: 'Tabor Pipe', category: '관악기' },
  { value: 'tarogato', label: '타로가토', labelEn: 'Tarogato', category: '관악기' },
  { value: 'tenor-horn', label: '테너 호른', labelEn: 'Tenor Horn', category: '관악기' },
  { value: 'tenor-recorder', label: '테너 리코더', labelEn: 'Tenor Recorder', category: '관악기' },
  { value: 'tenor-saxophone', label: '테너 색소폰', labelEn: 'Tenor Saxophone', category: '관악기' },
  { value: 'tenor-trombone', label: '테너 트롬본', labelEn: 'Tenor Trombone', category: '관악기' },
  { value: 'tin-whistle', label: '틴 휘슬', labelEn: 'Tin Whistle', category: '관악기' },
  { value: 'traverso', label: '트라베르소', labelEn: 'Traverso', category: '관악기' },
  { value: 'trombone', label: '트롬본', labelEn: 'Trombone', category: '관악기' },
  { value: 'trombonium', label: '트롬보늄', labelEn: 'Trombonium', category: '관악기' },
  { value: 'trumpet', label: '트럼펫', labelEn: 'Trumpet', category: '관악기' },
  { value: 'tuba', label: '튜바', labelEn: 'Tuba', category: '관악기' },
  { value: 'uilleann-pipes', label: '일리언 파이프', labelEn: 'Uilleann Pipes', category: '관악기' },
  { value: 'valve-trombone', label: '밸브 트롬본', labelEn: 'Valve Trombone', category: '관악기' },
  { value: 'venna', label: '베나', labelEn: 'Venna', category: '관악기' },
  { value: 'whistle', label: '휘슬', labelEn: 'Whistle', category: '관악기' },
  { value: 'wood-flute', label: '우드 플루트', labelEn: 'Wood Flute', category: '관악기' },
  { value: 'oboe', label: '오보에', labelEn: 'Oboe', category: '관악기' },
  { value: 'cusneophone', label: '커스네오폰', labelEn: 'Cusneophone', category: '관악기' },
  { value: 'electronic-valve-instrument', label: '일렉트로닉 밸브 악기', labelEn: 'Electronic Valve Instrument', category: '관악기' },
  { value: 'electronic-wind-instrument', label: '일렉트로닉 윈드 악기', labelEn: 'Electronic Wind Instrument', category: '관악기' },

  // Percussion
  { value: 'bass-drum', label: '베이스 드럼', labelEn: 'Bass Drum', category: '타악기' },
  { value: 'bata-drums', label: '바타 드럼', labelEn: 'Bata Drums', category: '타악기' },
  { value: 'bells', label: '벨', labelEn: 'Bells', category: '타악기' },
  { value: 'bendir', label: '벤디르', labelEn: 'Bendir', category: '타악기' },
  { value: 'berimbau', label: '베림바우', labelEn: 'Berimbau', category: '타악기' },
  { value: 'bonang', label: '보낭', labelEn: 'Bonang', category: '타악기' },
  { value: 'bongos', label: '봉고', labelEn: 'Bongos', category: '타악기' },
  { value: 'cajon', label: '카혼', labelEn: 'Cajon', category: '타악기' },
  { value: 'castanets', label: '캐스터네츠', labelEn: 'Castanets', category: '타악기' },
  { value: 'caxixi', label: '카시시', labelEn: 'Caxixi', category: '타악기' },
  { value: 'chekere', label: '체케레', labelEn: 'Chekere', category: '타악기' },
  { value: 'chimes', label: '차임', labelEn: 'Chimes', category: '타악기' },
  { value: 'claves', label: '클라베스', labelEn: 'Claves', category: '타악기' },
  { value: 'conch-shells', label: '소라', labelEn: 'Conch Shells', category: '타악기' },
  { value: 'congas', label: '콩가', labelEn: 'Congas', category: '타악기' },
  { value: 'cowbell', label: '카우벨', labelEn: 'Cowbell', category: '타악기' },
  { value: 'crotales', label: '크로탈레스', labelEn: 'Crotales', category: '타악기' },
  { value: 'cymbals', label: '심벌즈', labelEn: 'Cymbals', category: '타악기' },
  { value: 'daf', label: '다프', labelEn: 'Daf', category: '타악기' },
  { value: 'dhol', label: '돌', labelEn: 'Dhol', category: '타악기' },
  { value: 'djembe', label: '젬베', labelEn: 'Djembe', category: '타악기' },
  { value: 'doumbek', label: '둠벡', labelEn: 'Doumbek', category: '타악기' },
  { value: 'drums', label: '드럼', labelEn: 'Drums', category: '타악기' },
  { value: 'finger-cymbals', label: '핑거 심벌즈', labelEn: 'Finger Cymbals', category: '타악기' },
  { value: 'finger-snaps', label: '핑거 스냅', labelEn: 'Finger Snaps', category: '타악기' },
  { value: 'frame-drum', label: '프레임 드럼', labelEn: 'Frame Drum', category: '타악기' },
  { value: 'gender', label: '젠더', labelEn: 'Gender', category: '타악기' },
  { value: 'ghatam', label: '가탐', labelEn: 'Ghatam', category: '타악기' },
  { value: 'glockenspiel', label: '글로켄슈필', labelEn: 'Glockenspiel', category: '타악기' },
  { value: 'gong', label: '공', labelEn: 'Gong', category: '타악기' },
  { value: 'guro', label: '구로', labelEn: 'Guro', category: '타악기' },
  { value: 'handclaps', label: '핸드클랩', labelEn: 'Handclaps', category: '타악기' },
  { value: 'kaghouge', label: '하그호게', labelEn: "Hag'houge", category: '타악기' },
  { value: 'kalimba', label: '칼림바', labelEn: 'Kalimba', category: '타악기' },
  { value: 'karkaba', label: '카르카바', labelEn: 'Karkaba', category: '타악기' },
  { value: 'kendang', label: '큰당', labelEn: 'Kendang', category: '타악기' },
  { value: 'kenong-kethuk', label: '크농/크툭', labelEn: 'Kenong/Kethuk', category: '타악기' },
  { value: 'maracas', label: '마라카스', labelEn: 'Maracas', category: '타악기' },
  { value: 'marimba', label: '마림바', labelEn: 'Marimba', category: '타악기' },
  { value: 'mridangam', label: '므리당감', labelEn: 'Mridangam', category: '타악기' },
  { value: 'peking', label: '페킹', labelEn: 'Peking', category: '타악기' },
  { value: 'percussion', label: '퍼커션', labelEn: 'Percussion', category: '타악기' },
  { value: 'saron', label: '사론', labelEn: 'Saron', category: '타악기' },
  { value: 'shakers', label: '셰이커', labelEn: 'Shakers', category: '타악기' },
  { value: 'shekere', label: '셰케레', labelEn: 'Shekere', category: '타악기' },
  { value: 'sleigh-bells', label: '슬레이 벨', labelEn: 'Sleigh Bells', category: '타악기' },
  { value: 'slenthem', label: '슬렌템', labelEn: 'Slenthem', category: '타악기' },
  { value: 'snare-drum', label: '스네어 드럼', labelEn: 'Snare Drum', category: '타악기' },
  { value: 'spoons', label: '스푼', labelEn: 'Spoons', category: '타악기' },
  { value: 'steel-drums', label: '스틸 드럼', labelEn: 'Steel Drums', category: '타악기' },
  { value: 'surdo', label: '수르도', labelEn: 'Surdo', category: '타악기' },
  { value: 'tabla', label: '타블라', labelEn: 'Tabla', category: '타악기' },
  { value: 'talking-drum', label: '토킹 드럼', labelEn: 'Talking Drum', category: '타악기' },
  { value: 'tamborim', label: '탐보림', labelEn: 'Tamborim', category: '타악기' },
  { value: 'tambourine', label: '탬버린', labelEn: 'Tambourine', category: '타악기' },
  { value: 'temple-blocks', label: '템플 블록', labelEn: 'Temple Blocks', category: '타악기' },
  { value: 'tenor-drum', label: '테너 드럼', labelEn: 'Tenor Drum', category: '타악기' },
  { value: 'thavil', label: '타빌', labelEn: 'Thavil', category: '타악기' },
  { value: 'timbales', label: '팀발레스', labelEn: 'Timbales', category: '타악기' },
  { value: 'timpani', label: '팀파니', labelEn: 'Timpani', category: '타악기' },
  { value: 'triangle', label: '트라이앵글', labelEn: 'Triangle', category: '타악기' },
  { value: 'tubular-bells', label: '튜블러 벨', labelEn: 'Tubular Bells', category: '타악기' },
  { value: 'udu', label: '우두', labelEn: 'Udu', category: '타악기' },
  { value: 'vibraphone', label: '비브라폰', labelEn: 'Vibraphone', category: '타악기' },
  { value: 'vibraslap', label: '비브라슬랩', labelEn: 'Vibraslap', category: '타악기' },
  { value: 'washboard', label: '워시보드', labelEn: 'Washboard', category: '타악기' },
  { value: 'wood-block', label: '우드 블록', labelEn: 'Wood Block', category: '타악기' },
  { value: 'xylophone', label: '실로폰', labelEn: 'Xylophone', category: '타악기' },
  { value: 'xyloimba', label: '실로임바', labelEn: 'Xyloimba', category: '타악기' },
  { value: 'zarb', label: '자르브', labelEn: 'Zarb', category: '타악기' },
  { value: 'balafon', label: '발라폰', labelEn: 'Balafon', category: '타악기' },

  // Electronic
  { value: 'drum-machine', label: '드럼 머신', labelEn: 'Drum Machine', category: '전자악기' },
  { value: 'sampler', label: '샘플러', labelEn: 'Sampler', category: '전자악기' },
  { value: 'turntable', label: '턴테이블', labelEn: 'Turntable', category: '전자악기' },
  { value: 'modular-synth', label: '모듈러 신스', labelEn: 'Modular Synth', category: '전자악기' },
  { value: 'theremin', label: '테레민', labelEn: 'Theremin', category: '전자악기' },

  // Voice
  { value: 'vocals', label: '보컬', labelEn: 'Vocals', category: '보컬' },
  { value: 'alto-vocals', label: '알토 보컬', labelEn: 'Alto Vocals', category: '보컬' },
  { value: 'baritone-vocals', label: '바리톤 보컬', labelEn: 'Baritone Vocals', category: '보컬' },
  { value: 'bass-vocals', label: '베이스 보컬', labelEn: 'Bass Vocals', category: '보컬' },
  { value: 'chant-vocals', label: '챈트 보컬', labelEn: 'Chant Vocals', category: '보컬' },
  { value: 'contralto-vocals', label: '콘트랄토 보컬', labelEn: 'Contralto Vocals', category: '보컬' },
  { value: 'counter-tenor', label: '카운터 테너', labelEn: 'Counter Tenor', category: '보컬' },
  { value: 'harmony-vocals', label: '하모니 보컬', labelEn: 'Harmony Vocals', category: '보컬' },
  { value: 'mezzo-soprano-vocals', label: '메조 소프라노 보컬', labelEn: 'Mezzo-soprano Vocals', category: '보컬' },
  { value: 'soprano-vocals', label: '소프라노 보컬', labelEn: 'Soprano Vocals', category: '보컬' },
  { value: 'tenor-vocals', label: '테너 보컬', labelEn: 'Tenor Vocals', category: '보컬' },
  { value: 'background-vocals', label: '백그라운드 보컬', labelEn: 'Background Vocals', category: '보컬' },
  { value: 'beat-boxing', label: '비트박싱', labelEn: 'Beat Boxing', category: '보컬' },
  { value: 'noises', label: '노이즈', labelEn: 'Noises', category: '보컬' },
  { value: 'talkbox', label: '토크박스', labelEn: 'Talkbox', category: '보컬' },
  { value: 'vocoder', label: '보코더', labelEn: 'Vocoder', category: '보컬' },

  // Other
  { value: 'bandoneon', label: '반도네온', labelEn: 'Bandoneon', category: '기타' },
  { value: 'baglama', label: '바글라마', labelEn: 'Baglama', category: '기타' },
  { value: 'haaghouge', label: '하그호게', labelEn: "Hag'houge", category: '기타' },
  { value: 'hurdy-gurdy', label: '허디거디', labelEn: 'Hurdy Gurdy', category: '기타' }
];

export function getInstrumentsByCategory(category: string): Instrument[] {
  return instrumentList.filter(instrument => instrument.category === category);
}

export function searchInstruments(query: string): Instrument[] {
  const lowercaseQuery = query.toLowerCase();
  return instrumentList.filter(instrument =>
    instrument.label.toLowerCase().includes(lowercaseQuery) ||
    instrument.labelEn.toLowerCase().includes(lowercaseQuery) ||
    instrument.value.toLowerCase().includes(lowercaseQuery)
  );
}

export function getInstrumentLabel(value: string, language: 'ko' | 'en' = 'ko'): string {
  const instrument = instrumentList.find(i => i.value === value);
  return instrument ? (language === 'ko' ? instrument.label : instrument.labelEn) : value;
}

export function getInstrumentCategory(value: string): string {
  const instrument = instrumentList.find(i => i.value === value);
  return instrument?.category || '';
}
