// Comprehensive territories data for music distribution
export interface Territory {
  code: string;
  name: string;
  region: 'Africa' | 'Americas' | 'Asia' | 'Europe' | 'Oceania';
}

export const territories: Territory[] = [
  // Africa (58 Total)
  { code: 'DZ', name: 'Algeria', region: 'Africa' },
  { code: 'AO', name: 'Angola', region: 'Africa' },
  { code: 'BJ', name: 'Benin', region: 'Africa' },
  { code: 'BW', name: 'Botswana', region: 'Africa' },
  { code: 'BF', name: 'Burkina Faso', region: 'Africa' },
  { code: 'BI', name: 'Burundi', region: 'Africa' },
  { code: 'CM', name: 'Cameroon', region: 'Africa' },
  { code: 'CV', name: 'Cape Verde', region: 'Africa' },
  { code: 'CF', name: 'Central African Republic', region: 'Africa' },
  { code: 'TD', name: 'Chad', region: 'Africa' },
  { code: 'KM', name: 'Comoros', region: 'Africa' },
  { code: 'CG', name: 'Congo', region: 'Africa' },
  { code: 'CD', name: 'Congo (DR)', region: 'Africa' },
  { code: 'CI', name: 'Cote d\'Ivoire', region: 'Africa' },
  { code: 'DJ', name: 'Djibouti', region: 'Africa' },
  { code: 'EG', name: 'Egypt', region: 'Africa' },
  { code: 'GQ', name: 'Equatorial Guinea', region: 'Africa' },
  { code: 'ER', name: 'Eritrea', region: 'Africa' },
  { code: 'ET', name: 'Ethiopia', region: 'Africa' },
  { code: 'GA', name: 'Gabon', region: 'Africa' },
  { code: 'GM', name: 'Gambia', region: 'Africa' },
  { code: 'GH', name: 'Ghana', region: 'Africa' },
  { code: 'GN', name: 'Guinea', region: 'Africa' },
  { code: 'GW', name: 'Guinea-Bissau', region: 'Africa' },
  { code: 'KE', name: 'Kenya', region: 'Africa' },
  { code: 'LS', name: 'Lesotho', region: 'Africa' },
  { code: 'LR', name: 'Liberia', region: 'Africa' },
  { code: 'LY', name: 'Libyan Arab Jamahiriya', region: 'Africa' },
  { code: 'MG', name: 'Madagascar', region: 'Africa' },
  { code: 'MW', name: 'Malawi', region: 'Africa' },
  { code: 'ML', name: 'Mali', region: 'Africa' },
  { code: 'MR', name: 'Mauritania', region: 'Africa' },
  { code: 'MU', name: 'Mauritius', region: 'Africa' },
  { code: 'YT', name: 'Mayotte', region: 'Africa' },
  { code: 'MA', name: 'Morocco', region: 'Africa' },
  { code: 'MZ', name: 'Mozambique', region: 'Africa' },
  { code: 'NA', name: 'Namibia', region: 'Africa' },
  { code: 'NE', name: 'Niger', region: 'Africa' },
  { code: 'NG', name: 'Nigeria', region: 'Africa' },
  { code: 'RE', name: 'Reunion', region: 'Africa' },
  { code: 'RW', name: 'Rwanda', region: 'Africa' },
  { code: 'SH', name: 'Saint Helena', region: 'Africa' },
  { code: 'ST', name: 'Sao Tome and Principe', region: 'Africa' },
  { code: 'SN', name: 'Senegal', region: 'Africa' },
  { code: 'SC', name: 'Seychelles', region: 'Africa' },
  { code: 'SL', name: 'Sierra Leone', region: 'Africa' },
  { code: 'SO', name: 'Somalia', region: 'Africa' },
  { code: 'ZA', name: 'South Africa', region: 'Africa' },
  { code: 'SS', name: 'South Sudan', region: 'Africa' },
  { code: 'SD', name: 'Sudan', region: 'Africa' },
  { code: 'SZ', name: 'Swaziland', region: 'Africa' },
  { code: 'TG', name: 'Togo', region: 'Africa' },
  { code: 'TN', name: 'Tunisia', region: 'Africa' },
  { code: 'UG', name: 'Uganda', region: 'Africa' },
  { code: 'TZ', name: 'United Republic of Tanzania', region: 'Africa' },
  { code: 'EH', name: 'Western Sahara', region: 'Africa' },
  { code: 'ZM', name: 'Zambia', region: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe', region: 'Africa' },

  // Americas (55 Total)
  { code: 'AI', name: 'Anguilla', region: 'Americas' },
  { code: 'AG', name: 'Antigua and Barbuda', region: 'Americas' },
  { code: 'AR', name: 'Argentina', region: 'Americas' },
  { code: 'AW', name: 'Aruba', region: 'Americas' },
  { code: 'BS', name: 'Bahamas', region: 'Americas' },
  { code: 'BB', name: 'Barbados', region: 'Americas' },
  { code: 'BZ', name: 'Belize', region: 'Americas' },
  { code: 'BM', name: 'Bermuda', region: 'Americas' },
  { code: 'BO', name: 'Bolivia', region: 'Americas' },
  { code: 'BQ', name: 'Bonaire, Saint Eustatius and Saba', region: 'Americas' },
  { code: 'BR', name: 'Brazil', region: 'Americas' },
  { code: 'VG', name: 'British Virgin Islands', region: 'Americas' },
  { code: 'CA', name: 'Canada', region: 'Americas' },
  { code: 'KY', name: 'Cayman Islands', region: 'Americas' },
  { code: 'CL', name: 'Chile', region: 'Americas' },
  { code: 'CO', name: 'Colombia', region: 'Americas' },
  { code: 'CR', name: 'Costa Rica', region: 'Americas' },
  { code: 'CU', name: 'Cuba', region: 'Americas' },
  { code: 'CW', name: 'Curacao', region: 'Americas' },
  { code: 'DM', name: 'Dominica', region: 'Americas' },
  { code: 'DO', name: 'Dominican Republic', region: 'Americas' },
  { code: 'EC', name: 'Ecuador', region: 'Americas' },
  { code: 'SV', name: 'El Salvador', region: 'Americas' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', region: 'Americas' },
  { code: 'GF', name: 'French Guiana', region: 'Americas' },
  { code: 'GL', name: 'Greenland', region: 'Americas' },
  { code: 'GD', name: 'Grenada', region: 'Americas' },
  { code: 'GP', name: 'Guadeloupe', region: 'Americas' },
  { code: 'GT', name: 'Guatemala', region: 'Americas' },
  { code: 'GY', name: 'Guyana', region: 'Americas' },
  { code: 'HT', name: 'Haiti', region: 'Americas' },
  { code: 'HN', name: 'Honduras', region: 'Americas' },
  { code: 'JM', name: 'Jamaica', region: 'Americas' },
  { code: 'MQ', name: 'Martinique', region: 'Americas' },
  { code: 'MX', name: 'Mexico', region: 'Americas' },
  { code: 'MS', name: 'Montserrat', region: 'Americas' },
  { code: 'NI', name: 'Nicaragua', region: 'Americas' },
  { code: 'PA', name: 'Panama', region: 'Americas' },
  { code: 'PY', name: 'Paraguay', region: 'Americas' },
  { code: 'PE', name: 'Peru', region: 'Americas' },
  { code: 'PR', name: 'Puerto Rico', region: 'Americas' },
  { code: 'BL', name: 'Saint Barthelemy', region: 'Americas' },
  { code: 'KN', name: 'Saint Kitts and Nevis', region: 'Americas' },
  { code: 'LC', name: 'Saint Lucia', region: 'Americas' },
  { code: 'MF', name: 'Saint Martin', region: 'Americas' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', region: 'Americas' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', region: 'Americas' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', region: 'Americas' },
  { code: 'SR', name: 'Suriname', region: 'Americas' },
  { code: 'TT', name: 'Trinidad and Tobago', region: 'Americas' },
  { code: 'TC', name: 'Turks and Caicos Islands', region: 'Americas' },
  { code: 'US', name: 'United States of America', region: 'Americas' },
  { code: 'VI', name: 'United States Virgin Islands', region: 'Americas' },
  { code: 'UY', name: 'Uruguay', region: 'Americas' },
  { code: 'VE', name: 'Venezuela', region: 'Americas' },

  // Asia (50 Total)
  { code: 'AF', name: 'Afghanistan', region: 'Asia' },
  { code: 'AM', name: 'Armenia', region: 'Asia' },
  { code: 'AZ', name: 'Azerbaijan', region: 'Asia' },
  { code: 'BH', name: 'Bahrain', region: 'Asia' },
  { code: 'BD', name: 'Bangladesh', region: 'Asia' },
  { code: 'BT', name: 'Bhutan', region: 'Asia' },
  { code: 'BN', name: 'Brunei Darussalam', region: 'Asia' },
  { code: 'KH', name: 'Cambodia', region: 'Asia' },
  { code: 'CN', name: 'China', region: 'Asia' },
  { code: 'GE', name: 'Georgia', region: 'Asia' },
  { code: 'HK', name: 'Hong Kong', region: 'Asia' },
  { code: 'IN', name: 'India', region: 'Asia' },
  { code: 'ID', name: 'Indonesia', region: 'Asia' },
  { code: 'IR', name: 'Iran Islamic Republic of', region: 'Asia' },
  { code: 'IQ', name: 'Iraq', region: 'Asia' },
  { code: 'IL', name: 'Israel', region: 'Asia' },
  { code: 'JP', name: 'Japan', region: 'Asia' },
  { code: 'JO', name: 'Jordan', region: 'Asia' },
  { code: 'KZ', name: 'Kazakhstan', region: 'Asia' },
  { code: 'KP', name: 'Korea (DPRK)', region: 'Asia' },
  { code: 'KW', name: 'Kuwait', region: 'Asia' },
  { code: 'KG', name: 'Kyrgyzstan', region: 'Asia' },
  { code: 'LA', name: 'Laos (PDR)', region: 'Asia' },
  { code: 'LB', name: 'Lebanon', region: 'Asia' },
  { code: 'MO', name: 'Macao', region: 'Asia' },
  { code: 'MY', name: 'Malaysia', region: 'Asia' },
  { code: 'MV', name: 'Maldives', region: 'Asia' },
  { code: 'MN', name: 'Mongolia', region: 'Asia' },
  { code: 'MM', name: 'Myanmar', region: 'Asia' },
  { code: 'NP', name: 'Nepal', region: 'Asia' },
  { code: 'PS', name: 'Occupied Palestinian Territory', region: 'Asia' },
  { code: 'OM', name: 'Oman', region: 'Asia' },
  { code: 'PK', name: 'Pakistan', region: 'Asia' },
  { code: 'PH', name: 'Philippines', region: 'Asia' },
  { code: 'QA', name: 'Qatar', region: 'Asia' },
  { code: 'KR', name: 'Republic of Korea', region: 'Asia' },
  { code: 'SA', name: 'Saudi Arabia', region: 'Asia' },
  { code: 'SG', name: 'Singapore', region: 'Asia' },
  { code: 'LK', name: 'Sri Lanka', region: 'Asia' },
  { code: 'SY', name: 'Syrian Arab Republic', region: 'Asia' },
  { code: 'TW', name: 'Taiwan', region: 'Asia' },
  { code: 'TJ', name: 'Tajikistan', region: 'Asia' },
  { code: 'TH', name: 'Thailand', region: 'Asia' },
  { code: 'TL', name: 'Timor-Leste', region: 'Asia' },
  { code: 'TR', name: 'Turkey', region: 'Asia' },
  { code: 'TM', name: 'Turkmenistan', region: 'Asia' },
  { code: 'AE', name: 'United Arab Emirates', region: 'Asia' },
  { code: 'UZ', name: 'Uzbekistan', region: 'Asia' },
  { code: 'VN', name: 'Viet Nam', region: 'Asia' },
  { code: 'YE', name: 'Yemen', region: 'Asia' },

  // Europe (52 Total)
  { code: 'AX', name: 'Aland Islands', region: 'Europe' },
  { code: 'AL', name: 'Albania', region: 'Europe' },
  { code: 'AD', name: 'Andorra', region: 'Europe' },
  { code: 'AT', name: 'Austria', region: 'Europe' },
  { code: 'BY', name: 'Belarus', region: 'Europe' },
  { code: 'BE', name: 'Belgium', region: 'Europe' },
  { code: 'BA', name: 'Bosnia and Herzegovina', region: 'Europe' },
  { code: 'BG', name: 'Bulgaria', region: 'Europe' },
  { code: 'HR', name: 'Croatia', region: 'Europe' },
  { code: 'CY', name: 'Cyprus', region: 'Europe' },
  { code: 'CZ', name: 'Czech Republic', region: 'Europe' },
  { code: 'DK', name: 'Denmark', region: 'Europe' },
  { code: 'EE', name: 'Estonia', region: 'Europe' },
  { code: 'FO', name: 'Faeroe Islands', region: 'Europe' },
  { code: 'FI', name: 'Finland', region: 'Europe' },
  { code: 'FR', name: 'France', region: 'Europe' },
  { code: 'DE', name: 'Germany', region: 'Europe' },
  { code: 'GI', name: 'Gibraltar', region: 'Europe' },
  { code: 'GR', name: 'Greece', region: 'Europe' },
  { code: 'GG', name: 'Guernsey', region: 'Europe' },
  { code: 'VA', name: 'Holy See', region: 'Europe' },
  { code: 'HU', name: 'Hungary', region: 'Europe' },
  { code: 'IS', name: 'Iceland', region: 'Europe' },
  { code: 'IE', name: 'Ireland', region: 'Europe' },
  { code: 'IM', name: 'Isle Of Man', region: 'Europe' },
  { code: 'IT', name: 'Italy', region: 'Europe' },
  { code: 'JE', name: 'Jersey', region: 'Europe' },
  { code: 'LV', name: 'Latvia', region: 'Europe' },
  { code: 'LI', name: 'Liechtenstein', region: 'Europe' },
  { code: 'LT', name: 'Lithuania', region: 'Europe' },
  { code: 'LU', name: 'Luxembourg', region: 'Europe' },
  { code: 'MK', name: 'Macedonia (frm Yugoslavia)', region: 'Europe' },
  { code: 'MT', name: 'Malta', region: 'Europe' },
  { code: 'MC', name: 'Monaco', region: 'Europe' },
  { code: 'ME', name: 'Montenegro', region: 'Europe' },
  { code: 'NL', name: 'Netherlands', region: 'Europe' },
  { code: 'NO', name: 'Norway', region: 'Europe' },
  { code: 'PL', name: 'Poland', region: 'Europe' },
  { code: 'PT', name: 'Portugal', region: 'Europe' },
  { code: 'MD', name: 'Republic of Moldova', region: 'Europe' },
  { code: 'RO', name: 'Romania', region: 'Europe' },
  { code: 'RU', name: 'Russian Federation', region: 'Europe' },
  { code: 'SM', name: 'San Marino', region: 'Europe' },
  { code: 'RS', name: 'Serbia', region: 'Europe' },
  { code: 'SK', name: 'Slovakia', region: 'Europe' },
  { code: 'SI', name: 'Slovenia', region: 'Europe' },
  { code: 'ES', name: 'Spain', region: 'Europe' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen Islands', region: 'Europe' },
  { code: 'SE', name: 'Sweden', region: 'Europe' },
  { code: 'CH', name: 'Switzerland', region: 'Europe' },
  { code: 'UA', name: 'Ukraine', region: 'Europe' },
  { code: 'GB', name: 'United Kingdom of Great Britain', region: 'Europe' },

  // Oceania (34 Total)
  { code: 'AS', name: 'American Samoa', region: 'Oceania' },
  { code: 'AQ', name: 'Antarctica', region: 'Oceania' },
  { code: 'AU', name: 'Australia', region: 'Oceania' },
  { code: 'BV', name: 'Bouvet Island', region: 'Oceania' },
  { code: 'IO', name: 'British Indian Ocean Territory', region: 'Oceania' },
  { code: 'CX', name: 'Christmas Island', region: 'Oceania' },
  { code: 'CC', name: 'Cocos (Keeling)', region: 'Oceania' },
  { code: 'CK', name: 'Cook Islands', region: 'Oceania' },
  { code: 'FJ', name: 'Fiji', region: 'Oceania' },
  { code: 'PF', name: 'French Polynesia', region: 'Oceania' },
  { code: 'TF', name: 'French Southern Territories', region: 'Oceania' },
  { code: 'GU', name: 'Guam', region: 'Oceania' },
  { code: 'HM', name: 'Heard and McDonald Islands', region: 'Oceania' },
  { code: 'KI', name: 'Kiribati', region: 'Oceania' },
  { code: 'MH', name: 'Marshall Islands', region: 'Oceania' },
  { code: 'FM', name: 'Micronesia', region: 'Oceania' },
  { code: 'NR', name: 'Nauru', region: 'Oceania' },
  { code: 'NC', name: 'New Caledonia', region: 'Oceania' },
  { code: 'NZ', name: 'New Zealand', region: 'Oceania' },
  { code: 'NU', name: 'Niue', region: 'Oceania' },
  { code: 'NF', name: 'Norfolk Island', region: 'Oceania' },
  { code: 'MP', name: 'Northern Mariana Islands', region: 'Oceania' },
  { code: 'PW', name: 'Palau', region: 'Oceania' },
  { code: 'PG', name: 'Papua New Guinea', region: 'Oceania' },
  { code: 'PN', name: 'Pitcairn', region: 'Oceania' },
  { code: 'WS', name: 'Samoa', region: 'Oceania' },
  { code: 'SB', name: 'Solomon Islands', region: 'Oceania' },
  { code: 'GS', name: 'South Georgia and South Sandwich Islands', region: 'Oceania' },
  { code: 'TK', name: 'Tokelau', region: 'Oceania' },
  { code: 'TO', name: 'Tonga', region: 'Oceania' },
  { code: 'TV', name: 'Tuvalu', region: 'Oceania' },
  { code: 'UM', name: 'US Minor Outlying Islands', region: 'Oceania' },
  { code: 'VU', name: 'Vanuatu', region: 'Oceania' },
  { code: 'WF', name: 'Wallis and Futuna Islands', region: 'Oceania' }
];

export const regions = ['World', 'Africa', 'Americas', 'Asia', 'Europe', 'Oceania'] as const;
export type Region = typeof regions[number];

export const getTerritoriesByRegion = (region: Region): Territory[] => {
  if (region === 'World') return territories;
  return territories.filter(t => t.region === region);
};

export const regionCounts = {
  World: territories.length,
  Africa: territories.filter(t => t.region === 'Africa').length,
  Americas: territories.filter(t => t.region === 'Americas').length,
  Asia: territories.filter(t => t.region === 'Asia').length,
  Europe: territories.filter(t => t.region === 'Europe').length,
  Oceania: territories.filter(t => t.region === 'Oceania').length
};