export const DSP_SEED_DATA = [
  {
    dspId: "247916",
    name: "7Digital",
    code: "via IIP-DDS",
    description: "7digital are a digital media delivery company, which means, among other things, we create download stores. Lots of them. Over the last few years we have created hundreds of digital services that provide music, video, audio books, games, documents, streaming media, subscription services and pretty much anything else you can think of that can be delivered digitally. We have provided services that enable record labels, television stations, internet service providers, film companies, FMCG brands, newspapers and individual artists to make sales and deliver digital content. We can create a service for you, or give you access to our API which will allow you to develop your own service. With second to none international experience, a vast catalogue and good working relationships with everyone who matters, we are perfectly placed to help you make music part of your offering.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "99268",
    name: "Amazon",
    code: "via IIP-DDS",
    description: "Amazon.com Inc (AMZN) is a leading global Internet company and one of the most trafficked Internet retail destinations worldwide. Amazon directly sells, or acts as a platform for the sale of, a very broad range of products, including books, music, videos, consumer electronics, clothing and household products. The majority of Amazon's sales are products sold by Amazon, with the remaining amount from third-party sellers. Through year-end 2006, Amazon had approximately 64 million active customers worldwide. In 2006, 55% of Amazon's revenue was generated in North America and 45% was generated by its International segment. Within North America, Media was 61% of total sales, Electronics & General Merchandise (EGM) was 34% of the total, and Other revenue was 4%. Within its International segment, Media was 72% of sales and EGM was 28% of sales. Amazon has direct operations in the United States, Canada, France, Germany, Japan, and the United Kingdom. Amazon was founded in 1994 and is headquartered in Seattle, Washington. Amazon is an online shopping website with one of the largest product supplies online. It was one of the first companies to sell products deep into the long tail by housing them all in numerous warehouses and distributing products from many partner companies. Since 2004 Amazon has begun rapidly expanding its web services arsenal. Products such as Amazon EC2 (Elastic Compute Cloud) and Amazon S3 (Simple Storage System), have been large success. Prior to these services Amazon had survived on a low margin business model that relied on enormous volume in product sales. Amazon is looking to these services to provide a healthier profit margin.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "104465305",
    name: "Ami Entertainment",
    code: "via IIP-DDS",
    contactEmail: "musicrequests@amientertainment.com",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "20799134",
    name: "Anghami",
    code: "via IIP-DDS",
    description: "\"Anghami – Music. Unlimited.\" is a music service/app tapping for the first time into the MENA (Middle-East North-Africa) region and offering Arabic and International licensed music content as well as poetry, religious and bollywood content - adapted to the varied regional tastes. Anghami (meaning my-tunes in Arabic) offers unlimited music to stream and play offline for a monthly subscription with a 'try-before-you-buy' one month trial. Anghami features content from leading Arabic labels such as Rotana, Mazzika, Melody as well as leading Arabic and regional aggregators. Anghami also features the major international labels such as Sony, EMI, Warner and continuously licensing new content for a greater user-experience. Anghami is based in Lebanon and is funded by leading firms bringing in the largest digital music project ever to the region.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1330598",
    name: "Apple Music",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "847103579",
    name: "AWA",
    code: "via IIP-DDS",
    description: "A joint venture established between Cyber Agent and Avex that specializes in the \"Music x IT\" field. We have started a new music streaming service combining both company's knowledge.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "89882",
    name: "Beatport",
    code: "via IIP-DDS",
    description: "About Us Beatport is the recognized leader of electronic music downloads by DJs and fans alike delivering content in premium-encoded formats that match the professional performance quality standards of the world's leading sound systems. Beatport.com allows users to access the world of club music through secure, legal, hi-speed, high quality downloads in MP3, MP4 and WAV formats on a pay per download basis from an impressive library of the world's leading independent labels. Mission Statement Music. Technology. Culture. Design. Beatport is the most relevant online source of electronic music in the world. History The first version of Beatport launched in January 2004 with 79 record labels on board. By mid 2004, Beatport started to gain recognition collaborating with some of the top DJs and technology companies in the business such as Native Instruments in Berlin and world-renowned dance artists, Bad Boy Bill, John Acquaviva and Richie Hawtin. With the re-vision of the site January 2005, the momentum of Beatport's achievements picked up speed. Beatport 2.0 soon became the recognized global leader in Independent dance music, building a catalog over 100,000 tracks supplied by 2,700 signed labels. With the third re-launch, Beatport 3.0 displays significant improvements to the site. Adding to the already impressive list of features, 3.0 includes a more robust search engine, 'My Beatport', 'Users Also Bought' 'Customized weekly emails' 'Enhanced Top 10 lists' and 'Email to a Friend.' To help with music discovery, Beatport launched a corresponding community site, Beatportal.com, on May 28, 2007. Beatportal is a result of Beatport's goal to be the most relevant online resource for electronic music. The vision for Beatportal is to provide music lovers with up-to-date information about the world of electronic music. This site offers access to music news, industry news, music reviews, Podcasts, videos, DJ profiles, event listings, nightclubs, and much more. Beatport's main office is located in Denver Colorado with satellite offices in New York and Berlin.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1158892521",
    name: "Bmat",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1501350807",
    name: "Bugs!",
    code: "via IIP-DDS",
    description: "Bugs Music is the 3rd largest music service in Korea and offers similar functionalities and services as MelON. Bugs also delivers content to Music Mate, one of the smaller but still popular music services in South Korea. Bugs Music and Music Mate both feature international catalogue, but local content generates more than 80% of total revenues.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "2100357",
    name: "Deezer",
    code: "via IIP-DDS",
    description: "DEEZER, 1st European streaming service",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "2215088010",
    name: "Dreamus Company (FLO)",
    code: "via IIP-DDS",
    description: "AI-based music recommendation service optimized for individual tastes, deviating from service provision based on real-time charts.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1499657856",
    name: "Facebook Audio Library",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "SOCIAL"
  },
  {
    dspId: "1415672002",
    name: "Facebook Fingerprinting",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "FINGERPRINTING"
  },
  {
    dspId: "2721730765",
    name: "Facebook Video",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "VIDEO"
  },
  {
    dspId: "2929664894",
    name: "Facebook Video Fingerprinting",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "FINGERPRINTING"
  },
  {
    dspId: "1988507361",
    name: "fizy",
    code: "via IIP-DDS",
    description: "fizy is the most known and used music platform in Turkey. Fully on-demand music service, users can listen millions of songs, also can watch video clips and live broadcasting concerts. Currently fizy is available in 5 different countries; Turkey, Northern Cyprus, Ukraine, Belarus and Germany. Our business is based on subscribtion models.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "2697871022",
    name: "Genie Music",
    code: "via IIP-DDS",
    description: "Genie Music is a 'digital music platform' company and operates online music services in South Korea.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "9538495",
    name: "Gracenote",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "32483420",
    name: "HighResAudio",
    code: "via IIP-DDS",
    description: "highresaudio.com is a high-resolution music download service offering a diverse catalog of music in only 24-bit resolution. highresaudio is the perfect companion for audiophiles, music lovers and digital audio systems and anywhere else that pure sound quality matters. highresaudio is founded by a team of experienced, visionary and enthusiastic music specialists in Germany. We embrace the transformation brought by technologies to the music industry and audiophiles in the pursuit of the ultrasonic music experience. highresaudio strives to develop innovative services and applications, business models and shape new commercial opportunities for record labels, artists and manufacturers of digital audio products.",
    territories: ["World"],
    availability: "Immediately",
    isHD: true,
    serviceType: "DOWNLOAD"
  },
  {
    dspId: "1268816855",
    name: "Hungama",
    code: "via IIP-DDS",
    description: "Hungama Digital Media Entertainment Private Limited is the largest aggregator, developer, publisher and distributor of Bollywood, International and South-Asian entertainment content in the world. Leader in Mobile & Digital Entertainment solutions, Digital Advertising, Gaming and Applications. With partnerships with over 400 content creators, Hungama has licensed worldwide exclusive digital rights to millions of music and video content. We manage India's premium cross platform digital entertainment store, Hungama.com, offering content across all genres and all forms. Full length Movies, music tracks, music videos, short films, ringtones, mobile content and applications across various categories for digital downloads. Accessible from a PC & Mobile, users can enjoy all this content anytime, anywhere.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "3441649",
    name: "iHeartRadio",
    code: "via IIP-DDS",
    description: "iHeartRadio allows you to listen to your favorite live radio stations or create your own commercial-free custom music stations. Features: • The best of LIVE INTERNET RADIO: pop, country, hip-hop and R&B, rock, talk, news, sports & more • Create CUSTOM MUSIC stations: over 18 million songs from more than 400,000 artists • PERFECT FOR: music playlists for working, driving, working out & hundreds more activities • TALK: on-demand talk radio episodes from great names in news, sports, finance, comedy & entertainment",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "RADIO"
  },
  {
    dspId: "103725",
    name: "iMusica / Claro SA",
    code: "via IIP-DDS",
    description: "Created in 2000, iMusica is a pioneer in Latin America in distribution of digital media and sales of legally downloaded audiovisual content over the Internet, and more recently, via cell phones. It has over 2 million tracks licensed for legal distribution, and has secured agreements with Warner Music, Universal Music, Emi Music, Sony music, Som Livre, Deckdisc, Trama, Biscoito Fino and over 300 independent national and international recording companies. It has a network of music stores on the Internet in partnership with the largest e-commerce portals and sites, such as MSN.com.br, Yahoo.com.br, Americanas.com, Submarino.com, Som Livre, among others. Present in 18 Latin American countries, iMusica also acts as a content aggregator for the main digital services abroad, such as iTunes, AmazonMp3, eMusic.com, among others.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "316911752",
    name: "JioSaavn",
    code: "via IIP-DDS",
    description: "Saavn is India's leading digital music service, transforming how people around the world access and experience music on a daily basis. Through its unique combination of Internet radio and on-demand music, coupled with proprietary social features like music tagging and music chat, Saavn delivers one of the richest media experiences available on mobile and Web today. Saavn is currently accessed in more than 150 countries and offers 7 million+ tracks in 11 languages. The company's award-winning iOS and Android mobile products include phonetic search, dynamic bit-rate streaming, global native ad-serving, and industry-leading design. With Saavn Pro, users can listen to music ad-free and offline. And through partnerships with Apple, Google, Facebook, Twitter, and Shazam, Saavn reaches more music fans than any other South Asian music service.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1517454273",
    name: "Joox",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1686928319",
    name: "Kakao / MelOn",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "121452605",
    name: "KkBox",
    code: "via IIP-DDS",
    description: "KKBOX, Asia's leading music streaming service, was established in 2004 by a group of Taiwanese software programmers with a shared passion for technology and music. With the support from more than 500 international major and local independent music labels, KKBOX features 20 million legal tracks, including the most comprehensive Asia-Pop music library, and is currently available in Taiwan, Hong Kong, Japan, Singapore, Malaysia and Thailand with over 10 million users.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1226212715",
    name: "Kuack Media",
    code: "via IIP-DDS",
    description: "Kuack Media Group developed a streaming music app for subscription, multiplatform and multi-label which has 2 types of service with different prices; \"Premium\" and \"Top Chart\".The Premium service allows users access to unlimited music streaming, conditional downloads, create playlists, share on social networks, etc. The Top Chart service has access to a top 40 and the user can select up to 5 playlists from a list of curated playlist and then can rotate them every 7 days. This service also allows conditional downloads but only of the complete playlist, not individual tracks. Our music app is available through mobile carriers in Anguilla, Antigua & Barbuda, Aruba, Barbados, Bermuda, Bolivia, Bonaire, British Virgin Islands, Cayman Islands, Colombia, Costa Rica, Curacao, Dominican Republic, Dominique, El Salvador, French Guiana, Grenada, Guadeloupe, Haiti, Jamaica, Martinique, Panama, Peru, St. Kills & Nevis, St. Lucia, St, Vincent & the Grenadines, Suriname, Trinidad & Tobago, Turks & Caicos",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1232212955",
    name: "LINE Music",
    code: "via IIP-DDS",
    description: "LINE MUSIC is a subscription based music streaming service which is integrated into the LINE app, Japan`s #1 instant messaging service with 220 million users global MAU (Monthly Active Users). Users can effortlessly send music or playlists directly to friends or groups on the LINE app's chat screen or share them on their Timeline. LINE is at the forefront of merging channels to bring communication and entertainment services closer together to users, offering a revolutionary mobile experience. directly to friends or groups on the LINE app's chat screen or share them on their Timeline. LINE is at the forefront of merging channels to bring communication and entertainment services closer together to users, offering a revolutionary mobile experience.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "3887807596",
    name: "LyricFind",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "OTHER"
  },
  {
    dspId: "3357532813",
    name: "MePlaylist",
    code: "via IIP-DDS",
    description: "MePlaylist is a digital entertainment and streaming service that grants music lovers access to stream and download unlimited music. MePlaylist studies your tastes and preferences, creates custom-curated playlists on your feeds.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1684139985",
    name: "Mixcloud",
    code: "via IIP-DDS",
    description: "Mixcloud is an online platform for user-generated long-form audio content such as DJ mixes, radio shows and podcasts.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "3874608116",
    name: "mora [HD]",
    code: "A",
    description: "A la carte download (HD audio)",
    territories: ["World"],
    availability: "Immediately",
    isHD: true,
    serviceType: "DOWNLOAD"
  },
  {
    dspId: "3810399865",
    name: "mora [SD]",
    code: "A",
    description: "A la carte download.",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "DOWNLOAD"
  },
  {
    dspId: "3730648038",
    name: "Muska",
    code: "via IIP-DDS",
    description: "Muska is a music streaming app.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1674795424",
    name: "NAVER VIBE",
    code: "via IIP-DDS",
    description: "music service, operation, delivery, marketing",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1382854531",
    name: "NetEase Cloud Music",
    code: "via IIP-DDS",
    description: "Launched in 2013 by NetEase, Inc., NetEase Cloud Music is a leading interactive music streaming service provider in China with more than 800 million registered users. Dedicated to providing an elevated user experience, NetEase Cloud Music provides precise, personalized recommendations, promotes user interaction and creates a strong social community – with probably the most socially engaged music fans in the world. Its focus on discovering and promoting emerging musicians has made NetEase Cloud Music a destination of choice for exploring new and independent music among music enthusiasts in China – it has also become the platform of choice for fans of international music in China. The platform has been recognized as the most popular entertainment app among China's vibrant Generation Z community.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "464139",
    name: "Nuuday A/S",
    code: "via IIP-DDS",
    description: "Providing digital music to mobile and broadband subscribers via the telco services YouSee and Telmore.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "3807021043",
    name: "orimyustore",
    code: "A",
    description: "Music download service",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "DOWNLOAD"
  },
  {
    dspId: "7851192",
    name: "Pandora",
    code: "via IIP-DDS",
    description: "Pandora is the world's most powerful music discovery platform – a place where artists find their fans and listeners find music they love. We are driven by a single purpose: unleashing the infinite power of music by connecting artists and fans, whether through earbuds, car speakers, live on stage or anywhere fans want to experience it. Our team of highly trained musicologists analyze hundreds of attributes for each recording which powers our proprietary Music Genome Project®, delivering billions of hours of personalized music tailored to the tastes of each music listener, full of discovery, making artist/fan connections at unprecedented scale. Founded by musicians, Pandora empowers artists with valuable data and tools to help grow their careers and connect with their fans.",
    territories: ["Americas (United States of America)"],
    availability: "Immediately",
    serviceType: "RADIO"
  },
  {
    dspId: "2528780514",
    name: "Peloton",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "2406442214",
    name: "Pretzel Rocks",
    code: "via IIP-DDS",
    description: "Pretzel Rocks is a streaming music solution for broadcasters on Twitch, Mixer, YouTube Gaming and Facebook Gaming. With Pretzel, broadcasters do not have to worry about DMCA or copyright infringement strikes against their channels. Pretzel enables broadcasters to promote the music they love while compensating rights holders fairly, both financially and through marketing initiatives.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "9940949",
    name: "Qobuz",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1001270022599",
    name: "Simbals",
    code: "via IIP-DDS",
    description: "Simbals is a company specializing in audio-related technology, offering advanced tools for music analysis, sound recognition, and audio fingerprinting. Their technology employs machine learning to accurately identify and break down music into its core components, aiding in tasks such as copyright management, music recommendation, and detailed musicological analysis. Simbals' solutions are useful for various applications, including music production, streaming services, and sound recognition across different fields.",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "FINGERPRINTING"
  },
  {
    dspId: "35299696",
    name: "SoundCloud",
    code: "via IIP-DDS",
    description: "Deliver your catalogue to SoundCloud's content filtering system to block infringements and manage your rights via their CMS",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "746109",
    name: "Spotify",
    code: "via IIP-DDS",
    description: "Spotify is a new way to enjoy music. Simply download and install, before you know it you'll be singing along to the genre, artist or song of your choice. With Spotify you are never far away from the song you want. There are no restrictions in terms of what you can listen to or when. Forget about the hassle of waiting for files to download and fill up your hard drive before you get round to organising them. Spotify is instant, fun and simple. Because music is social, Spotify allows you to share songs and playlists with friends, and even work together on collaborative playlists, Friday afternoon in the office might never be the same again! We're music lovers like everyone else. We want to connect millions of people with their favorite songs by creating a product that people love to use. We respect creativity and believe in fairly compensating artists for their work. We've cleared the rights to use the music you'll listen to in Spotify.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "2522630811",
    name: "Spotify Video",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "VIDEO"
  },
  {
    dspId: "1234931270",
    name: "Taobao",
    code: "via IIP-DDS",
    description: "A e-commerce platform that also enables users share contents including short videos & pics.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1461025062",
    name: "Tencent",
    code: "via IIP-DDS",
    territories: ["Asia (China)"],
    availability: "Immediately"
  },
  {
    dspId: "3440259",
    name: "TIDAL",
    code: "via IIP-DDS",
    description: "TIDAL is a global music and entertainment platform that brings artists and fans together through unique music and content experiences and is currently available in 52 countries. TIDAL has over 49.2 million songs in our catalog and over 179,000 high quality videos, offering passionate music fans both a premium and high fidelity sound quality, along with high resolution video, and expertly curated editorial content. TIDAL provides a 30 day free trial period to all new customers on both subscription tiers.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "1809226414",
    name: "TikTok",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "SOCIAL"
  },
  {
    dspId: "1130831671",
    name: "TouchTunes",
    code: "via IIP-DDS",
    description: "TouchTunes is the largest in-venue interactive music and entertainment platform, featured in over 71,000 bars and restaurants across North America and Europe. TouchTunes' platform provides location-based digital solutions that encourage social interactions through shared experiences. Music is at the core of TouchTunes' experience with millions of songs played daily across the network and a mobile app that lets users find nearby jukebox locations, create playlists, and control the music in-venue directly from their phone. The mobile app is available on the iOS and Android platforms and has been downloaded over 3.5 million times. TouchTunes' award-winning products and services also include an integrated photo booth, the first fully licensed commercial karaoke system and an interactive TV messaging and engagement solution.",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "4668622402",
    name: "Trebel Music",
    code: "via IIP-DDS",
    description: "TREBEL Music is an ad-supported download and play service that allows users to listen to their favorite music offline, on-demand, and anytime! Users can search for their favorite tracks, artists or albums; alternatively, they can browse curated playlists from our team.",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "DOWNLOAD"
  },
  {
    dspId: "3874502471",
    name: "U-NEXT",
    code: "A",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "3405271817",
    name: "YouTube Music & Content ID",
    code: "via IIP-DDS",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "3874587629",
    name: "エムティーアイ [HD] (MTI)",
    code: "A",
    description: "Music (HD) / Movies & TV shows / Digital books",
    territories: ["World"],
    availability: "Immediately",
    isHD: true
  },
  {
    dspId: "3874119747",
    name: "エムティーアイ [SD/MV] (MTI)",
    code: "A",
    description: "Music (SD) / Movies & TV shows / Digital books",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "3874630178",
    name: "オトトイ [HD] (OTOTOY)",
    code: "A",
    description: "Music Download (HD audio)",
    territories: ["World"],
    availability: "Immediately",
    isHD: true,
    serviceType: "DOWNLOAD"
  },
  {
    dspId: "3815954181",
    name: "オトトイ [SD] (OTOTOY)",
    code: "A",
    description: "Music Download (SD audio)",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "DOWNLOAD"
  },
  {
    dspId: "3810780576",
    name: "ドワンゴ (Dwango)",
    code: "A",
    description: "Digital Music download",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "DOWNLOAD"
  },
  {
    dspId: "3874749280",
    name: "フェイス (Faith)",
    code: "A",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "3654981364",
    name: "モンスターラボ (Monstar Lab)",
    code: "A",
    description: "BtoB non-interactive streaming service (offer BGM to retail shops & offices)",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "OTHER"
  },
  {
    dspId: "3874249365",
    name: "ヤマハ (YAMAHA)",
    code: "A",
    description: "A la carte download service",
    territories: ["World"],
    availability: "Immediately",
    serviceType: "DOWNLOAD"
  },
  {
    dspId: "3874574051",
    name: "レコチョク [HD] (Recochoku)",
    code: "A",
    description: "Numerous download and subscription streaming services, as well as bundle services with carriers (telecom companies) https://recochoku.jp/corporate/service/",
    territories: ["World"],
    availability: "Immediately",
    isHD: true
  },
  {
    dspId: "3654377854",
    name: "レコチョク [SD/MV] (Recochoku)",
    code: "A",
    description: "Numerous download and subscription streaming services, as well as bundle services with carriers (telecom companies) https://recochoku.jp/corporate/service/",
    territories: ["World"],
    availability: "Immediately"
  },
  {
    dspId: "3406622740",
    name: "楽天 (Rakuten)",
    code: "A",
    territories: ["World"],
    availability: "Immediately"
  }
];