name: Build Only (No Deploy)

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: ddalgiwuu/n3rve-platform

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image (no push)
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: false
        tags: |
          ${{ env.DOCKER_IMAGE }}:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build success
      run: |
        echo "✅ Docker build completed successfully!"
        echo "Image would be tagged as: ${{ env.DOCKER_IMAGE }}:test"