name: Test Deployment Configuration

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check secrets availability
      run: |
        echo "Testing secret availability..."
        
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "❌ DOCKER_USERNAME secret is not set"
        else
          echo "✅ DOCKER_USERNAME is configured"
        fi
        
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "❌ DOCKER_PASSWORD secret is not set"
        else
          echo "✅ DOCKER_PASSWORD is configured"
        fi
        
        if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
          echo "❌ EC2_SSH_KEY secret is not set"
        else
          echo "✅ EC2_SSH_KEY is configured"
        fi
        
    - name: Test Docker Hub connection
      if: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Test EC2 connectivity
      if: ${{ secrets.EC2_SSH_KEY != '' }}
      run: |
        echo "Testing EC2 connectivity..."
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -i key.pem ubuntu@52.78.81.116 'echo "✅ EC2 connection successful"' || echo "❌ EC2 connection failed"
        rm key.pem